from _typeshed import StrOrBytesPath
from collections.abc import Sequence
from typing import Any, ClassVar, TypeVar, overload
from typing_extensions import TypeAlias

import numpy as np
from numpy.typing import ArrayLike, DTypeLike, NDArray

_T = TypeVar("_T")

# One entry of the per-axis metadata list. Recognised keys are ``name``,
# ``title``, ``units``, ``values`` (an ndarray of axis coordinates) and
# ``cols`` (a list of column descriptions); any other key is carried along
# untouched. The list is always ``ndim + 1`` long -- the final entry holds
# metadata for the array as a whole.
_AxisInfo: TypeAlias = dict[str, Any]
# Anything accepted where an axis is named: an integer index, or a name
# (``str`` or ``tuple``) looked up in the ``name`` key of the axis info.
_AxisArg: TypeAlias = int | str | tuple[Any, ...]

USE_HDF5: bool
HAVE_HDF5: bool

def axis(name: str | None = None, cols=None, values: ArrayLike | None = None, units: str | None = None) -> _AxisInfo: ...

class sliceGenerator:
    def __getitem__(self, arg: _T) -> _T: ...
    def __getslice__(self, arg: _T) -> _T: ...

SLICER: sliceGenerator

class MetaArray:
    version: ClassVar[str]
    # ``None``, an h5py compression name, or a ``(filter, opts)`` pair.
    defaultCompression: ClassVar[str | tuple[str, int] | None]
    nameTypes: ClassVar[list[type]]
    @staticmethod
    def isNameType(var: object) -> bool: ...
    wrapMethods: ClassVar[set[str]]
    def __init__(
        self,
        data: MetaArray | ArrayLike | tuple[int, ...] | None = None,
        info: Sequence[_AxisInfo] | None = None,
        dtype: DTypeLike | None = None,
        file: StrOrBytesPath | None = None,
        copy: bool = False,
        **kwargs,
    ) -> None: ...
    def checkInfo(self) -> None: ...
    @overload
    def implements(self, name: None = None) -> list[str]: ...
    @overload
    def implements(self, name: str) -> bool: ...
    # A `MetaArray` when the index selects a sub-array, otherwise the single
    # element the index picks out. Named indexing is supported:
    # ``arr['axisName':'columnName']``, ``arr['axisName':minVal:maxVal]``.
    def __getitem__(self, ind) -> Any: ...
    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> np.dtype[Any]: ...
    def __len__(self) -> int: ...
    def __getslice__(self, *args) -> Any: ...
    def __setitem__(self, ind, val) -> None: ...
    def __getattr__(self, attr: str): ...
    def __eq__(self, b: object) -> Any: ...
    def __ne__(self, b: object) -> Any: ...
    def __sub__(self, b: MetaArray | ArrayLike) -> MetaArray: ...
    def __add__(self, b: MetaArray | ArrayLike) -> MetaArray: ...
    def __mul__(self, b: MetaArray | ArrayLike) -> MetaArray: ...
    def __div__(self, b: MetaArray | ArrayLike) -> MetaArray: ...
    def __truediv__(self, b: MetaArray | ArrayLike) -> MetaArray: ...
    def asarray(self) -> NDArray[Any]: ...
    def __array__(self, dtype: DTypeLike | None = None) -> NDArray[Any]: ...
    def axisValues(self, axis: _AxisArg) -> NDArray[Any]: ...
    def xvals(self, axis: _AxisArg) -> NDArray[Any]: ...
    def axisHasValues(self, axis: _AxisArg) -> bool: ...
    def axisHasColumns(self, axis: _AxisArg) -> bool: ...
    def axisUnits(self, axis: _AxisArg) -> str | None: ...
    def hasColumn(self, axis: _AxisArg, col: str) -> bool: ...
    @overload
    def listColumns(self, axis: None = None) -> dict[str | int, list[str]]: ...
    @overload
    def listColumns(self, axis: _AxisArg) -> list[str]: ...
    def columnName(self, axis: _AxisArg, col: int) -> str: ...
    # The axis' ``name`` if it has one, otherwise ``n`` itself.
    def axisName(self, n: int) -> str | int: ...
    def columnUnits(self, axis: _AxisArg, column: str) -> str: ...
    def rowsort(self, axis: int | str, key: int = 0) -> MetaArray: ...
    def append(self, val, axis: _AxisArg) -> MetaArray: ...
    def extend(self, val, axis: _AxisArg) -> MetaArray: ...
    @overload
    def infoCopy(self, axis: None = None) -> list[_AxisInfo]: ...
    @overload
    def infoCopy(self, axis: _AxisArg) -> _AxisInfo: ...
    def copy(self) -> MetaArray: ...
    def prettyInfo(self) -> str: ...
    # `fn` names a method of the wrapped ndarray ('mean', 'min', 'max', ...).
    def axisCollapsingFn(self, fn: str, axis: _AxisArg | None = None, *args, **kargs) -> Any: ...
    def mean(self, axis: _AxisArg | None = None, *args, **kargs) -> Any: ...
    def min(self, axis: _AxisArg | None = None, *args, **kargs) -> Any: ...
    def max(self, axis: _AxisArg | None = None, *args, **kargs) -> Any: ...
    def transpose(self, *args: _AxisArg | Sequence[_AxisArg]) -> MetaArray: ...
    # `kwargs` are forwarded to the reader: `writable`, `readAllData`, `mmap`, `subset`.
    def readFile(self, filename: StrOrBytesPath, **kwargs) -> None: ...
    @staticmethod
    def mapHDF5Array(data, writable: bool = False) -> np.memmap[Any, np.dtype[Any]]: ...
    @staticmethod
    def readHDF5Meta(root, mmap: bool = False) -> dict[str, Any] | list[Any] | tuple[Any, ...]: ...
    # `opts`: appendAxis, appendKeys, compression, chunks, mappable.
    def write(self, fileName: StrOrBytesPath, **opts) -> None: ...
    def writeMeta(self, fileName: StrOrBytesPath) -> None: ...
    def writeHDF5(self, fileName: StrOrBytesPath, **opts) -> None: ...
    def writeHDF5Meta(self, root, name: str, data, **dsOpts) -> None: ...
    def writeMa(self, fileName: StrOrBytesPath, appendAxis: _AxisArg | None = None, newFile: bool = False) -> None: ...
    # Returns the CSV text when `fileName` is None, otherwise writes it and returns None.
    def writeCsv(self, fileName: StrOrBytesPath | None = None) -> str | None: ...
