# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..graphicsItems.ROI import ROI
from ..graphicsItems.ViewBox import ViewBox
from ..Qt import QtWidgets
from .CanvasItem import CanvasItem, GroupCanvasItem

__all__ = ["Canvas"]

class Canvas(QtWidgets.QWidget):
    sigSelectionChanged: Incomplete
    sigItemTransformChanged: Incomplete
    sigItemTransformChangeFinished: Incomplete
    ui: Incomplete
    view: ViewBox
    itemList: Incomplete  # TreeWidget
    allowTransforms: bool
    multiSelectBox: SelectBox
    redirect: Canvas | None
    items: list[CanvasItem]
    grid: CanvasItem
    hideBtn: Incomplete  # QPushButton
    ctrlSize: int
    sizeApplied: bool
    registeredName: str
    menu: Incomplete  # QMenu
    def __init__(self, parent=None, allowTransforms: bool = True, hideCtrl: bool = False, name: str | None = None) -> None: ...
    def splitterMoved(self) -> None: ...
    def hideBtnClicked(self) -> None: ...
    def autoRange(self) -> None: ...
    def resizeEvent(self, ev=None) -> None: ...
    def updateRedirect(self, *args) -> None: ...
    def redirectItems(self, canvas: Canvas) -> None: ...
    def reclaimItems(self) -> None: ...
    def treeItemChanged(self, item, col: int) -> None: ...
    def treeItemSelected(self) -> None: ...
    def selectedItems(self) -> list[CanvasItem]: ...
    def selectItem(self, item: CanvasItem) -> None: ...
    def showMultiSelectBox(self) -> None: ...
    def mirrorSelectionClicked(self) -> None: ...
    def reflectSelectionClicked(self) -> None: ...
    def resetTransformsClicked(self) -> None: ...
    def multiSelectBoxChanged(self) -> None: ...
    def multiSelectBoxChangeFinished(self) -> None: ...
    def multiSelectBoxMoved(self) -> None: ...
    # `opts` are the CanvasItem options: name, z, movable, scalable, rotatable, visible, parent,
    # and either transform or pos/angle/scale.
    def addGraphicsItem(self, item, **opts) -> CanvasItem: ...
    # `kargs` is passed on to addItem(), which accepts no keyword arguments; only an empty
    # `kargs` actually works.
    def addGroup(self, name: str | None, **kargs) -> GroupCanvasItem: ...
    def addItem(self, citem: CanvasItem) -> CanvasItem: ...
    def treeItemMoved(self, item, parent, index: int) -> None: ...
    def itemVisibilityChanged(self, item: CanvasItem) -> None: ...
    # `item` is a CanvasItem, a QTreeWidgetItem, or a graphics item previously added
    # through addGraphicsItem().
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
    def addToScene(self, item) -> None: ...
    def removeFromScene(self, item) -> None: ...
    def listItems(self) -> list[CanvasItem]: ...
    # `name` indexes into the item *list*, so only an integer index works.
    def getListItem(self, name) -> CanvasItem: ...
    def itemTransformChanged(self, item: CanvasItem) -> None: ...
    def itemTransformChangeFinished(self, item: CanvasItem) -> None: ...
    menuItem: Incomplete  # QTreeWidgetItem | None
    def itemListContextMenuEvent(self, ev) -> None: ...
    def removeClicked(self) -> None: ...

class SelectBox(ROI):
    def __init__(self, scalable: bool = False) -> None: ...
