# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing import ClassVar

from ..Qt import QtCore, QtWidgets

class CanvasManager(QtCore.QObject):
    SINGLETON: ClassVar[CanvasManager | None]
    sigCanvasListChanged: Incomplete
    canvases: dict[str, Incomplete]
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> CanvasManager: ...
    def registerCanvas(self, canvas, name: str) -> str: ...
    def unregisterCanvas(self, name: str) -> None: ...
    def listCanvases(self) -> list[str]: ...
    def getCanvas(self, name: str): ...

manager: CanvasManager

class CanvasCombo(QtWidgets.QComboBox):
    hostName: str | None
    def __init__(self, parent=None) -> None: ...
    def updateCanvasList(self) -> None: ...
    def setHostName(self, name: str) -> None: ...
