# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing import ClassVar, TypedDict

from ..graphicsItems.ROI import ROI, _ROIState
from ..Qt import QtCore
from ..SRTTransform import SRTTransform, _SRTState
from .Canvas import Canvas

__all__ = ["CanvasItem", "GroupCanvasItem"]

class _CanvasItemState(TypedDict):
    type: str
    name: str
    visible: bool
    alpha: float
    userTransform: _SRTState
    z: float | None
    scalable: bool
    rotatable: bool
    movable: bool

class SelectBox(ROI):
    def __init__(self, scalable: bool = False, rotatable: bool = True) -> None: ...

class CanvasItem(QtCore.QObject):
    sigResetUserTransform: Incomplete
    sigTransformChangeFinished: Incomplete
    sigTransformChanged: Incomplete
    sigVisibilityChanged: Incomplete
    transformCopyBuffer: ClassVar[_SRTState | None]
    # keys: name, z, movable, scalable, rotatable, visible, parent, and either
    # transform or pos/angle/scale
    opts: dict[str, Incomplete]
    selectedAlone: bool
    canvas: Canvas | None
    ctrl: Incomplete  # QWidget
    layout: Incomplete  # QGridLayout
    alphaLabel: Incomplete  # QLabel
    alphaSlider: Incomplete  # QSlider
    resetTransformBtn: Incomplete  # QPushButton
    copyBtn: Incomplete  # QPushButton
    pasteBtn: Incomplete  # QPushButton
    transformWidget: Incomplete  # QWidget
    transformGui: Incomplete  # TransformGuiTemplate_generic.Ui_Form
    baseTransform: SRTTransform
    selectBox: SelectBox
    itemRotation: Incomplete  # QGraphicsRotation
    itemScale: Incomplete  # QGraphicsScale
    tempTransform: SRTTransform
    userTransform: SRTTransform
    def __init__(self, item, **opts) -> None: ...
    def setMovable(self, m: bool) -> None: ...
    def setCanvas(self, canvas: Canvas | None) -> None: ...
    def graphicsItem(self): ...
    def parentItem(self) -> CanvasItem | None: ...
    # `parent` is a CanvasItem, a QGraphicsItem, or None
    def setParentItem(self, parent) -> None: ...
    def copyClicked(self) -> None: ...
    def pasteClicked(self) -> None: ...
    def mirrorY(self) -> None: ...
    def mirrorXY(self) -> None: ...
    def hasUserTransform(self) -> bool: ...
    def ctrlWidget(self): ...
    def alphaChanged(self, val: float) -> None: ...
    def setAlpha(self, alpha: float) -> None: ...
    def alpha(self) -> float: ...
    def isMovable(self) -> bool: ...
    def selectBoxMoved(self) -> None: ...
    def scale(self, x: float, y: float) -> None: ...
    def rotate(self, ang: float) -> None: ...
    def translate(self, x: float, y: float) -> None: ...
    def setTranslate(self, x: float, y: float) -> None: ...
    def setRotate(self, angle: float) -> None: ...
    def setScale(self, x: float, y: float) -> None: ...
    def setTemporaryTransform(self, transform: SRTTransform) -> None: ...
    def applyTemporaryTransform(self) -> None: ...
    def resetTemporaryTransform(self) -> None: ...
    def transform(self): ...
    def updateTransform(self) -> _SRTState: ...
    def displayTransform(self, transform: SRTTransform) -> None: ...
    def resetUserTransform(self) -> None: ...
    def resetTransformClicked(self) -> None: ...
    def restoreTransform(self, tr: _SRTState) -> None: ...
    def saveTransform(self) -> _SRTState: ...
    def selectBoxFromUser(self) -> None: ...
    itemRect: Incomplete  # QRectF
    selectBoxBase: _ROIState
    def selectBoxToItem(self) -> None: ...
    def zValue(self) -> float | None: ...
    def setZValue(self, z: float | None) -> None: ...
    def selectionChanged(self, sel: bool, multi: bool) -> None: ...
    def showSelectBox(self) -> None: ...
    def hideSelectBox(self) -> None: ...
    def selectBoxChanged(self) -> None: ...
    def selectBoxChangeFinished(self) -> None: ...
    def alphaPressed(self) -> None: ...
    def alphaReleased(self) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def setVisible(self, vis: bool) -> None: ...
    def isVisible(self) -> bool: ...
    def saveState(self) -> _CanvasItemState: ...
    def restoreState(self, state: _CanvasItemState) -> None: ...

class GroupCanvasItem(CanvasItem):
    def __init__(self, **opts) -> None: ...
