# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtCore, QtWidgets  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]

class CanvasManager(QtCore.QObject):
    SINGLETON: Incomplete
    sigCanvasListChanged: Incomplete
    canvases: Incomplete
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls): ...
    def registerCanvas(self, canvas, name): ...
    def unregisterCanvas(self, name) -> None: ...
    def listCanvases(self): ...
    def getCanvas(self, name): ...

manager: Incomplete

class CanvasCombo(QtWidgets.QComboBox):
    hostName: Incomplete
    def __init__(self, parent=None) -> None: ...
    def updateCanvasList(self) -> None: ...
    def setHostName(self, name) -> None: ...
