from _typeshed import Incomplete
from collections.abc import Mapping, Sequence
from typing import Any, Literal
from typing_extensions import TypeAlias

from ..AxisItem import AxisItem
from ..GraphicsWidget import GraphicsWidget
from ..LegendItem import LegendItem
from ..PlotDataItem import PlotDataItem
from ..ViewBox import ViewBox

__all__ = ["PlotItem"]

_AxisName: TypeAlias = Literal["left", "bottom", "right", "top"]
# `ViewBox.XAxis`, `YAxis` or `XYAxes`.
_Axis: TypeAlias = Literal[0, 1, 2]
_Range: TypeAlias = Sequence[float]

class PlotItem(GraphicsWidget):
    sigRangeChanged: Incomplete
    sigYRangeChanged: Incomplete
    sigXRangeChanged: Incomplete
    lastFileDir: Incomplete
    autoBtn: Incomplete
    buttonsHidden: bool
    mouseHovering: bool
    layout: Incomplete
    vb: ViewBox
    alpha: float
    autoAlpha: bool
    spectrumMode: bool
    legend: LegendItem | None
    axes: dict[str, dict[str, Incomplete]]
    titleLabel: Incomplete
    items: list[Incomplete]
    curves: list[Incomplete]
    itemMeta: Incomplete
    dataItems: list[Incomplete]
    paramList: Incomplete
    avgCurves: dict[Incomplete, Incomplete]
    avgPen: Incomplete
    avgShadowPen: Incomplete
    ctrl: Incomplete
    ctrlMenu: Incomplete
    stateGroup: Incomplete
    fileDialog: Incomplete
    def __init__(
        self,
        parent=None,
        name: str | None = None,
        labels: Mapping[str, str | tuple[str, str]] | None = None,
        title: str | None = None,
        viewBox: ViewBox | None = None,
        axisItems: Mapping[str, AxisItem] | None = None,
        enableMenu: bool = True,
        **kargs,
    ) -> None: ...
    def implements(self, interface: str | None = None) -> bool: ...
    def getViewBox(self) -> ViewBox: ...
    def setAxisItems(self, axisItems: Mapping[str, AxisItem] | None = None) -> None: ...
    def setLogMode(self, x: bool | None = None, y: bool | None = None) -> None: ...
    def showGrid(self, x: bool | None = None, y: bool | None = None, alpha: float | None = None) -> None: ...
    def close(self) -> None: ...
    def registerPlot(self, name: str) -> None: ...
    def updateGrid(self, *args) -> None: ...
    def viewGeometry(self): ...
    def avgToggled(self, b) -> None: ...
    def avgParamListClicked(self, item) -> None: ...
    def recomputeAverages(self) -> None: ...
    def addAvgCurve(self, curve) -> None: ...
    def autoBtnClicked(self) -> None: ...
    def viewStateChanged(self) -> None: ...
    def addItem(self, item, *args, **kargs) -> None: ...
    def listDataItems(self) -> list[Incomplete]: ...
    def addLine(self, x: float | None = None, y: float | None = None, z: float | None = None, **kwds): ...
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
    def clearPlots(self) -> None: ...
    def plot(self, *args, **kargs) -> PlotDataItem: ...
    def addLegend(self, offset: Sequence[float] | None = (30, 30), **kwargs) -> LegendItem: ...
    def addColorBar(self, image, **kargs): ...
    def multiDataPlot(self, *, x=None, y=None, constKwargs: Mapping[str, Any] | None = None, **kwargs) -> list[PlotDataItem]: ...
    def scatterPlot(self, *args, **kargs) -> PlotDataItem: ...
    def replot(self) -> None: ...
    def updateParamList(self) -> None: ...
    def writeSvg(self, fileName: str | None = None) -> None: ...
    def writeImage(self, fileName: str | None = None) -> None: ...
    def writeCsv(self, fileName: str | None = None) -> None: ...
    def saveState(self) -> dict[str, Incomplete]: ...
    def restoreState(self, state: Mapping[str, Incomplete]) -> None: ...
    def widgetGroupInterface(self): ...
    def updateSpectrumMode(self, b=None) -> None: ...
    def updateLogMode(self) -> None: ...
    def updateDerivativeMode(self) -> None: ...
    def updatePhasemapMode(self) -> None: ...
    def setDownsampling(
        self, ds: int | None = None, auto: bool | None = None, mode: Literal["subsample", "mean", "peak"] | None = None
    ) -> None: ...
    def updateDownsampling(self) -> None: ...
    def downsampleMode(self) -> tuple[int, bool, str]: ...
    def setClipToView(self, clip: bool) -> None: ...
    def clipToViewMode(self) -> bool: ...
    def updateDecimation(self) -> None: ...
    def updateAlpha(self, *args) -> None: ...
    def alphaState(self) -> tuple[float, bool]: ...
    def pointMode(self): ...
    def resizeEvent(self, ev) -> None: ...
    def getMenu(self): ...
    def getContextMenus(self, event): ...
    def setMenuEnabled(self, enableMenu: bool = True, enableViewBoxMenu: bool | Literal["same"] | None = "same") -> None: ...
    def menuEnabled(self) -> bool: ...
    def setContextMenuActionVisible(self, name: str, visible: bool) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def getLabel(self, key: _AxisName) -> None: ...
    def getScale(self, key: _AxisName) -> AxisItem: ...
    def getAxis(self, name: _AxisName) -> AxisItem: ...
    def setLabel(
        self, axis: _AxisName, text: str | None = None, units: str | None = None, unitPrefix: str | None = None, **args
    ) -> None: ...
    def setLabels(self, **kwds) -> None: ...
    def showLabel(self, axis: _AxisName, show: bool = True) -> None: ...
    def setTitle(self, title: str | None = None, **args) -> None: ...
    def showAxis(self, axis: _AxisName, show: bool = True) -> None: ...
    def hideAxis(self, axis: _AxisName) -> None: ...
    def showAxes(
        self, selection: bool | Sequence[bool], showValues: bool | Sequence[bool] = True, size: bool | Sequence[float] = False
    ) -> None: ...
    def hideButtons(self) -> None: ...
    def showButtons(self) -> None: ...
    def updateButtons(self) -> None: ...
    def setExportMode(self, export, opts=None) -> None: ...
    # Inherited from ViewBox:
    def register(self, name: str) -> None: ...
    def unregister(self) -> None: ...
    def setMouseEnabled(self, x: bool | None = None, y: bool | None = None) -> None: ...
    def viewRange(self) -> list[list[float]]: ...
    def viewRect(self): ...
    def setRange(
        self,
        rect=None,
        xRange: _Range | None = None,
        yRange: _Range | None = None,
        padding: float | None = None,
        update: bool = True,
        disableAutoRange: bool = True,
    ) -> None: ...
    def setYRange(self, min: float, max: float, padding: float | None = None, update: bool = True) -> None: ...
    def setXRange(self, min: float, max: float, padding: float | None = None, update: bool = True) -> None: ...
    def autoRange(self, padding: float | None = None, items: Sequence[Incomplete] | None = None, item=None) -> None: ...
    def setLimits(self, **kwds) -> None: ...
    def enableAutoRange(
        self,
        axis: _Axis | str | None = None,
        enable: bool | float = True,
        x: bool | float | None = None,
        y: bool | float | None = None,
    ) -> None: ...
    def disableAutoRange(self, axis: _Axis | str | None = None) -> None: ...
    def setAutoPan(self, x: bool | None = None, y: bool | None = None) -> None: ...
    def setAutoVisible(self, x: bool | None = None, y: bool | None = None) -> None: ...
    def setXLink(self, view: ViewBox | str | None) -> None: ...
    def setYLink(self, view: ViewBox | str | None) -> None: ...
    def invertY(self, b: bool = True) -> None: ...
    def invertX(self, b: bool = True) -> None: ...
    def setDefaultPadding(self, padding: float = 0.02) -> None: ...
    def setAspectLocked(self, lock: bool = True, ratio: float | None = 1) -> None: ...
