from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, ClassVar, Literal, overload
from typing_extensions import TypeAlias

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .functions import _ColorArg

__all__ = ["ColorMap"]

# `ColorMap.CLIP`/`REPEAT`/`MIRROR`/`DIVERGING`, or the matching `enumMap` key.
_MappingMode: TypeAlias = Literal[1, 2, 3, 4, "clip", "repeat", "mirror", "diverging"]
# `ColorMap.BYTE`/`FLOAT`/`QCOLOR`, or the matching `enumMap` key.
_ReturnMode: TypeAlias = Literal[1, 2, 3, "byte", "float", "qcolor"]
_Source: TypeAlias = Literal["matplotlib", "colorcet"]

def listMaps(source: _Source | None = None) -> list[str]: ...
def get(name: str, source: _Source | None = None, skipCache: bool = False) -> ColorMap | None: ...
def getFromMatplotlib(name: str) -> ColorMap | None: ...
def getFromColorcet(name: str) -> ColorMap | None: ...
def makeHslCycle(
    hue: float | tuple[float, float] = 0.0,
    saturation: float | tuple[float, float] = 1.0,
    lightness: float | tuple[float, float] = 0.5,
    steps: int = 36,
) -> ColorMap: ...
def makeMonochrome(
    color: (
        Literal["neutral", "warm", "cool", "green", "amber", "blue", "red", "pink", "lavender"]
        | tuple[float]
        | tuple[float, float]
        | tuple[float, float, float, float]
    ) = "neutral",
) -> ColorMap: ...
def modulatedBarData(length: int = 768, width: int = 32) -> NDArray[np.float64]: ...

class ColorMap:
    # Mapping modes
    CLIP: ClassVar[Literal[1]]
    REPEAT: ClassVar[Literal[2]]
    MIRROR: ClassVar[Literal[3]]
    DIVERGING: ClassVar[Literal[4]]
    # Return types
    BYTE: ClassVar[Literal[1]]
    FLOAT: ClassVar[Literal[2]]
    QCOLOR: ClassVar[Literal[3]]
    enumMap: ClassVar[dict[str, int]]
    name: str
    pos: NDArray[np.float64]
    color: NDArray[np.float64]
    mapping_mode: int
    stopsCache: dict[int, tuple[NDArray[np.float64], NDArray[Any]]]
    def __init__(
        self,
        pos: ArrayLike | None,
        color: Sequence[_ColorArg] | NDArray[Any],
        mapping: _MappingMode | None = 1,
        mode=None,
        linearize: bool = False,
        name: str = "",
    ) -> None: ...
    def setMappingMode(self, mapping: _MappingMode) -> None: ...
    # An `int` key selects a stop by index, a `float` key samples the map.
    def __getitem__(self, key: float): ...
    def linearize(self) -> None: ...
    def reverse(self) -> None: ...
    def getSubset(self, start: float, span: float) -> ColorMap: ...
    @overload
    def map(self, data: float | ArrayLike, mode: Literal[3, "qcolor"]): ...
    @overload
    def map(self, data: float | ArrayLike, mode: _ReturnMode = 1) -> NDArray[Any]: ...
    def mapToQColor(self, data: float | ArrayLike): ...
    def mapToByte(self, data: float | ArrayLike) -> NDArray[np.ubyte]: ...
    def mapToFloat(self, data: float | ArrayLike) -> NDArray[np.float64]: ...
    def getByIndex(self, idx: int): ...
    def getGradient(self, p1=None, p2=None): ...
    def getBrush(self, span: tuple[float, float] = (0.0, 1.0), orientation: Literal["vertical", "horizontal"] = "vertical"): ...
    def getPen(
        self,
        span: tuple[float, float] = (0.0, 1.0),
        orientation: Literal["vertical", "horizontal"] = "vertical",
        width: float = 1.0,
    ): ...
    def getColors(self, mode: _ReturnMode = 1): ...
    def getStops(self, mode: _ReturnMode = 1) -> tuple[NDArray[np.float64], Incomplete]: ...
    def getLookupTable(
        self, start: float = 0.0, stop: float = 1.0, nPts: int = 512, alpha: bool | None = None, mode: _ReturnMode = 1
    ) -> NDArray[Any]: ...
    def usesAlpha(self) -> bool: ...
    def isMapTrivial(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
