from _typeshed import Incomplete, StrPath
from collections.abc import Mapping, Sequence

GLOBAL_PATH: str | None

class ParseError(Exception):
    lineNum: int
    line: str
    message: str
    fileName: str | None
    def __init__(self, message: str, lineNum: int, line: str, fileName: str | None = None) -> None: ...

def writeConfigFile(data: Mapping[str, Incomplete], fname: StrPath) -> None: ...
def readConfigFile(fname: StrPath, **scope) -> dict[str, Incomplete]: ...
def appendConfigFile(data: Mapping[str, Incomplete], fname: StrPath) -> None: ...
def genString(data: Mapping[str, Incomplete], indent: str = "") -> str: ...
def parseString(lines: str | Sequence[str], start: int = 0, **scope) -> tuple[int, dict[str, Incomplete]]: ...
def measureIndent(s: str) -> int: ...
