import contextlib
from _typeshed import Incomplete, StrPath, TraceFunction
from collections.abc import Callable, Generator, Mapping, Sequence
from pstats import Stats
from threading import Thread
from types import CodeType, FrameType, TracebackType
from typing import Any, ClassVar, Literal, TextIO, TypeVar
from typing_extensions import Self
from weakref import ReferenceType, WeakValueDictionary

from .Qt import QT_LIB as QT_LIB
from .util.mutex import Mutex

_F = TypeVar("_F", bound=Callable[..., Any])

@contextlib.contextmanager
def open_maybe_console(filename: StrPath | None = None) -> Generator[TextIO]: ...
def ftrace(func: _F) -> _F: ...

class Tracer:
    count: int
    stack: list[str]
    def __init__(self) -> None: ...
    def trace(self, frame: FrameType, event: str, arg) -> TraceFunction: ...
    def stop(self) -> None: ...
    def start(self) -> None: ...
    def frameInfo(self, fr: FrameType) -> str: ...

def warnOnException(func: _F) -> _F: ...
def getExc(indent: int = 4, prefix: str = "|  ", skip: int = 1) -> str: ...
def printExc(msg: str = "", indent: int = 4, prefix: str = "|") -> None: ...
def printTrace(msg: str = "", indent: int = 4, prefix: str = "|") -> None: ...
def backtrace(skip: int = 0) -> str: ...
def formatException(
    exctype: type[BaseException] | None, value: BaseException | None, tb: TracebackType | None, skip: int = 0
) -> list[str]: ...
def printException(exctype: type[BaseException] | None, value: BaseException | None, traceback: TracebackType | None) -> None: ...
def listObjs(regex: str = "Q", typ: type | None = None) -> list[Incomplete]: ...
def findRefPath(
    startObj: object,
    endObj: object,
    maxLen: int = 8,
    restart: bool = True,
    seen: dict[int, list[Incomplete]] | None = None,  # maps {id(obj): [maxLen, subtree]}
    path: list[Incomplete] | None = None,
    ignore: dict[int, None] | None = None,  # a set of object ids
) -> list[list[Incomplete]]: ...
def objString(obj: object) -> str: ...
def refPathString(chain: Sequence[Incomplete]) -> str: ...
def objectSize(
    obj: object, ignore: dict[Incomplete, int] | None = None, verbose: bool = False, depth: int = 0, recursive: bool = False
) -> int: ...

class GarbageWatcher:
    objs: WeakValueDictionary[str, Incomplete]
    allNames: list[str]
    def __init__(self) -> None: ...
    def add(self, obj, name: str) -> None: ...
    def __setitem__(self, name: str, obj) -> None: ...
    def check(self) -> None: ...
    def __getitem__(self, item: str): ...

class Profiler:
    # The comma-separated contents of the PYQTGRAPHPROFILE environment variable: the
    # qualified names of the functions whose profilers are enabled.
    _profilers: ClassVar[list[str]]
    _depth: ClassVar[int]
    _msgs: ClassVar[list[tuple[str, tuple[Incomplete, ...]]]]  # maps {format string: args}
    # Set on the class to disable every profiler, or on an instance to disable just that one.
    disable: bool

    class DisabledProfiler:
        def __init__(self, *args, **kwds) -> None: ...
        def __call__(self, *args) -> None: ...
        def finish(self) -> None: ...
        def mark(self, msg: str | None = None) -> None: ...

    _disabledProfiler: ClassVar[DisabledProfiler]
    # Returns `Profiler._disabledProfiler` — a no-op with the same `__call__`/`mark`/`finish`
    # surface — when `disabled` is True, or when it is "env" and the caller's qualified name is
    # not listed in PYQTGRAPHPROFILE. That union is not expressible: `__new__` may only return a
    # subtype of its own class.
    def __new__(cls, msg: str | None = None, disabled: bool | Literal["env"] = "env", delayed: bool = True) -> Self: ...
    def __call__(self, msg: str | None = None) -> None: ...
    def mark(self, msg: str | None = None) -> None: ...
    def __del__(self) -> None: ...
    def finish(self, msg: str | None = None) -> None: ...
    def flush(self) -> None: ...

def profile(code: str, name: str = "profile_run", sort: str = "cumulative", num: int = 30) -> Stats: ...
def get_all_objects() -> dict[int, Incomplete]: ...
def lookup(oid: int, objects: Mapping[int, Incomplete] | None = None): ...

class ObjTracker:
    allObjs: ClassVar[dict[int, None]]  # a set of the ids of this class's own objects
    startRefs: dict[int, ReferenceType[Any] | None]  # maps {id(obj): weakref}, None if not weak-referenceable
    startCount: dict[type, int]
    newRefs: dict[int, ReferenceType[Any] | None]
    persistentRefs: dict[int, ReferenceType[Any] | None]
    objTypes: dict[int, str]
    objs: list[Incomplete]
    def __init__(self) -> None: ...
    def findNew(self, regex: str) -> list[Incomplete]: ...
    def findPersistent(self, regex: str) -> list[Incomplete]: ...
    def start(self) -> None: ...
    def diff(self, **kargs) -> None: ...  # accepts `showIDs`, passed on to report()
    def __del__(self) -> None: ...
    @classmethod
    def isObjVar(cls, o: object) -> bool: ...
    def collect(self) -> tuple[dict[int, ReferenceType[Any] | None], dict[type, int], dict[int, Incomplete]]: ...
    def forgetRef(self, ref: ReferenceType[Any] | None) -> None: ...
    def rememberRef(self, ref: ReferenceType[Any] | None) -> None: ...
    def lookup(self, oid: int, ref: ReferenceType[Any] | None, objs: Mapping[int, Incomplete] | None = None): ...
    def report(
        self,
        refs: Mapping[int, ReferenceType[Any] | None],
        allobjs: Mapping[int, Incomplete] | None = None,
        showIDs: bool = False,
    ) -> None: ...
    def findTypes(self, refs: Mapping[int, ReferenceType[Any] | None], regex: str) -> list[Incomplete]: ...

def describeObj(
    obj: object, depth: int = 4, path: list[Incomplete] | None = None, ignore: dict[int, None] | None = None
) -> None: ...
def typeStr(obj: object) -> str: ...
def searchRefs(obj: object, *args: str | int): ...
def allFrameObjs() -> list[FrameType | CodeType]: ...
def findObj(regex: str) -> list[Incomplete]: ...
def listRedundantModules() -> None: ...
def walkQObjectTree(obj, counts: dict[str, int] | None = None, verbose: bool = False, depth: int = 0) -> dict[str, int]: ...

QObjCache: dict[int, str]

def qObjectReport(verbose: bool = False) -> None: ...

class PrintDetector:
    stdout: TextIO
    def __init__(self) -> None: ...
    def remove(self) -> None: ...
    def __del__(self) -> None: ...
    def write(self, x: str) -> None: ...
    def flush(self) -> None: ...

def listQThreads() -> None: ...
def pretty(data: object, indent: str = "") -> str: ...

class ThreadTrace:
    interval: float
    lock: Mutex
    logFile: StrPath | None
    def __init__(self, interval: float = 10.0, logFile: StrPath | None = None) -> None: ...
    def stop(self) -> None: ...
    thread: Thread
    def start(self, interval: float | None = None) -> None: ...
    def run(self) -> None: ...

def threadName(threadId: int | None = None) -> str: ...

class ThreadColor:
    colors: ClassVar[dict[Thread, int]]
    lock: ClassVar[Mutex]
    stream: TextIO
    err: bool
    def __init__(self, stream: Literal["stdout", "stderr"]) -> None: ...
    def write(self, msg: str) -> None: ...
    def flush(self) -> None: ...
    def color(self) -> int: ...

def enableFaulthandler() -> bool: ...
