from _typeshed import Incomplete
from collections.abc import Callable
from typing import overload

callbacks: list[Callable[..., Incomplete]]
old_callbacks: list[Callable[..., Incomplete]]
clear_tracebacks: bool

def registerCallback(fn: Callable[..., Incomplete]) -> None: ...
def unregisterCallback(fn: Callable[..., Incomplete]) -> None: ...
def register(fn: Callable[..., Incomplete]) -> None: ...
def unregister(fn: Callable[..., Incomplete]) -> None: ...
def setTracebackClearing(clear: bool = True) -> None: ...

class ExceptionHandler:
    orig_sys_excepthook: Incomplete
    orig_threading_excepthook: Incomplete
    def __init__(self) -> None: ...
    def remove(self) -> None: ...
    def sys_excepthook(self, *args): ...
    def threading_excepthook(self, args): ...
    @overload
    def implements(self, interface: str) -> bool: ...
    @overload
    def implements(self, interface: None = None) -> list[str]: ...

handler: ExceptionHandler
original_excepthook: Incomplete
original_threading_excepthook: Incomplete
