# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Iterator, Sequence
from typing import Literal
from typing_extensions import Self, TypeAlias

from .Qt import QtCore

# Anything that can be turned into a `Point`: a scalar (used for both x and y),
# a length-2 sequence, another `Point`, or a QPointF / QPoint / QSize / QSizeF
# (`Incomplete`, since Qt types are not stubbed).
_PointLike: TypeAlias = float | Sequence[float] | Point | Incomplete

class Point(QtCore.QPointF):
    def __init__(self, *args: _PointLike) -> None: ...
    def __len__(self) -> Literal[2]: ...
    def __reduce__(self) -> tuple[type[Point], tuple[float, float]]: ...
    def __getitem__(self, i: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __setitem__(self, i: int, x: float) -> None: ...
    def __radd__(self, a: _PointLike) -> Point: ...
    def __add__(self, a: _PointLike) -> Point: ...
    def __rsub__(self, a: _PointLike) -> Point: ...
    def __sub__(self, a: _PointLike) -> Point: ...
    def __rmul__(self, a: _PointLike) -> Point: ...
    def __mul__(self, a: _PointLike) -> Point: ...
    def __rdiv__(self, a: _PointLike) -> Point: ...
    def __div__(self, a: _PointLike) -> Point: ...
    def __truediv__(self, a: _PointLike) -> Point: ...
    def __rtruediv__(self, a: _PointLike) -> Point: ...
    def __rpow__(self, a: _PointLike) -> Point: ...
    def __pow__(self, a: _PointLike) -> Point: ...
    def length(self) -> float: ...
    def norm(self) -> Point: ...
    def angle(self, a: _PointLike, units: Literal["degrees", "radians"] = "degrees") -> float: ...
    def dot(self, a: _PointLike) -> float: ...
    def cross(self, a: _PointLike) -> float: ...
    def proj(self, b: Self) -> Point: ...
    def min(self) -> float: ...
    def max(self) -> float: ...
    def copy(self) -> Point: ...
    def toQPoint(self): ...
