import importlib
from _typeshed import Incomplete, StrPath
from collections.abc import Sequence
from types import ModuleType

orig_reload = importlib.reload

def reloadAll(prefix: StrPath | Sequence[StrPath] | None = None, debug: bool = False) -> dict[str, Incomplete]: ...
def reload(module: ModuleType, debug: bool = False, lists: bool = False, dicts: bool = False) -> None: ...
def updateFunction(old, new, debug: bool, depth: int = 0, visited: list[Incomplete] | None = None) -> int | None: ...
def updateClass(old, new, debug: bool) -> None: ...
def safeStr(obj: object) -> str: ...
def getPreviousVersion(obj): ...
