from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Literal, TypedDict
from typing_extensions import TypeAlias

import numpy as np
from numpy.typing import NDArray

from .SRTTransform import SRTTransform
from .Transform3D import Transform3D
from .Vector import Vector

class _SRT3DState(TypedDict):
    pos: tuple[float, float, float]
    scale: tuple[float, float, float]
    angle: float
    axis: tuple[float, float, float]

# A QMatrix4x4, an SRTTransform, a QTransform or a saved state dict.
_SRT3DInit: TypeAlias = _SRT3DState | Incomplete

class SRTTransform3D(Transform3D):
    def __init__(self, init: _SRT3DInit | None = None) -> None: ...
    def getScale(self) -> Vector: ...
    def getRotation(self) -> tuple[float, Vector]: ...
    def getTranslation(self) -> Vector: ...
    def reset(self) -> None: ...
    def translate(self, *args: float | Vector) -> None: ...
    def setTranslate(self, *args: float | Vector) -> None: ...
    def scale(self, *args: float | Vector) -> None: ...
    def setScale(self, *args: float | Vector) -> None: ...
    def rotate(self, angle: float, axis: Sequence[float] | Vector = (0, 0, 1)) -> None: ...
    def setRotate(self, angle: float, axis: Sequence[float] | Vector = (0, 0, 1)) -> None: ...
    def setFromMatrix(self, m: NDArray[Any] | Sequence[Sequence[float]]) -> None: ...
    def as2D(self) -> SRTTransform: ...
    def saveState(self) -> _SRT3DState: ...
    def restoreState(self, state: _SRT3DState) -> None: ...
    def update(self) -> None: ...
    def matrix(self, nd: Literal[2, 3] = 3) -> NDArray[np.float64]: ...
    def __reduce__(self) -> tuple[type[SRTTransform3D], tuple[_SRT3DState]]: ...
