# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing import TypedDict
from typing_extensions import TypeAlias

import numpy as np
from numpy.typing import NDArray

from .Point import Point
from .Qt import QtGui

class _SRTState(TypedDict):
    pos: tuple[float, float]
    scale: tuple[float, float]
    angle: float

# A QTransform, a QMatrix4x4, an SRTTransform3D or a saved state dict.
_SRTInit: TypeAlias = _SRTState | Incomplete

class SRTTransform(QtGui.QTransform):
    def __init__(self, init: _SRTInit | None = None) -> None: ...
    def getScale(self) -> Point: ...
    def getRotation(self) -> float: ...
    def getTranslation(self) -> Point: ...
    def reset(self) -> None: ...
    def setFromQTransform(self, tr) -> None: ...
    def setFromMatrix4x4(self, m) -> None: ...
    def translate(self, *args: float | Point) -> None: ...
    def setTranslate(self, *args: float | Point) -> None: ...
    def scale(self, *args: float | Point) -> None: ...
    def setScale(self, *args: float | Point) -> None: ...
    def rotate(self, angle: float) -> None: ...
    def setRotate(self, angle: float) -> None: ...
    def __truediv__(self, t) -> SRTTransform: ...
    def __div__(self, t) -> SRTTransform: ...
    def __mul__(self, t) -> SRTTransform: ...
    def saveState(self) -> _SRTState: ...
    def __reduce__(self) -> tuple[type[SRTTransform], tuple[_SRTState]]: ...
    def restoreState(self, state: _SRTState) -> None: ...
    def update(self) -> None: ...
    def matrix(self) -> NDArray[np.float64]: ...
