# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from .Qt import QtGui  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]

class Transform3D(QtGui.QMatrix4x4):
    def __init__(self, *args) -> None: ...
    def matrix(self, nd: int = 3): ...
    def map(self, obj): ...
    def inverted(self): ...
