SI_PREFIXES: str
UNITS: list[str]
allUnits: dict[str, float]

def addUnit(prefix: str, val: float) -> None: ...

# `addUnit` injects one module-level float per prefix/unit combination
# (`mV`, `kHz`, `pA`, ...); see `allUnits` for the full set.
def __getattr__(name: str) -> float: ...

# These three are declared but unimplemented upstream; they all return None.
def evalUnits(unitStr: str) -> None: ...
def formatUnits(units) -> None: ...
def simplify(units) -> None: ...
