# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from .Qt import QT_LIB as QT_LIB, QtGui  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]

class Vector(QtGui.QVector3D):
    def __init__(self, *args) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i): ...
    def __setitem__(self, i, x) -> None: ...
    def __iter__(self): ...
    def angle(self, a): ...
    def __abs__(self): ...
