# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Mapping, Sequence

from .Qt import QtCore

__all__ = ["WidgetGroup"]

class WidgetGroup(QtCore.QObject):
    classes: dict[Incomplete, tuple[Incomplete, ...]]
    sigChanged: Incomplete
    widgetList: dict[Incomplete, str]
    scales: dict[Incomplete, float]
    cache: dict[str, Incomplete]
    uncachedWidgets: dict[Incomplete, None]
    # A list of widgets, a list of `(widget, name)` pairs, or a QWidget whose
    # children are added automatically.
    def __init__(self, widgetList: Sequence[Incomplete] | Incomplete | None = None) -> None: ...
    def addWidget(self, w, name: str | None = None, scale: float | None = None) -> None: ...
    def findWidget(self, name: str): ...
    def interface(self, obj): ...
    def checkForChildren(self, obj) -> bool: ...
    def autoAdd(self, obj) -> None: ...
    def acceptsType(self, obj) -> bool: ...
    def setScale(self, widget, scale: float) -> None: ...
    def widgetChanged(self, *args) -> None: ...
    def state(self) -> dict[str, Incomplete]: ...
    def setState(self, s: Mapping[str, Incomplete]) -> None: ...
    def readWidget(self, w): ...
    def setWidget(self, w, v) -> None: ...
