# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing import Literal, TypedDict
from typing_extensions import TypeAlias

from ..Qt import QtWidgets
from .Dock import Dock, DockLabel
from .DockArea import DockArea

__all__ = ["Container", "HContainer", "VContainer", "TContainer"]

class _SplitContainerState(TypedDict):
    sizes: list[int]

class _TabContainerState(TypedDict):
    index: int

# Where `insert()` places the new item relative to `neighbor`.
_InsertPos: TypeAlias = Literal["before", "after"]

class Container:
    area: DockArea | None
    stretches: Incomplete
    def __init__(self, area: DockArea | None) -> None: ...
    def container(self) -> Container | None: ...
    def containerChanged(self, c: Container | None) -> None: ...
    def type(self) -> str | None: ...
    def insert(self, new: Dock | Container | list[Dock | Container], pos: _InsertPos | None = None, neighbor=None) -> None: ...
    def apoptose(self, propagate: bool = True) -> None: ...
    def close(self) -> None: ...
    def childEvent_(self, ev) -> None: ...
    def childStretchChanged(self) -> None: ...
    def setStretch(self, x: float | None = None, y: float | None = None) -> None: ...
    def updateStretch(self) -> None: ...
    def stretch(self) -> tuple[float, float]: ...

class SplitContainer(Container, QtWidgets.QSplitter):
    sigStretchChanged: Incomplete
    # `orientation` is a QtCore.Qt.Orientation.
    def __init__(self, area: DockArea | None, orientation) -> None: ...
    def saveState(self) -> _SplitContainerState: ...
    def restoreState(self, state: _SplitContainerState) -> None: ...
    def childEvent(self, ev) -> None: ...

class HContainer(SplitContainer):
    def __init__(self, area: DockArea | None) -> None: ...
    def type(self) -> Literal["horizontal"]: ...
    def updateStretch(self) -> None: ...

class VContainer(SplitContainer):
    def __init__(self, area: DockArea | None) -> None: ...
    def type(self) -> Literal["vertical"]: ...
    def updateStretch(self) -> None: ...

class StackedWidget(QtWidgets.QStackedWidget):
    container: TContainer
    def __init__(self, *, container: TContainer) -> None: ...
    def childEvent(self, ev) -> None: ...

class TContainer(Container, QtWidgets.QWidget):
    sigStretchChanged: Incomplete
    layout: Incomplete
    hTabLayout: Incomplete
    hTabBox: Incomplete
    stack: StackedWidget
    def __init__(self, area: DockArea | None) -> None: ...
    def tabClicked(self, tab: DockLabel, ev=None) -> None: ...
    def raiseDock(self, dock: Dock) -> None: ...
    def type(self) -> Literal["tab"]: ...
    def saveState(self) -> _TabContainerState: ...
    def restoreState(self, state: _TabContainerState) -> None: ...
    def updateStretch(self) -> None: ...
