# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Iterable
from typing import Literal
from typing_extensions import TypeAlias

from ..Qt import QtWidgets

__all__ = ["DockDrop"]

_DropArea: TypeAlias = Literal["center", "right", "left", "top", "bottom"]

class DockDrop:
    dndWidget: Incomplete
    allowedAreas: set[str]
    dropArea: _DropArea | None
    overlay: DropAreaOverlay
    def __init__(self, dndWidget) -> None: ...
    # The areas are added to a set, so a plain string is split into characters.
    def addAllowedArea(self, area: Iterable[str]) -> None: ...
    def removeAllowedArea(self, area: str) -> None: ...
    # `size` is a QSize.
    def resizeOverlay(self, size) -> None: ...
    def raiseOverlay(self) -> None: ...
    def dragEnterEvent(self, ev) -> None: ...
    def dragMoveEvent(self, ev) -> None: ...
    def dragLeaveEvent(self, ev) -> None: ...
    def dropEvent(self, ev) -> None: ...

class DropAreaOverlay(QtWidgets.QWidget):
    dropArea: _DropArea | None
    def __init__(self, parent) -> None: ...
    def setDropArea(self, area: _DropArea | None) -> None: ...
    def paintEvent(self, ev) -> None: ...
