# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtWidgets  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]

__all__ = ["DockDrop"]

class DockDrop:
    dndWidget: Incomplete
    allowedAreas: Incomplete
    dropArea: Incomplete
    overlay: Incomplete
    def __init__(self, dndWidget) -> None: ...
    def addAllowedArea(self, area) -> None: ...
    def removeAllowedArea(self, area) -> None: ...
    def resizeOverlay(self, size) -> None: ...
    def raiseOverlay(self) -> None: ...
    def dragEnterEvent(self, ev) -> None: ...
    def dragMoveEvent(self, ev) -> None: ...
    def dragLeaveEvent(self, ev) -> None: ...
    def dropEvent(self, ev) -> None: ...

class DropAreaOverlay(QtWidgets.QWidget):
    dropArea: Incomplete
    def __init__(self, parent) -> None: ...
    def setDropArea(self, area) -> None: ...
    def paintEvent(self, ev) -> None: ...
