# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing import Literal, overload
from typing_extensions import TypeAlias

from ..Qt import QtWidgets
from ..widgets.VerticalLabel import VerticalLabel
from .Container import Container
from .DockArea import DockArea

_Orientation: TypeAlias = Literal["vertical", "horizontal"]

class Dock(QtWidgets.QWidget):
    sigStretchChanged: Incomplete
    sigClosed: Incomplete
    dockdrop: Incomplete
    area: DockArea | None
    label: DockLabel
    labelHidden: bool
    # If False, the dock is no longer allowed to move the label.
    moveLabel: bool
    autoOrient: bool
    orientation: _Orientation
    topLayout: Incomplete
    widgetArea: Incomplete
    layout: Incomplete
    widgets: list[Incomplete]
    currentRow: int
    hStyle: str
    vStyle: str
    nStyle: str
    dragStyle: str
    # Extra keyword arguments are passed to `DockLabel()` when `label` is None.
    def __init__(
        self,
        name: str,
        area: DockArea | None = None,
        size: tuple[float, float] = (10, 10),
        widget=None,
        hideTitle: bool = False,
        autoOrientation: bool = True,
        label: DockLabel | None = None,
        **kargs,
    ) -> None: ...
    @overload
    def implements(self, name: None = None) -> list[str]: ...
    @overload
    def implements(self, name: str) -> bool: ...
    def setStretch(self, x: float | None = None, y: float | None = None) -> None: ...
    def stretch(self) -> tuple[float, float]: ...
    def hideTitleBar(self) -> None: ...
    def showTitleBar(self) -> None: ...
    def title(self) -> str: ...
    def setTitle(self, text: str) -> None: ...
    def setOrientation(self, o: Literal["auto", "vertical", "horizontal"] = "auto", force: bool = False) -> None: ...
    def updateStyle(self) -> None: ...
    def resizeEvent(self, ev) -> None: ...
    def name(self) -> str: ...
    def addWidget(self, widget, row: int | None = None, col: int = 0, rowspan: int = 1, colspan: int = 1) -> None: ...
    drag: Incomplete
    def startDrag(self) -> None: ...
    def float(self) -> None: ...
    def container(self) -> Container | None: ...
    def containerChanged(self, c: Container | None) -> None: ...
    def raiseDock(self) -> None: ...
    def close(self) -> None: ...
    def dragEnterEvent(self, *args) -> None: ...
    def dragMoveEvent(self, *args) -> None: ...
    def dragLeaveEvent(self, *args) -> None: ...
    def dropEvent(self, *args) -> None: ...

class DockLabel(VerticalLabel):
    sigClicked: Incomplete
    sigCloseClicked: Incomplete
    dim: bool
    fixedWidth: bool
    # A CSS font size, e.g. "12px".
    fontSize: str
    dock: Dock | None
    mouseMoved: bool
    closeButton: Incomplete
    def __init__(self, text: str, closable: bool = False, fontSize: str = "12px") -> None: ...
    vStyle: str
    hStyle: str
    def updateStyle(self) -> None: ...
    def setDim(self, d: bool) -> None: ...
    def setOrientation(self, o: _Orientation) -> None: ...
    def isClosable(self) -> bool: ...
    pressPos: Incomplete
    def mousePressEvent(self, ev) -> None: ...
    def mouseMoveEvent(self, ev) -> None: ...
    def mouseReleaseEvent(self, ev) -> None: ...
    def mouseDoubleClickEvent(self, ev) -> None: ...
    def resizeEvent(self, ev) -> None: ...
