# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing import Any, Literal, TypedDict
from typing_extensions import TypeAlias
from weakref import WeakValueDictionary

from ..Qt import QtWidgets
from .Container import Container, _InsertPos, _SplitContainerState, _TabContainerState
from .Dock import Dock

# Where a new Dock goes relative to `relativeTo`.
_Position: TypeAlias = Literal["bottom", "top", "left", "right", "above", "below"]

# A single Dock, identified by its name; the trailing dict is always empty.
_DockChildState: TypeAlias = tuple[Literal["dock"], str, dict[str, Any]]
# A container, its children, and the container's own `saveState()`.
_ContainerChildState: TypeAlias = tuple[
    Literal["vertical", "horizontal", "tab"], list[_ChildState], _SplitContainerState | _TabContainerState
]
_ChildState: TypeAlias = _DockChildState | _ContainerChildState

class _AreaState(TypedDict):
    main: _ChildState | None
    # Each entry pairs a floating area's own state with its (x, y, w, h) geometry.
    float: list[tuple[_AreaState, tuple[int, int, int, int]]]

class DockArea(Container, QtWidgets.QWidget):
    dockdrop: Incomplete
    layout: Incomplete
    docks: WeakValueDictionary[str, Dock]
    topContainer: Container | None
    temporary: bool
    tempAreas: list[DockArea]
    home: DockArea | None
    def __init__(self, parent=None, temporary: bool = False, home: DockArea | None = None) -> None: ...
    def type(self) -> Literal["top"]: ...
    # Extra keyword arguments are passed to `Dock()` when `dock` is None.
    def addDock(
        self, dock: Dock | None = None, position: _Position = "bottom", relativeTo: Dock | str | None = None, **kwds
    ) -> Dock: ...
    def moveDock(self, dock: Dock, position: _Position, neighbor: Dock | Container | None) -> None: ...
    def getContainer(self, obj: Dock | Container | None) -> Container | None: ...
    def makeContainer(self, typ: Literal["vertical", "horizontal", "tab"]) -> Container: ...
    def addContainer(self, typ: Literal["vertical", "horizontal", "tab"], obj: Dock | Container | None) -> Container: ...
    def insert(self, new: Dock | Container | list[Dock | Container], pos: _InsertPos | None = None, neighbor=None) -> None: ...
    def count(self) -> int: ...
    def resizeEvent(self, ev) -> None: ...
    def addTempArea(self) -> DockArea: ...
    def floatDock(self, dock: Dock) -> None: ...
    def removeTempArea(self, area: DockArea) -> None: ...
    def saveState(self) -> _AreaState: ...
    def childState(self, obj: Dock | Container) -> _ChildState: ...
    def restoreState(
        self,
        state: _AreaState,
        missing: Literal["error", "create", "ignore"] = "error",
        extra: Literal["bottom", "top", "left", "right", "above", "below", "float"] = "bottom",
    ) -> None: ...
    def buildFromState(
        self,
        state: _ChildState,
        docks: dict[str, Dock],
        root: Container,
        depth: int = 0,
        missing: Literal["error", "create", "ignore"] = "error",
    ) -> None: ...
    def findAll(
        self, obj: Dock | Container | None = None, c: list[Container] | None = None, d: dict[str, Dock] | None = None
    ) -> tuple[list[Container], dict[str, Dock]]: ...
    def apoptose(self, propagate: bool = True) -> None: ...
    def clear(self) -> None: ...
    def dragEnterEvent(self, *args) -> None: ...
    def dragMoveEvent(self, *args) -> None: ...
    def dragLeaveEvent(self, *args) -> None: ...
    def dropEvent(self, *args) -> None: ...
    def printState(self, state: _AreaState | None = None, name: str = "Main") -> None: ...

class TempAreaWindow(QtWidgets.QWidget):
    layout: Incomplete
    dockarea: DockArea
    def __init__(self, area: DockArea, **kwargs) -> None: ...
    def closeEvent(self, *args) -> None: ...
