# Populated at import time from the active binding's shiboken/sip helpers.
def wrapinstance(ptr: int, base=None): ...
def unwrapinstance(obj) -> int: ...
def __getattr__(name: str): ...  # incomplete module
