# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

import jupyter_rfb  # type: ignore[import-not-found]  # pyright: ignore[reportMissingImports]

__all__ = ["GraphicsLayoutWidget", "PlotWidget"]

class GraphicsView(jupyter_rfb.RemoteFrameBuffer):
    gfxView: Incomplete
    logical_size: Incomplete
    pixel_ratio: float
    def __init__(self, **kwds) -> None: ...
    def get_frame(self): ...
    def handle_event(self, event) -> None: ...

class GraphicsLayoutWidget(GraphicsView):
    gfxLayout: Incomplete
    def __init__(self, **kwds) -> None: ...
    def addPlot(self, *args, **kwds): ...
    def addViewBox(self, *args, **kwds): ...

class PlotWidget(GraphicsView):
    plotItem: Incomplete
    def __init__(self, **kwds) -> None: ...
    def getPlotItem(self): ...
    def __getattr__(self, attr): ...
