# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

import weakref
from _typeshed import Incomplete
from collections.abc import Iterable

from ...Qt import QtWidgets
from ...WidgetGroup import WidgetGroup
from .ViewBox import ViewBox

translate: Incomplete

class ViewBoxMenu(QtWidgets.QMenu):
    view: Incomplete  # weakref.ref[ViewBox]
    # False while the menu widgets are out of date with respect to the view.
    valid: bool
    viewMap: weakref.WeakValueDictionary[str, ViewBox]
    viewAll: Incomplete
    # One `Ui_Form` instance per axis, X then Y.
    ctrl: list[Incomplete]
    widgetGroups: list[WidgetGroup]
    dv: Incomplete
    # The "3 button" and "1 button" mouse-mode actions.
    mouseModes: list[Incomplete]
    def __init__(self, view: ViewBox) -> None: ...
    def viewStateChanged(self) -> None: ...
    def updateState(self) -> None: ...
    def popup(self, *args) -> None: ...
    def autoRange(self) -> None: ...
    def xMouseToggled(self, b: bool) -> None: ...
    def xManualClicked(self) -> None: ...
    def xRangeTextChanged(self) -> None: ...
    def xAutoClicked(self) -> None: ...
    def xAutoSpinChanged(self, val: float) -> None: ...
    def xLinkComboChanged(self, ind: int) -> None: ...
    def xAutoPanToggled(self, b: bool) -> None: ...
    def xVisibleOnlyToggled(self, b: bool) -> None: ...
    def yMouseToggled(self, b: bool) -> None: ...
    def yManualClicked(self) -> None: ...
    def yRangeTextChanged(self) -> None: ...
    def yAutoClicked(self) -> None: ...
    def yAutoSpinChanged(self, val: float) -> None: ...
    def yLinkComboChanged(self, ind: int) -> None: ...
    def yAutoPanToggled(self, b: bool) -> None: ...
    def yVisibleOnlyToggled(self, b: bool) -> None: ...
    def yInvertToggled(self, b: bool) -> None: ...
    def xInvertToggled(self, b: bool) -> None: ...
    def setMouseMode(self, action) -> None: ...
    def setViewList(self, views: Iterable[ViewBox]) -> None: ...
