from _typeshed import Incomplete
from collections.abc import Iterator, Sequence
from typing import Any, ClassVar, Literal
from typing_extensions import TypeAlias
from weakref import WeakKeyDictionary, WeakValueDictionary

from ...functions import _ColorArg, _PenArg
from ..GraphicsWidget import GraphicsWidget
from ..ItemGroup import ItemGroup

__all__ = ["ViewBox"]

# `ViewBox.XAxis`, `YAxis` or `XYAxes`.
_Axis: TypeAlias = Literal[0, 1, 2]
# A (min, max) pair per axis.
_Range: TypeAlias = Sequence[float]

class WeakList:
    def __init__(self) -> None: ...
    def append(self, obj: object) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...

class ChildGroup(ItemGroup):
    itemsChangedListeners: Incomplete
    def __init__(self, parent) -> None: ...
    def itemChange(self, change, value): ...

class ViewBox(GraphicsWidget):
    sigYRangeChanged: Incomplete
    sigXRangeChanged: Incomplete
    sigRangeChangedManually: Incomplete
    sigRangeChanged: Incomplete
    sigStateChanged: Incomplete
    sigTransformChanged: Incomplete
    sigResized: Incomplete
    PanMode: ClassVar[Literal[3]]
    RectMode: ClassVar[Literal[1]]
    XAxis: ClassVar[Literal[0]]
    YAxis: ClassVar[Literal[1]]
    XYAxes: ClassVar[Literal[2]]
    NamedViews: ClassVar[WeakValueDictionary[str, ViewBox]]
    AllViews: ClassVar[WeakKeyDictionary[ViewBox, None]]
    name: str | None
    linksBlocked: bool
    addedItems: list[Incomplete]
    state: dict[str, Incomplete]
    locateGroup: Incomplete
    childGroup: Incomplete
    background: Incomplete
    border: Incomplete
    borderRect: Incomplete
    target: Incomplete
    axHistory: Incomplete
    axHistoryPointer: int
    menu: Incomplete
    def __init__(
        self,
        parent=None,
        border: _PenArg = None,
        lockAspect: bool = False,
        enableMouse: bool = True,
        invertY: bool = False,
        enableMenu: bool = True,
        name: str | None = None,
        invertX: bool = False,
        defaultPadding: float = 0.02,
    ) -> None: ...
    @property
    def rbScaleBox(self): ...
    @rbScaleBox.setter
    def rbScaleBox(self, scaleBox) -> None: ...
    def getAspectRatio(self) -> float: ...
    def register(self, name: str) -> None: ...
    def unregister(self) -> None: ...
    def close(self) -> None: ...
    def implements(self, interface: str) -> bool: ...
    def itemChange(self, change, value): ...
    def prepareForPaint(self) -> None: ...
    def getState(self, copy: bool = True) -> dict[str, Incomplete]: ...
    def setState(self, state: dict[str, Incomplete]) -> None: ...
    def setBackgroundColor(self, color: _ColorArg) -> None: ...
    def setMouseMode(self, mode: Literal[1, 3]) -> None: ...
    def setLeftButtonAction(self, mode: Literal["rect", "pan"] = "rect") -> None: ...
    def innerSceneItem(self): ...
    def setMouseEnabled(self, x: bool | None = None, y: bool | None = None) -> None: ...
    def mouseEnabled(self) -> list[bool]: ...
    def setMenuEnabled(self, enableMenu: bool = True) -> None: ...
    def menuEnabled(self) -> bool: ...
    def addItem(self, item, ignoreBounds: bool = False) -> None: ...
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
    def resizeEvent(self, ev) -> None: ...
    def boundingRect(self): ...
    def viewRange(self) -> list[list[float]]: ...
    def viewRect(self): ...
    def targetRange(self) -> list[list[float]]: ...
    def targetRect(self): ...
    def setRange(
        self,
        rect=None,
        xRange: _Range | None = None,
        yRange: _Range | None = None,
        padding: float | None = None,
        update: bool = True,
        disableAutoRange: bool = True,
    ) -> None: ...
    def setYRange(self, min: float, max: float, padding: float | None = None, update: bool = True) -> None: ...
    def setXRange(self, min: float, max: float, padding: float | None = None, update: bool = True) -> None: ...
    def autoRange(self, padding: float | None = None, items: Sequence[Incomplete] | None = None, item=None) -> None: ...
    def suggestPadding(self, axis: _Axis) -> float: ...
    def setLimits(self, **kwds) -> None: ...
    def scaleBy(self, s=None, center=None, x: float | None = None, y: float | None = None) -> None: ...
    def translateBy(self, t=None, x: float | None = None, y: float | None = None) -> None: ...
    def enableAutoRange(
        self,
        axis: _Axis | str | None = None,
        enable: bool | float = True,
        x: bool | float | None = None,
        y: bool | float | None = None,
    ) -> None: ...
    def disableAutoRange(self, axis: _Axis | str | None = None) -> None: ...
    def autoRangeEnabled(self) -> list[bool | float]: ...
    def setAutoPan(self, x: bool | None = None, y: bool | None = None) -> None: ...
    def setAutoVisible(self, x: bool | None = None, y: bool | None = None) -> None: ...
    def updateAutoRange(self) -> None: ...
    def setXLink(self, view: ViewBox | str | None) -> None: ...
    def setYLink(self, view: ViewBox | str | None) -> None: ...
    def setLogMode(self, axis: Literal["x", "y"], logMode: bool) -> None: ...
    def linkView(self, axis: _Axis, view: ViewBox | str | None) -> None: ...
    def blockLink(self, b: bool) -> None: ...
    def linkedXChanged(self) -> None: ...
    def linkedYChanged(self) -> None: ...
    def linkedView(self, ax: _Axis) -> ViewBox | None: ...
    def linkedViewChanged(self, view: ViewBox | None, axis: _Axis) -> None: ...
    def screenGeometry(self): ...
    def itemsChanged(self) -> None: ...
    def itemBoundsChanged(self, item) -> None: ...
    def invertY(self, b: bool = True) -> None: ...
    def yInverted(self) -> bool: ...
    def invertX(self, b: bool = True) -> None: ...
    def xInverted(self) -> bool: ...
    def setBorder(self, *args: _PenArg, **kwds) -> None: ...
    def setDefaultPadding(self, padding: float = 0.02) -> None: ...
    def setAspectLocked(self, lock: bool = True, ratio: float | None = 1) -> None: ...
    def childTransform(self): ...
    def mapToView(self, obj): ...
    def mapFromView(self, obj): ...
    def mapSceneToView(self, obj): ...
    def mapViewToScene(self, obj): ...
    def mapFromItemToView(self, item, obj): ...
    def mapFromViewToItem(self, item, obj): ...
    def mapViewToDevice(self, obj): ...
    def mapDeviceToView(self, obj): ...
    def viewPixelSize(self) -> tuple[float, float]: ...
    def itemBoundingRect(self, item): ...
    def wheelEvent(self, ev, axis: Literal[0, 1] | None = None) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def raiseContextMenu(self, ev) -> None: ...
    def getMenu(self, ev): ...
    def getContextMenus(self, event): ...
    def mouseDragEvent(self, ev, axis: Literal[0, 1] | None = None) -> None: ...
    def keyPressEvent(self, ev) -> None: ...
    # Steps `d` entries through the zoom history; 0 resets it.
    def scaleHistory(self, d: int) -> None: ...
    def updateScaleBox(self, p1, p2) -> None: ...
    def showAxRect(self, ax, **kwargs) -> None: ...
    def allChildren(self, item=None) -> list[Incomplete]: ...
    # `[[xmin, xmax], [ymin, ymax]]`; an entry is None if that axis has no bounds.
    def childrenBounds(
        self,
        frac: Sequence[float] | None = None,
        orthoRange: Sequence[_Range | None] = (None, None),
        items: Sequence[Incomplete] | None = None,
    ) -> list[list[float] | None]: ...
    def childrenBoundingRect(self, *args, **kwds): ...
    def updateViewRange(self, forceX: bool = False, forceY: bool = False) -> None: ...
    def updateMatrix(self, changed=None) -> None: ...
    def paint(self, p, opt, widget) -> None: ...
    def updateBackground(self) -> None: ...
    def updateViewLists(self) -> None: ...
    @staticmethod
    def updateAllViewLists() -> None: ...
    @staticmethod
    def forgetView(vid: int, name: str | None) -> None: ...
    @staticmethod
    def quit() -> None: ...
    def locate(self, item, timeout: float = 3.0, children: bool = False) -> None: ...
    def clearLocate(self) -> None: ...
