# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtWidgets  # type: ignore[import-not-found]  # pyright: ignore[reportMissingImports]

__all__ = ["ArrowItem"]

class ArrowItem(QtWidgets.QGraphicsPathItem):
    opts: Incomplete
    def __init__(self, parent=None, **opts) -> None: ...
    path: Incomplete
    def setStyle(self, **opts) -> None: ...
    def paint(self, p, *args) -> None: ...
    def shape(self): ...
    def dataBounds(self, ax, frac, orthoRange=None): ...
    def pixelPadding(self): ...
