from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Literal

from ..functions import _PenArg
from .GraphicsWidget import GraphicsWidget
from .ViewBox.ViewBox import ViewBox

__all__ = ["AxisItem"]

class AxisItem(GraphicsWidget):
    label: Incomplete
    picture: Incomplete
    orientation: Literal["left", "right", "top", "bottom"]
    style: dict[str, Incomplete]
    textWidth: int
    textHeight: int
    fixedWidth: float | None
    fixedHeight: float | None
    labelText: str
    labelUnits: str
    labelUnitPrefix: str
    labelStyle: dict[str, Incomplete]
    logMode: bool
    # Declared `float` because that is the intended type; note `setScale(None)`
    # stores `None` unguarded, which then breaks `updateAutoSIPrefix`.
    scale: float
    autoSIPrefix: bool
    autoSIPrefixScale: float
    grid: bool
    def __init__(
        self,
        orientation: Literal["left", "right", "top", "bottom"],
        pen: _PenArg = None,
        textPen: _PenArg = None,
        tickPen: _PenArg = None,
        linkView: ViewBox | None = None,
        parent=None,
        maxTickLength: int = -5,
        showValues: bool = True,
        text: str = "",
        units: str = "",
        unitPrefix: str = "",
        **args,
    ) -> None: ...
    # Accepts the keys of `style`: tickLength, tickTextOffset, tickTextWidth, tickTextHeight,
    # autoExpandTextSpace, autoReduceTextSpace, hideOverlappingLabels, tickFont, stopAxisAtTick,
    # textFillLimits, showValues, maxTickLevel, maxTextLevel and tickAlpha. Any other key raises
    # `NameError`.
    def setStyle(self, **kwds) -> None: ...
    def close(self) -> None: ...
    def setGrid(self, grid: bool | int) -> None: ...
    # One positional argument sets the log mode of this axis' own direction; two set the
    # x and y modes, which may also be given as the `x` and `y` keyword arguments.
    def setLogMode(self, *args: bool | None, **kwargs: bool | None) -> None: ...
    def setTickFont(self, font) -> None: ...
    def resizeEvent(self, ev=None) -> None: ...
    def showLabel(self, show: bool = True) -> None: ...
    def setLabel(self, text: str | None = None, units: str | None = None, unitPrefix: str | None = None, **args) -> None: ...
    def labelString(self) -> str: ...
    def setHeight(self, h: float | None = None) -> None: ...
    def setWidth(self, w: float | None = None) -> None: ...
    def pen(self): ...
    def setPen(self, *args: _PenArg, **kwargs) -> None: ...
    def textPen(self): ...
    def setTextPen(self, *args: _PenArg, **kwargs) -> None: ...
    def tickPen(self): ...
    def setTickPen(self, *args: _PenArg, **kwargs) -> None: ...
    def setScale(self, scale: float | None = None) -> None: ...
    def enableAutoSIPrefix(self, enable: bool = True) -> None: ...
    def updateAutoSIPrefix(self) -> None: ...
    range: list[float]
    def setRange(self, mn: float, mx: float) -> None: ...
    def linkedView(self) -> ViewBox | None: ...
    def linkToView(self, view: ViewBox) -> None: ...
    def unlinkFromView(self) -> None: ...
    # `newRange` defaults to the linked view's range along this axis' direction.
    def linkedViewChanged(self, view: ViewBox, newRange: Sequence[float] | None = None) -> None: ...
    def boundingRect(self): ...
    def paint(self, p, opt, widget) -> None: ...
    def setTickDensity(self, density: float = 1.0) -> None: ...
    # A list of tick levels, each a list of `(value, label)` pairs; `None`
    # restores automatic tick generation.
    def setTicks(self, ticks: Sequence[Sequence[tuple[float, str]]] | None) -> None: ...
    def setTickSpacing(
        self, major: float | None = None, minor: float | None = None, levels: Sequence[tuple[float, float]] | None = None
    ) -> None: ...
    def tickSpacing(self, minVal: float, maxVal: float, size: float) -> list[tuple[float, float]]: ...
    def tickValues(self, minVal: float, maxVal: float, size: float) -> list[tuple[float, Sequence[float]]]: ...
    def logTickValues(
        self, minVal: float, maxVal: float, size: float, stdTicks: Sequence[tuple[float, Sequence[float]]]
    ) -> list[tuple[float | None, Sequence[float]]]: ...
    def tickStrings(self, values: Sequence[float], scale: float, spacing: float) -> list[str]: ...
    def logTickStrings(self, values: Sequence[float], scale: float, spacing: float) -> list[str]: ...
    # `(axisSpec, tickSpecs, textSpecs)` ready to be passed to `drawPicture`, or `None` if
    # there is nothing to draw. `axisSpec` is `(pen, start, stop)`, `tickSpecs` a list of
    # `(pen, start, stop)` and `textSpecs` a list of `(rect, flags, text)`.
    def generateDrawSpecs(self, p): ...
    def drawPicture(self, p, axisSpec, tickSpecs, textSpecs) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def wheelEvent(self, event) -> None: ...
    # Forwarded to the linked view with this axis' direction; a no-op if there is no linked view.
    def mouseDragEvent(self, event) -> None: ...
    def mouseClickEvent(self, event) -> None: ...
