from _typeshed import Incomplete
from collections.abc import Sequence
from typing import overload

from .GraphicsObject import GraphicsObject

__all__ = ["BarGraphItem"]

class BarGraphItem(GraphicsObject):
    opts: dict[str, Incomplete]
    picture: Incomplete
    # Accepts x, x0, x1, y, y0, y1, width, height, pen, brush, pens, brushes,
    # and name.
    def __init__(self, **opts) -> None: ...
    def setOpts(self, **opts) -> None: ...
    def drawPicture(self) -> None: ...
    def paint(self, p, *args) -> None: ...
    def shape(self): ...
    @overload
    def implements(self, interface: str) -> bool: ...
    @overload
    def implements(self, interface: None = None) -> list[str]: ...
    def name(self) -> str | None: ...
    def getData(self) -> tuple[Incomplete, Incomplete]: ...
    def dataBounds(
        self, ax: int, frac: float = 1.0, orthoRange: Sequence[float] | None = None
    ) -> tuple[float | None, float | None]: ...
    def pixelPadding(self) -> float: ...
    def boundingRect(self): ...
