from _typeshed import Incomplete

from .GraphicsObject import GraphicsObject
from .PlotCurveItem import PlotCurveItem

__all__ = ["CurvePoint", "CurveArrow"]

class CurvePoint(GraphicsObject):
    curve: Incomplete  # weakref.ref[PlotCurveItem]
    def __init__(self, curve: PlotCurveItem, index: int = 0, pos: float | None = None, rotate: bool = True) -> None: ...
    # `pos` is a fraction of the curve length, not a coordinate pair.
    def setPos(self, pos: float) -> None: ...
    def setIndex(self, index: int) -> None: ...
    def event(self, ev) -> bool: ...
    def boundingRect(self): ...
    def paint(self, *args) -> None: ...
    def makeAnimation(
        self, prop: str | bytes = "position", start: float = 0.0, end: float = 1.0, duration: int = 10000, loop: int = 1
    ): ...

class CurveArrow(CurvePoint):
    arrow: Incomplete
    # Accepts any keyword accepted by `ArrowItem.setStyle`.
    def __init__(self, curve: PlotCurveItem, index: int = 0, pos: float | None = None, **opts) -> None: ...
    def setStyle(self, **opts) -> None: ...
