from _typeshed import Incomplete

from .GraphicsObject import GraphicsObject

__all__ = ["ErrorBarItem"]

class ErrorBarItem(GraphicsObject):
    opts: dict[str, Incomplete]
    # Accepts x, y, height, width, top, bottom, left, right, beam, pen.
    def __init__(self, **opts) -> None: ...
    path: Incomplete
    def setData(self, **opts) -> None: ...
    def setOpts(self, **opts) -> None: ...
    def drawPath(self) -> None: ...
    def paint(self, p, *args) -> None: ...
    def boundingRect(self): ...
