# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Callable, Sequence
from typing import Any, Literal, TypeVar
from typing_extensions import TypeAlias

import numpy as np
from numpy.typing import NDArray

from ..colormap import ColorMap
from ..functions import _ColorArg, _PenArg
from ..Qt import QtWidgets
from .GradientPresets import _GradientPreset
from .GraphicsWidget import GraphicsWidget

__all__ = ["TickSliderItem", "GradientEditorItem", "addGradientListToDocstring"]

_F = TypeVar("_F", bound=Callable[..., Any])
_Orientation: TypeAlias = Literal["left", "right", "top", "bottom"]

# Same keys as a `GradientPresets` entry, plus the optional visibility flag
# that `saveState` adds.
class _GradientState(_GradientPreset, total=False):
    ticksVisible: bool

def addGradientListToDocstring() -> Callable[[_F], _F]: ...

class TickSliderItem(GraphicsWidget):
    sigTicksChanged: Incomplete
    sigTicksChangeFinished: Incomplete
    orientation: _Orientation
    length: float
    tickSize: int
    ticks: dict[Tick, float]
    maxDim: float
    allowAdd: bool
    allowRemove: bool
    tickPen: Incomplete
    # orientation name -> (rotation, x scale, y scale)
    orientations: dict[_Orientation, tuple[float, float, float]]
    def __init__(
        self, orientation: _Orientation = "bottom", allowAdd: bool = True, allowRemove: bool = True, **kargs
    ) -> None: ...
    def paint(self, p, opt, widget) -> None: ...
    def keyPressEvent(self, ev) -> None: ...
    def setMaxDim(self, mx: float | None = None) -> None: ...
    def setOrientation(self, orientation: _Orientation) -> None: ...
    def addTick(self, x: float, color: _ColorArg | None = None, movable: bool = True, finish: bool = True) -> Tick: ...
    def removeTick(self, tick: Tick, finish: bool = True) -> None: ...
    def tickMoved(self, tick: Tick, pos) -> None: ...
    def tickMoveFinished(self, tick: Tick) -> None: ...
    def tickClicked(self, tick: Tick, ev) -> None: ...
    def widgetLength(self) -> float: ...
    def resizeEvent(self, ev) -> None: ...
    def setLength(self, newLen: float) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def showMenu(self, ev) -> None: ...
    def setTickColor(self, tick: Tick | int, color: _ColorArg) -> None: ...
    def setTickValue(self, tick: Tick | int, val: float) -> None: ...
    def tickValue(self, tick: Tick | int) -> float: ...
    def getTick(self, tick: Tick | int) -> Tick: ...
    def listTicks(self) -> list[tuple[Tick, float]]: ...

class GradientEditorItem(TickSliderItem):
    sigGradientChanged: Incomplete
    sigGradientChangeFinished: Incomplete
    currentTick: Tick | None
    currentTickColor: Incomplete
    rectSize: int
    gradRect: Incomplete
    backgroundRect: Incomplete
    colorMode: Literal["rgb", "hsv"]
    colorDialog: Incomplete
    rgbAction: Incomplete
    hsvAction: Incomplete
    menu: Incomplete
    linkedGradients: dict[int, Callable[[GradientEditorItem], None]]
    def __init__(self, *args, **kargs) -> None: ...
    def showTicks(self, show: bool = True) -> None: ...
    def setOrientation(self, orientation: _Orientation) -> None: ...
    def showMenu(self, ev) -> None: ...
    def colorMapMenuClicked(self, cmap: ColorMap) -> None: ...
    def loadPreset(self, name: str) -> None: ...
    def setColorMode(self, cm: Literal["rgb", "hsv"]) -> None: ...
    def colorMap(self) -> ColorMap: ...
    gradient: Incomplete
    def updateGradient(self) -> None: ...
    def setLength(self, newLen: float) -> None: ...
    def currentColorChanged(self, color) -> None: ...
    def currentColorRejected(self) -> None: ...
    def currentColorAccepted(self) -> None: ...
    def tickClicked(self, tick: Tick, ev) -> None: ...
    def raiseColorDialog(self, tick: Tick) -> None: ...
    tickMenu: TickMenu
    def raiseTickContextMenu(self, tick: Tick, ev) -> None: ...
    def tickMoveFinished(self, tick: Tick) -> None: ...
    def getGradient(self): ...
    # A `QColor`, or an `(r, g, b, a)` tuple when `toQColor` is False.
    def getColor(self, x: float, toQColor: bool = True): ...
    def getLookupTable(self, nPts: int, alpha: bool | None = None) -> NDArray[np.ubyte]: ...
    def usesAlpha(self) -> bool: ...
    def isLookupTrivial(self) -> bool: ...
    def addTick(self, x: float, color: _ColorArg | None = None, movable: bool = True, finish: bool = True) -> Tick: ...
    def saveState(self) -> _GradientState: ...
    def restoreState(self, state: _GradientState) -> None: ...
    def setColorMap(self, cm: ColorMap) -> None: ...
    def linkGradient(self, slaveGradient: GradientEditorItem, connect: bool = True) -> None: ...

class Tick(QtWidgets.QGraphicsWidget):
    sigMoving: Incomplete
    sigMoved: Incomplete
    sigClicked: Incomplete
    movable: bool
    moving: bool
    scale: Incomplete
    color: Incomplete
    pen: Incomplete
    hoverPen: Incomplete
    currentPen: Incomplete
    removeAllowed: bool
    pg: Incomplete
    def __init__(
        self,
        pos: Sequence[float],
        color: _ColorArg,
        movable: bool = True,
        scale: float = 10,
        pen: _PenArg = "w",
        removeAllowed: bool = True,
    ) -> None: ...
    def boundingRect(self): ...
    def shape(self): ...
    def paint(self, p, *args) -> None: ...
    cursorOffset: Incomplete
    startPosition: Incomplete
    def mouseDragEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...

class TickMenu(QtWidgets.QMenu):
    tick: Incomplete
    sliderItem: Incomplete
    removeAct: Incomplete
    fracPosSpin: Incomplete
    def __init__(self, tick: Tick, sliderItem: TickSliderItem) -> None: ...
    def fractionalValueChanged(self, x) -> None: ...
