from ..Point import _PointLike

__all__ = ["GraphicsWidgetAnchor"]

class GraphicsWidgetAnchor:
    def __init__(self) -> None: ...
    def anchor(self, itemPos: _PointLike, parentPos: _PointLike, offset: _PointLike = (0, 0)) -> None: ...
    def autoAnchor(self, pos: _PointLike, relative: bool = True) -> None: ...
