from _typeshed import Incomplete
from collections import OrderedDict
from collections.abc import Mapping
from typing import Any
from xml.etree.ElementTree import Element

from ..Point import Point
from ..widgets.GraphicsView import GraphicsView
from .ViewBox.ViewBox import ViewBox

__all__ = ["GraphicsItem"]

class LRU(OrderedDict[Incomplete, Incomplete]):
    maxsize: int
    def __init__(self, maxsize: int = 128, *args, **kwds) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...

class GraphicsItem:
    def __init__(self) -> None: ...
    def getViewWidget(self): ...
    def forgetViewWidget(self) -> None: ...
    # The innermost `ViewBox` containing this item, or the `GraphicsView` it is
    # displayed in if there is no `ViewBox`. `None` if the item has no view.
    def getViewBox(self) -> ViewBox | GraphicsView | None: ...
    def forgetViewBox(self) -> None: ...
    def deviceTransform(self, viewportTransform=None): ...
    def viewTransform(self): ...
    def getBoundingParents(self) -> list[Incomplete]: ...
    def viewRect(self): ...
    # `(None, None)` if the pixel size is not yet defined.
    def pixelVectors(self, direction=None) -> tuple[Point, Point] | tuple[None, None]: ...
    def pixelLength(self, direction, ortho: bool = False) -> float | None: ...
    def pixelSize(self) -> tuple[float, float] | tuple[None, None]: ...
    def pixelWidth(self) -> float: ...
    def pixelHeight(self) -> float: ...
    def mapToDevice(self, obj): ...
    def mapFromDevice(self, obj): ...
    def mapRectToDevice(self, rect): ...
    def mapRectFromDevice(self, rect): ...
    def mapToView(self, obj): ...
    def mapRectToView(self, obj): ...
    def mapFromView(self, obj): ...
    def mapRectFromView(self, obj): ...
    def pos(self) -> Point: ...
    def viewPos(self): ...
    def parentItem(self): ...
    def setParentItem(self, parent): ...
    def childItems(self) -> list[Incomplete]: ...
    def sceneTransform(self): ...
    def transformAngle(self, relativeItem=None) -> float: ...
    def changeParent(self) -> None: ...
    def parentChanged(self) -> None: ...
    def viewChanged(self, view, oldView) -> None: ...
    def viewRangeChanged(self) -> None: ...
    def viewTransformChanged(self) -> None: ...
    def informViewBoundsChanged(self) -> None: ...
    def childrenShape(self): ...
    def allChildItems(self, root=None) -> list[Incomplete]: ...
    def setExportMode(self, export: bool, opts: Mapping[str, Any] | None = None) -> None: ...
    def getContextMenus(self, event) -> list[Incomplete]: ...
    def generateSvg(self, nodes: dict[str, Element]) -> tuple[Element, list[Element]] | None: ...
