# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from ..Qt import QtWidgets
from .GraphicsItem import GraphicsItem

__all__ = ["GraphicsWidget"]

class GraphicsWidget(GraphicsItem, QtWidgets.QGraphicsWidget):
    def __init__(self, *args, **kwargs) -> None: ...
    def setFixedHeight(self, h: float) -> None: ...
    def setFixedWidth(self, h: float) -> None: ...
    def height(self) -> float: ...
    def width(self) -> float: ...
    def boundingRect(self): ...
    def shape(self): ...
