# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from ..Qt import QtWidgets  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]
from .GraphicsItem import GraphicsItem

__all__ = ["GraphicsWidget"]

class GraphicsWidget(GraphicsItem, QtWidgets.QGraphicsWidget):
    def __init__(self, *args, **kwargs) -> None: ...
    def setFixedHeight(self, h) -> None: ...
    def setFixedWidth(self, h) -> None: ...
    def height(self): ...
    def width(self): ...
    def boundingRect(self): ...
    def shape(self): ...
