from _typeshed import Incomplete

from ..functions import _PenArg
from .GraphicsWidget import GraphicsWidget
from .LabelItem import LabelItem
from .PlotItem import PlotItem
from .ViewBox import ViewBox

__all__ = ["GraphicsLayout"]

class GraphicsLayout(GraphicsWidget):
    border: Incomplete
    layout: Incomplete
    items: dict[Incomplete, list[tuple[int, int]]]
    rows: dict[int, dict[int, Incomplete]]
    itemBorders: Incomplete
    currentRow: int
    currentCol: int
    def __init__(self, parent=None, border: _PenArg | bool = None) -> None: ...
    def setBorder(self, *args: _PenArg, **kwds) -> None: ...
    def nextRow(self) -> None: ...
    def nextColumn(self) -> None: ...
    def nextCol(self, *args, **kargs) -> None: ...
    def addPlot(
        self, row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1, **kargs
    ) -> PlotItem: ...
    def addViewBox(
        self, row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1, **kargs
    ) -> ViewBox: ...
    def addLabel(
        self, text: str = " ", row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1, **kargs
    ) -> LabelItem: ...
    def addLayout(
        self, row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1, **kargs
    ) -> GraphicsLayout: ...
    def addItem(self, item, row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1) -> None: ...
    def getItem(self, row: int, col: int): ...
    def boundingRect(self): ...
    def itemIndex(self, item) -> int: ...
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
    def setContentsMargins(self, *args) -> None: ...
    def setSpacing(self, *args) -> None: ...
