from _typeshed import Incomplete
from collections.abc import Sequence

from ..functions import _PenArg
from .UIGraphicsItem import UIGraphicsItem

__all__ = ["GridItem"]

class GridItem(UIGraphicsItem):
    opts: dict[str, Incomplete]
    def __init__(self, pen: _PenArg = "default", textPen: _PenArg = "default") -> None: ...
    picture: Incomplete
    def setPen(self, *args: _PenArg, **kwargs) -> None: ...
    def setTextPen(self, *args: _PenArg, **kwargs) -> None: ...
    grid_depth: int
    # One entry per tick scale, in descending order; `None` picks the spacing
    # for that scale automatically.
    def setTickSpacing(self, x: Sequence[float | None] | None = None, y: Sequence[float | None] | None = None) -> None: ...
    def viewRangeChanged(self) -> None: ...
    def paint(self, p, opt, widget) -> None: ...
    def generatePicture(self) -> None: ...
