from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Literal

from numpy.typing import NDArray

from ..colormap import ColorMap
from ..functions import _PenArg
from .GraphicsObject import GraphicsObject

__all__ = ["ImageItem"]

class ImageItem(GraphicsObject):
    sigImageChanged: Incomplete
    sigRemoveRequested: Incomplete
    menu: Incomplete
    image: NDArray[Any] | None
    qimage: Incomplete
    paintMode: Incomplete
    levels: NDArray[Any] | None
    lut: NDArray[Any] | None
    autoDownsample: bool
    axisOrder: Literal["row-major", "col-major"]
    drawKernel: Incomplete
    border: Incomplete
    removable: bool
    def __init__(self, image: NDArray[Any] | None = None, **kargs) -> None: ...
    def setCompositionMode(self, mode) -> None: ...
    def setBorder(self, b: _PenArg) -> None: ...
    def width(self) -> int | None: ...
    def height(self) -> int | None: ...
    def channels(self) -> int | None: ...
    def boundingRect(self): ...
    def setLevels(self, levels: Sequence[float] | NDArray[Any] | None, update: bool = True) -> None: ...
    def getLevels(self) -> NDArray[Any] | None: ...
    def setColorMap(self, colorMap: ColorMap | str) -> None: ...
    def getColorMap(self) -> ColorMap | None: ...
    def setLookupTable(self, lut, update: bool = True) -> None: ...
    def setAutoDownsample(self, active: bool = True) -> None: ...
    def setOpts(self, update: bool = True, **kargs) -> None: ...
    def setRect(self, *args) -> None: ...
    def clear(self) -> None: ...
    def setImage(self, image: NDArray[Any] | None = None, autoLevels: bool | None = None, **kargs) -> None: ...
    def dataTransform(self): ...
    def inverseDataTransform(self): ...
    def mapToData(self, obj): ...
    def mapFromData(self, obj): ...
    def quickMinMax(self, targetSize: float = 1000000.0) -> tuple[float, float]: ...
    def updateImage(self, *args, **kargs): ...
    def render(self) -> None: ...
    def paint(self, p, *args) -> None: ...
    def save(self, fileName: str, *args) -> None: ...
    # `(None, None)` when there is no image; a list of per-channel pairs when
    # `perChannel=True`.
    def getHistogram(
        self,
        bins: int | str | NDArray[Any] = "auto",
        step: int | Literal["auto"] = "auto",
        perChannel: bool = False,
        targetImageSize: int = 200,
        targetHistogramSize: int = 500,
        **kwds,
    ): ...
    def setPxMode(self, b: bool) -> None: ...
    def setScaledMode(self) -> None: ...
    def getPixmap(self): ...
    def pixelSize(self) -> tuple[float, float]: ...
    def viewTransformChanged(self) -> None: ...
    def mouseDragEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def raiseContextMenu(self, ev) -> bool: ...
    def getMenu(self): ...
    def hoverEvent(self, ev) -> None: ...
    def tabletEvent(self, ev) -> None: ...
    def drawAt(self, pos, ev=None) -> None: ...
    drawKernelCenter: Incomplete
    drawMode: Incomplete
    drawMask: Incomplete
    def setDrawKernel(
        self,
        kernel: NDArray[Any] | None = None,
        mask: NDArray[Any] | None = None,
        center: Sequence[int] = (0, 0),
        mode: Literal["set", "add"] = "set",
    ) -> None: ...
    removeTimer: Incomplete
    def removeClicked(self) -> None: ...
    def emitRemoveRequested(self) -> None: ...
