from _typeshed import Incomplete
from collections.abc import Mapping, Sequence
from typing import Any

from ..functions import _PenArg
from ..Point import Point
from .GraphicsObject import GraphicsObject
from .TextItem import TextItem

__all__ = ["InfiniteLine", "InfLineLabel"]

class InfiniteLine(GraphicsObject):
    sigDragged: Incomplete
    sigPositionChangeFinished: Incomplete
    sigPositionChanged: Incomplete
    sigClicked: Incomplete
    maxRange: list[float | None]
    moving: bool
    mouseHovering: bool
    p: list[float]
    span: Sequence[float]
    currentPen: Incomplete
    markers: list[Incomplete]
    label: InfLineLabel | None
    def __init__(
        self,
        pos: float | Sequence[float] | Point | None = None,
        angle: float = 90,
        pen: _PenArg = None,
        movable: bool = False,
        bounds: Sequence[float | None] | None = None,
        hoverPen: _PenArg = None,
        label: str | None = None,
        labelOpts: Mapping[str, Any] | None = None,
        span: Sequence[float] = (0, 1),
        markers: Sequence[Incomplete] | None = None,
        name: str | None = None,
    ) -> None: ...
    movable: bool
    def setMovable(self, m: bool) -> None: ...
    def setBounds(self, bounds: Sequence[float | None] | None) -> None: ...
    def bounds(self) -> list[float | None]: ...
    pen: Incomplete
    def setPen(self, *args: _PenArg, **kwargs) -> None: ...
    hoverPen: Incomplete
    def setHoverPen(self, *args: _PenArg, **kwargs) -> None: ...
    def addMarker(self, marker: str, position: float = 0.5, size: float = 10.0) -> None: ...
    def clearMarkers(self) -> None: ...
    angle: float
    def setAngle(self, angle: float) -> None: ...
    def setPos(self, pos: float | Sequence[float] | Point) -> None: ...
    def getXPos(self) -> float: ...
    def getYPos(self) -> float: ...
    def getPos(self) -> list[float]: ...
    # A scalar for horizontal or vertical lines, `[x, y]` otherwise.
    def value(self): ...
    def setValue(self, v: float | Sequence[float] | Point) -> None: ...
    def setSpan(self, mn: float, mx: float) -> None: ...
    def boundingRect(self): ...
    def paint(self, p, *args) -> None: ...
    def dataBounds(self, axis: int, frac: float = 1.0, orthoRange: Sequence[float] | None = None): ...
    cursorOffset: Incomplete
    startPosition: Incomplete
    def mouseDragEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def setMouseHover(self, hover: bool) -> None: ...
    def viewTransformChanged(self) -> None: ...
    def setName(self, name: str) -> None: ...
    def name(self) -> str | None: ...

class InfLineLabel(TextItem):
    line: InfiniteLine
    movable: bool
    moving: bool
    orthoPos: float
    format: str
    anchors: Sequence[Sequence[float]] | None
    def __init__(
        self,
        line: InfiniteLine,
        text: str = "",
        movable: bool = False,
        position: float = 0.5,
        anchors: Sequence[Sequence[float]] | None = None,
        **kwds,
    ) -> None: ...
    def valueChanged(self) -> None: ...
    def getEndpoints(self) -> tuple[Point | None, Point | None]: ...
    def updatePosition(self) -> None: ...
    def setVisible(self, v: bool) -> None: ...
    def setMovable(self, m: bool) -> None: ...
    def setPosition(self, p: float) -> None: ...
    def setFormat(self, text: str) -> None: ...
    def mouseDragEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def viewTransformChanged(self) -> None: ...
