from _typeshed import Incomplete

from .GraphicsWidget import GraphicsWidget
from .GraphicsWidgetAnchor import GraphicsWidgetAnchor

__all__ = ["LabelItem"]

class LabelItem(GraphicsWidgetAnchor, GraphicsWidget):
    item: Incomplete
    opts: dict[str, Incomplete]
    # `args` are CSS style options: `color`, `justify`, `family`, `size`, `bold`, `italic`.
    def __init__(self, text: str = " ", parent=None, angle: float = 0, **args) -> None: ...
    def setAttr(self, attr: str, value) -> None: ...
    text: str
    def setText(self, text: str, **args) -> None: ...
    def resizeEvent(self, ev) -> None: ...
    angle: float
    def setAngle(self, angle: float) -> None: ...
    def updateMin(self) -> None: ...
    def sizeHint(self, hint, constraint): ...
    def itemRect(self): ...
