from _typeshed import Incomplete
from collections.abc import Sequence

from ..functions import _BrushArg, _PenArg
from .GraphicsWidget import GraphicsWidget
from .GraphicsWidgetAnchor import GraphicsWidgetAnchor

__all__ = ["LegendItem", "ItemSample"]

class LegendItem(GraphicsWidgetAnchor, GraphicsWidget):
    layout: Incomplete
    items: list[tuple[ItemSample, Incomplete]]
    size: Sequence[float] | None
    frame: Incomplete
    columnCount: int
    rowCount: int
    sampleType: type[ItemSample]
    opts: dict[str, Incomplete]
    def __init__(
        self,
        size: Sequence[float] | None = None,
        offset: Sequence[float] | None = None,
        horSpacing: int = 25,
        verSpacing: int = 0,
        pen: _PenArg = None,
        brush: _BrushArg = None,
        labelTextColor: _PenArg = None,
        frame: bool = True,
        labelTextSize: str = "9pt",
        colCount: int = 1,
        sampleType: type[ItemSample] | None = None,
        **kwargs,
    ) -> None: ...
    def setSampleType(self, sample: type[ItemSample]) -> None: ...
    def offset(self) -> Sequence[float] | None: ...
    def setOffset(self, offset: Sequence[float]) -> None: ...
    def pen(self): ...
    def setPen(self, *args: _PenArg, **kargs) -> None: ...
    def brush(self): ...
    def setBrush(self, *args: _BrushArg, **kargs) -> None: ...
    def labelTextColor(self): ...
    def setLabelTextColor(self, *args: _PenArg, **kargs) -> None: ...
    def labelTextSize(self) -> str: ...
    def setLabelTextSize(self, size: str) -> None: ...
    def setParentItem(self, p): ...
    def addItem(self, item, name: str) -> None: ...
    def setColumnCount(self, columnCount: int) -> None: ...
    def getLabel(self, plotItem): ...
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
    def updateSize(self) -> None: ...
    def boundingRect(self): ...
    def paint(self, p, *args) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def mouseDragEvent(self, ev) -> None: ...

class ItemSample(GraphicsWidget):
    item: Incomplete
    def __init__(self, item) -> None: ...
    def boundingRect(self): ...
    def paint(self, p, *args) -> None: ...
    def mouseClickEvent(self, event) -> None: ...
