from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any

from numpy.typing import NDArray

from ..colormap import ColorMap
from .GraphicsObject import GraphicsObject

__all__ = ["PColorMeshItem"]

class QuadInstances:
    nrows: int
    ncols: int
    pointsarray: Incomplete
    def __init__(self) -> None: ...
    polys: list[Incomplete]
    def resize(self, nrows: int, ncols: int) -> None: ...
    def ndarray(self) -> NDArray[Any]: ...
    def instances(self) -> list[Incomplete]: ...

class PColorMeshItem(GraphicsObject):
    sigLevelsChanged: Incomplete
    qpicture: Incomplete
    # `x` and `y` shadow `QGraphicsItem.x`/`QGraphicsItem.y`; both are
    # `NDArray[Any] | None` on an instance, as is `z`.
    x: Incomplete
    y: Incomplete
    z: NDArray[Any] | None
    edgecolors: Incomplete
    antialiasing: bool
    levels: tuple[float, float] | None
    cmap: ColorMap | None
    lut_qcolor: Sequence[Incomplete]
    quads: QuadInstances
    # Call signature is `PColorMeshItem([x, y,] z, **kwargs)`; `kwargs` accepts
    # `colorMap`, `levels`, `enableAutoLevels`, `edgecolors` and `antialiasing`.
    def __init__(self, *args, **kwargs) -> None: ...
    # `setData([x, y,] z, autoLevels=...)`.
    def setData(self, *args, **kwargs) -> None: ...
    def setLevels(self, levels: tuple[float, float], update: bool = True) -> None: ...
    def getLevels(self) -> tuple[float, float] | None: ...
    def setLookupTable(self, lut: Sequence[Incomplete], update: bool = True) -> None: ...
    def getColorMap(self) -> ColorMap | None: ...
    def setColorMap(self, cmap: ColorMap) -> None: ...
    def enableAutoLevels(self) -> None: ...
    def disableAutoLevels(self) -> None: ...
    def paint(self, p, *args) -> None: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def dataBounds(
        self, ax: int, frac: float = 1.0, orthoRange: Sequence[float] | None = None
    ) -> tuple[float, float] | tuple[None, None]: ...
    def pixelPadding(self) -> float: ...
    def boundingRect(self): ...
