from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Literal, overload

from numpy.typing import NDArray

from .. import debug
from ..functions import _BrushArg, _PenArg
from .GraphicsObject import GraphicsObject

__all__ = ["PlotCurveItem"]

class PlotCurveItem(GraphicsObject):
    sigPlotChanged: Incomplete
    sigClicked: Incomplete
    metaData: dict[str, Incomplete]
    opts: dict[str, Incomplete]
    def __init__(self, *args, **kargs) -> None: ...
    @overload
    def implements(self, interface: str) -> bool: ...
    @overload
    def implements(self, interface: None = None) -> list[str]: ...
    def name(self) -> str | None: ...
    clickable: bool
    def setClickable(self, s: bool, width: int | None = None) -> None: ...
    def setCompositionMode(self, mode) -> None: ...
    def getData(self) -> tuple[NDArray[Any] | None, NDArray[Any] | None]: ...
    def dataBounds(self, ax: int, frac: float = 1.0, orthoRange: Sequence[float] | None = None) -> Sequence[float | None]: ...
    def pixelPadding(self) -> float: ...
    def boundingRect(self): ...
    def viewTransformChanged(self) -> None: ...
    def invalidateBounds(self) -> None: ...
    def setPen(self, *args: _PenArg, **kargs) -> None: ...
    def setShadowPen(self, *args: _PenArg, **kargs) -> None: ...
    def setBrush(self, *args: _BrushArg, **kargs) -> None: ...
    fillPath: Incomplete
    def setFillLevel(self, level: float | None) -> None: ...
    def setSkipFiniteCheck(self, skipFiniteCheck: bool) -> None: ...
    def setData(self, *args, **kargs) -> None: ...
    yData: NDArray[Any] | None
    xData: NDArray[Any] | None
    path: Incomplete
    def updateData(self, *args, **kargs) -> None: ...
    def generatePath(self, x: NDArray[Any], y: NDArray[Any]): ...
    def getPath(self): ...
    def setSegmentedLineMode(self, mode: Literal["auto", "on", "off"]) -> None: ...
    @debug.warnOnException
    def paint(self, p, opt, widget) -> None: ...
    def paintGL(self, p, opt, widget) -> None: ...
    def clear(self) -> None: ...
    def mouseShape(self): ...
    def mouseClickEvent(self, ev) -> None: ...

class ROIPlotItem(PlotCurveItem):
    roi: Incomplete
    roiData: Incomplete
    roiImg: Incomplete
    axes: tuple[int, int]
    xVals: NDArray[Any] | None
    def __init__(self, roi, data, img, axes: tuple[int, int] = (0, 1), xVals=None, color=None) -> None: ...
    def getRoiData(self) -> NDArray[Any] | None: ...
    def roiChangedEvent(self) -> None: ...
