from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Literal, overload

from numpy.typing import NDArray

from ..functions import _BrushArg, _PenArg
from .GraphicsObject import GraphicsObject

__all__ = ["PlotDataItem"]

class PlotDataset:
    x: NDArray[Any] | None
    y: NDArray[Any] | None
    xAllFinite: bool | None
    yAllFinite: bool | None
    def __init__(
        self, x: NDArray[Any] | None, y: NDArray[Any] | None, xAllFinite: bool | None = None, yAllFinite: bool | None = None
    ) -> None: ...
    @property
    def containsNonfinite(self) -> bool | None: ...
    def dataRect(self): ...
    def applyLogMapping(self, logMode: tuple[bool, bool]) -> None: ...

class PlotDataItem(GraphicsObject):
    sigPlotChanged: Incomplete
    sigClicked: Incomplete
    sigPointsClicked: Incomplete
    sigPointsHovered: Incomplete
    curve: Incomplete
    scatter: Incomplete
    opts: dict[str, Incomplete]
    def __init__(self, *args, **kargs) -> None: ...
    @property
    def xData(self) -> NDArray[Any] | None: ...
    @property
    def yData(self) -> NDArray[Any] | None: ...
    @overload
    def implements(self, interface: str) -> bool: ...
    @overload
    def implements(self, interface: None = None) -> list[str]: ...
    def name(self) -> str | None: ...
    def setCurveClickable(self, state: bool, width: int | None = None) -> None: ...
    def curveClickable(self) -> bool: ...
    def boundingRect(self): ...
    def setPos(self, x: float, y: float) -> None: ...
    def setAlpha(self, alpha: float, auto: bool) -> None: ...
    def setFftMode(self, state: bool) -> None: ...
    def setLogMode(self, xState: bool, yState: bool) -> None: ...
    def setDerivativeMode(self, state: bool) -> None: ...
    def setPhasemapMode(self, state: bool) -> None: ...
    def setPen(self, *args: _PenArg, **kargs) -> None: ...
    def setShadowPen(self, *args: _PenArg, **kargs) -> None: ...
    def setFillBrush(self, *args: _BrushArg, **kargs) -> None: ...
    def setBrush(self, *args: _BrushArg, **kargs) -> None: ...
    def setFillLevel(self, level: float | None) -> None: ...
    def setSymbol(self, symbol: str | Sequence[str] | None) -> None: ...
    def setSymbolPen(self, *args: _PenArg, **kargs) -> None: ...
    def setSymbolBrush(self, *args: _BrushArg, **kargs) -> None: ...
    def setSymbolSize(self, size: float) -> None: ...
    def setDownsampling(
        self, ds: int | None = None, auto: bool | None = None, method: Literal["subsample", "mean", "peak"] | None = None
    ) -> None: ...
    def setClipToView(self, state: bool) -> None: ...
    def setDynamicRangeLimit(self, limit: float | None = 1000000.0, hysteresis: float = 3.0) -> None: ...
    def setSkipFiniteCheck(self, skipFiniteCheck: bool) -> None: ...
    def setData(self, *args, **kargs) -> None: ...
    def updateItems(self, styleUpdate: bool = True) -> None: ...
    def getOriginalDataset(self) -> tuple[NDArray[Any] | None, NDArray[Any] | None]: ...
    def getData(self) -> tuple[NDArray[Any] | None, NDArray[Any] | None]: ...
    def dataRect(self): ...
    def dataBounds(self, ax: int, frac: float = 1.0, orthoRange: Sequence[float] | None = None) -> Sequence[float | None]: ...
    def pixelPadding(self) -> float: ...
    def clear(self) -> None: ...
    def appendData(self, *args, **kargs) -> None: ...
    def curveClicked(self, curve, ev) -> None: ...
    def scatterClicked(self, plt, points, ev) -> None: ...
    def scatterHovered(self, plt, points, ev) -> None: ...
    def viewRangeChanged(self, vb=None, ranges=None, changed=None) -> None: ...
