# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Literal, TypedDict

import numpy as np
from numpy.typing import NDArray

from ..functions import _PenArg
from ..Point import Point, _PointLike
from ..Qt import QtWidgets
from .GraphicsObject import GraphicsObject
from .UIGraphicsItem import UIGraphicsItem

__all__ = [
    "ROI",
    "TestROI",
    "RectROI",
    "EllipseROI",
    "CircleROI",
    "LineROI",
    "MultiLineROI",
    "MultiRectROI",
    "LineSegmentROI",
    "PolyLineROI",
    "CrosshairROI",
    "TriangleROI",
]

class _ROIState(TypedDict):
    pos: Point
    size: Point
    angle: float

class ROI(GraphicsObject):
    sigRegionChangeFinished: Incomplete
    sigRegionChangeStarted: Incomplete
    sigRegionChanged: Incomplete
    sigHoverEvent: Incomplete
    sigClicked: Incomplete
    sigRemoveRequested: Incomplete
    aspectLocked: bool
    translatable: bool
    rotatable: bool
    resizable: bool
    removable: bool
    menu: Incomplete
    freeHandleMoved: bool
    mouseHovering: bool
    hoverPen: Incomplete
    handlePen: Incomplete
    handleHoverPen: Incomplete
    handles: list[dict[str, Incomplete]]
    state: _ROIState
    lastState: _ROIState | None
    isMoving: bool
    handleSize: int
    invertible: bool
    maxBounds: Incomplete
    snapSize: float
    translateSnap: bool | Sequence[float]
    rotateSnap: bool | Sequence[float]
    rotateSnapAngle: float
    scaleSnap: bool | Sequence[float]
    scaleSnapSize: float
    mouseDragHandler: Incomplete
    def __init__(
        self,
        pos: _PointLike,
        size: _PointLike = ...,
        angle: float = 0.0,
        invertible: bool = False,
        maxBounds=None,
        snapSize: float = 1.0,
        scaleSnap: bool = False,
        translateSnap: bool = False,
        rotateSnap: bool = False,
        parent=None,
        pen: _PenArg = None,
        hoverPen: _PenArg = None,
        handlePen: _PenArg = None,
        handleHoverPen: _PenArg = None,
        movable: bool = True,
        rotatable: bool = True,
        resizable: bool = True,
        removable: bool = False,
        aspectLocked: bool = False,
        antialias: bool = True,
    ) -> None: ...
    def getState(self) -> _ROIState: ...
    def stateCopy(self) -> _ROIState: ...
    def saveState(self) -> dict[str, Incomplete]: ...
    def setState(self, state, update: bool = True) -> None: ...
    def setZValue(self, z: float) -> None: ...
    def parentBounds(self): ...
    pen: Incomplete
    currentPen: Incomplete
    def setPen(self, *args: _PenArg, **kwargs) -> None: ...
    def size(self) -> Point: ...
    def pos(self) -> Point: ...
    def angle(self) -> float: ...
    def setPos(self, pos: _PointLike, y: float | None = None, update: bool = True, finish: bool = True) -> None: ...
    def setSize(
        self,
        size: _PointLike,
        center: _PointLike | None = None,
        centerLocal: _PointLike | None = None,
        snap: bool = False,
        update: bool = True,
        finish: bool = True,
    ) -> None: ...
    def setAngle(
        self,
        angle: float,
        center: _PointLike | None = None,
        centerLocal: _PointLike | None = None,
        snap: bool = False,
        update: bool = True,
        finish: bool = True,
    ) -> None: ...
    def scale(
        self,
        s: float | _PointLike,
        center: _PointLike | None = None,
        centerLocal: _PointLike | None = None,
        snap: bool = False,
        update: bool = True,
        finish: bool = True,
    ) -> None: ...
    def translate(self, *args, **kargs) -> None: ...
    def rotate(
        self, angle: float, center: _PointLike | None = None, snap: bool = False, update: bool = True, finish: bool = True
    ) -> None: ...
    preMoveState: Incomplete
    def handleMoveStarted(self) -> None: ...
    def addTranslateHandle(self, pos, axes=None, item=None, name=None, index=None): ...
    def addFreeHandle(self, pos=None, axes=None, item=None, name=None, index=None): ...
    def addScaleHandle(self, pos, center, axes=None, item=None, name=None, lockAspect: bool = False, index=None): ...
    def addRotateHandle(self, pos, center, item=None, name=None, index=None): ...
    def addScaleRotateHandle(self, pos, center, item=None, name=None, index=None): ...
    def addRotateFreeHandle(self, pos, center, axes=None, item=None, name=None, index=None): ...
    def addHandle(self, info, index=None): ...
    def indexOfHandle(self, handle: Handle | int) -> int: ...
    def removeHandle(self, handle) -> None: ...
    def replaceHandle(self, oldHandle, newHandle) -> None: ...
    def checkRemoveHandle(self, handle) -> bool: ...
    def getLocalHandlePositions(self, index=None): ...
    def getSceneHandlePositions(self, index=None): ...
    def getHandles(self) -> list[Handle]: ...
    def mapSceneToParent(self, pt): ...
    def setSelected(self, s) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def setMouseHover(self, hover) -> None: ...
    def contextMenuEnabled(self) -> bool: ...
    def raiseContextMenu(self, ev) -> None: ...
    def getMenu(self): ...
    def removeClicked(self) -> None: ...
    def mouseDragEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def cancelMove(self) -> None: ...
    def checkPointMove(self, handle, pos, modifiers) -> bool: ...
    def movePoint(
        self, handle, pos: _PointLike, modifiers=None, finish: bool = True, coords: Literal["parent", "scene"] = "parent"
    ) -> None: ...
    def stateChanged(self, finish: bool = True) -> None: ...
    def stateChangeFinished(self) -> None: ...
    def stateRect(self, state): ...
    def getSnapPosition(self, pos: _PointLike, snap: bool | Sequence[float] | None = None) -> Point: ...
    def boundingRect(self): ...
    def paint(self, p, opt, widget) -> None: ...
    # `(slices, transform)` when `returnSlice`, otherwise `(bounds, transform)`.
    def getArraySlice(
        self, data: NDArray[Any], img, axes: tuple[int, int] = (0, 1), returnSlice: bool = True
    ) -> tuple[Incomplete, Incomplete]: ...
    # An ndarray, or `(ndarray, coords)` when `returnMappedCoords`.
    def getArrayRegion(
        self, data: NDArray[Any], img, axes: tuple[int, int] = (0, 1), returnMappedCoords: bool = False, **kwds
    ): ...
    def getAffineSliceParams(
        self, data: NDArray[Any], img, axes: tuple[int, int] = (0, 1), fromBoundingRect: bool = False
    ) -> tuple[Incomplete, Incomplete, Incomplete]: ...
    def renderShapeMask(self, width: int, height: int) -> NDArray[np.float64]: ...
    def getGlobalTransform(self, relativeTo=None): ...
    def applyGlobalTransform(self, tr) -> None: ...

class Handle(UIGraphicsItem):
    types: Incomplete
    sigClicked: Incomplete
    sigRemoveRequested: Incomplete
    rois: Incomplete
    radius: Incomplete
    typ: Incomplete
    pen: Incomplete
    hoverPen: Incomplete
    currentPen: Incomplete
    isMoving: bool
    menu: Incomplete
    deletable: Incomplete
    def __init__(
        self,
        radius,
        typ=None,
        pen=(200, 200, 220),
        hoverPen=(255, 255, 0),
        parent=None,
        deletable: bool = False,
        antialias: bool = True,
    ) -> None: ...
    def connectROI(self, roi) -> None: ...
    def disconnectROI(self, roi) -> None: ...
    def setDeletable(self, b) -> None: ...
    def removeClicked(self) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    removeAction: Incomplete
    def buildMenu(self): ...
    def getMenu(self): ...
    def raiseContextMenu(self, ev) -> None: ...
    startPos: Incomplete
    cursorOffset: Incomplete
    def mouseDragEvent(self, ev) -> None: ...
    def movePoint(self, pos, modifiers=None, finish: bool = True) -> None: ...
    path: Incomplete
    def buildPath(self) -> None: ...
    def paint(self, p, opt, widget) -> None: ...
    def shape(self): ...
    def boundingRect(self): ...
    def generateShape(self): ...
    def viewTransformChanged(self) -> None: ...

class MouseDragHandler:
    roi: Incomplete
    dragMode: Incomplete
    startState: Incomplete
    snapModifier: Incomplete
    translateModifier: Incomplete
    rotateModifier: Incomplete
    scaleModifier: Incomplete
    rotateSpeed: float
    scaleSpeed: float
    def __init__(self, roi) -> None: ...
    startPos: Incomplete
    cursorOffset: Incomplete
    def mouseDragEvent(self, ev) -> None: ...

class TestROI(ROI):
    def __init__(self, pos, size, **args) -> None: ...

class RectROI(ROI):
    def __init__(self, pos, size, centered: bool = False, sideScalers: bool = False, **args) -> None: ...

class LineROI(ROI):
    def __init__(self, pos1, pos2, width, **args) -> None: ...

class MultiRectROI(QtWidgets.QGraphicsObject):
    sigRegionChangeFinished: Incomplete
    sigRegionChangeStarted: Incomplete
    sigRegionChanged: Incomplete
    pen: Incomplete
    roiArgs: Incomplete
    lines: Incomplete
    def __init__(self, points, width, pen=None, **args) -> None: ...
    def paint(self, *args) -> None: ...
    def boundingRect(self): ...
    def roiChangedEvent(self) -> None: ...
    def roiChangeStartedEvent(self) -> None: ...
    def roiChangeFinishedEvent(self) -> None: ...
    def getHandlePositions(self): ...
    def getArrayRegion(self, arr: NDArray[Any], img=None, axes: tuple[int, int] = (0, 1), **kwds) -> NDArray[Any]: ...
    def addSegment(self, pos: _PointLike = (0, 0), scaleHandle: bool = False, connectTo=None) -> None: ...
    def removeSegment(self, index: int = -1) -> None: ...

class MultiLineROI(MultiRectROI):
    def __init__(self, *args, **kwds) -> None: ...

class EllipseROI(ROI):
    path: Incomplete
    def __init__(self, pos, size, **args) -> None: ...
    def paint(self, p, opt, widget) -> None: ...
    def getArrayRegion(  # type: ignore[override]
        self, arr: NDArray[Any], img=None, axes: tuple[int, int] = (0, 1), returnMappedCoords: bool = False, **kwds
    ): ...
    def shape(self): ...

class CircleROI(EllipseROI):
    def __init__(self, pos, size=None, radius=None, **args) -> None: ...

class PolyLineROI(ROI):
    closed: Incomplete
    segments: Incomplete
    def __init__(self, positions, closed: bool = False, pos=None, **args) -> None: ...
    def setPoints(self, points, closed=None) -> None: ...
    def clearPoints(self) -> None: ...
    def getState(self) -> _ROIState: ...
    def saveState(self) -> dict[str, Incomplete]: ...
    def setState(self, state) -> None: ...  # type: ignore[override]
    def addSegment(self, h1, h2, index=None) -> None: ...
    def setMouseHover(self, hover) -> None: ...
    def addHandle(self, info, index=None): ...
    def segmentClicked(self, segment, ev=None, pos=None) -> None: ...
    def removeHandle(self, handle, updateSegments: bool = True) -> None: ...
    def removeSegment(self, seg) -> None: ...
    def checkRemoveHandle(self, h): ...
    def paint(self, p, *args) -> None: ...
    def boundingRect(self): ...
    def shape(self): ...
    def getArrayRegion(self, *args, **kwds): ...
    def setPen(self, *args: _PenArg, **kwds) -> None: ...

class LineSegmentROI(ROI):
    def __init__(self, positions=(None, None), pos=None, handles=(None, None), **args) -> None: ...
    @property
    def endpoints(self): ...
    def listPoints(self): ...
    def getState(self) -> _ROIState: ...
    def saveState(self) -> dict[str, Incomplete]: ...
    def setState(self, state) -> None: ...  # type: ignore[override]
    def paint(self, p, *args) -> None: ...
    def boundingRect(self): ...
    def shape(self): ...
    def getArrayRegion(self, data, img, axes=(0, 1), order: int = 1, returnMappedCoords: bool = False, **kwds): ...  # type: ignore[override]

class _PolyLineSegment(LineSegmentROI):
    def __init__(self, *args, **kwds) -> None: ...
    def setParentHover(self, hover) -> None: ...
    def hoverEvent(self, ev): ...

class CrosshairROI(ROI):
    def __init__(self, pos=None, size=None, **kargs) -> None: ...
    def invalidate(self) -> None: ...
    def boundingRect(self): ...
    def shape(self): ...
    def paint(self, p, *args) -> None: ...

class RulerROI(LineSegmentROI):
    def paint(self, p, *args) -> None: ...
    def boundingRect(self): ...

class TriangleROI(ROI):
    poly: Incomplete
    def __init__(self, pos, size, **args) -> None: ...
    def paint(self, p, *args) -> None: ...
    path: Incomplete
    def shape(self): ...
    def getArrayRegion(self, *args, **kwds): ...
