# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, ClassVar, Literal, TypedDict, overload
from typing_extensions import TypeAlias

import numpy as np
from numpy.typing import NDArray

from ..functions import _PenArg
from ..Point import Point, _PointLike
from ..Qt import QtWidgets
from ..SRTTransform import SRTTransform
from .GraphicsObject import GraphicsObject
from .UIGraphicsItem import UIGraphicsItem

__all__ = [
    "ROI",
    "TestROI",
    "RectROI",
    "EllipseROI",
    "CircleROI",
    "LineROI",
    "MultiLineROI",
    "MultiRectROI",
    "LineSegmentROI",
    "PolyLineROI",
    "CrosshairROI",
    "TriangleROI",
]

# Handle kinds, as used by `Handle.types` and the `'type'` key of a handle info dict:
# translate, free, scale, rotate, scale+rotate, rotate+free.
_HandleType: TypeAlias = Literal["t", "f", "s", "r", "sr", "rf"]

# One entry of `ROI.handles`. `center`/`lockAspect` are only present for scale and
# rotate handles; `xoff`/`yoff` only for scale handles whose position shares an axis
# with their center.
class _HandleInfo(TypedDict, total=False):
    name: str | None
    type: _HandleType
    pos: Point | None
    item: Handle | None
    center: Point
    lockAspect: bool
    xoff: bool
    yoff: bool

class _ROIState(TypedDict):
    pos: Point
    size: Point
    angle: float

# `getState()` with `Point`s flattened to tuples, as returned by `saveState()`.
class _ROISavedState(TypedDict):
    pos: tuple[float, float]
    size: tuple[float, float]
    angle: float

class ROI(GraphicsObject):
    sigRegionChangeFinished: Incomplete
    sigRegionChangeStarted: Incomplete
    sigRegionChanged: Incomplete
    sigHoverEvent: Incomplete
    sigClicked: Incomplete
    sigRemoveRequested: Incomplete
    aspectLocked: bool
    translatable: bool
    rotatable: bool
    resizable: bool
    removable: bool
    menu: Incomplete
    freeHandleMoved: bool
    mouseHovering: bool
    hoverPen: Incomplete
    handlePen: Incomplete
    handleHoverPen: Incomplete
    handles: list[_HandleInfo]
    state: _ROIState
    lastState: _ROIState | None
    isMoving: bool
    handleSize: int
    invertible: bool
    maxBounds: Incomplete
    snapSize: float
    translateSnap: bool | Sequence[float]
    rotateSnap: bool | Sequence[float]
    rotateSnapAngle: float
    scaleSnap: bool | Sequence[float]
    scaleSnapSize: float
    mouseDragHandler: MouseDragHandler
    def __init__(
        self,
        pos: _PointLike,
        size: _PointLike = ...,
        angle: float = 0.0,
        invertible: bool = False,
        maxBounds=None,
        snapSize: float = 1.0,
        scaleSnap: bool = False,
        translateSnap: bool = False,
        rotateSnap: bool = False,
        parent=None,
        pen: _PenArg = None,
        hoverPen: _PenArg = None,
        handlePen: _PenArg = None,
        handleHoverPen: _PenArg = None,
        movable: bool = True,
        rotatable: bool = True,
        resizable: bool = True,
        removable: bool = False,
        aspectLocked: bool = False,
        antialias: bool = True,
    ) -> None: ...
    def getState(self) -> _ROIState: ...
    def stateCopy(self) -> _ROIState: ...
    def saveState(self) -> _ROISavedState: ...
    def setState(self, state: _ROIState | _ROISavedState, update: bool = True) -> None: ...
    def setZValue(self, z: float) -> None: ...
    def parentBounds(self): ...
    pen: Incomplete
    currentPen: Incomplete
    def setPen(self, *args: _PenArg, **kwargs) -> None: ...
    def size(self) -> Point: ...
    def pos(self) -> Point: ...
    def angle(self) -> float: ...
    def setPos(self, pos: _PointLike, y: float | None = None, update: bool = True, finish: bool = True) -> None: ...
    def setSize(
        self,
        size: _PointLike,
        center: _PointLike | None = None,
        centerLocal: _PointLike | None = None,
        snap: bool = False,
        update: bool = True,
        finish: bool = True,
    ) -> None: ...
    def setAngle(
        self,
        angle: float,
        center: _PointLike | None = None,
        centerLocal: _PointLike | None = None,
        snap: bool = False,
        update: bool = True,
        finish: bool = True,
    ) -> None: ...
    def scale(
        self,
        s: float | _PointLike,
        center: _PointLike | None = None,
        centerLocal: _PointLike | None = None,
        snap: bool = False,
        update: bool = True,
        finish: bool = True,
    ) -> None: ...
    # (x, y[, snap]) or ([x, y][, snap]); also accepts `snap`, `update` and `finish` keywords.
    def translate(self, *args, **kargs) -> None: ...
    def rotate(
        self, angle: float, center: _PointLike | None = None, snap: bool = False, update: bool = True, finish: bool = True
    ) -> None: ...
    preMoveState: _ROIState
    def handleMoveStarted(self) -> None: ...
    # `axes` is accepted for backwards compatibility and ignored.
    def addTranslateHandle(
        self, pos: _PointLike, axes=None, item: Handle | None = None, name: str | None = None, index: int | None = None
    ) -> Handle: ...
    def addFreeHandle(
        self,
        pos: _PointLike | None = None,
        axes=None,
        item: Handle | None = None,
        name: str | None = None,
        index: int | None = None,
    ) -> Handle: ...
    def addScaleHandle(
        self,
        pos: _PointLike,
        center: _PointLike,
        axes=None,
        item: Handle | None = None,
        name: str | None = None,
        lockAspect: bool = False,
        index: int | None = None,
    ) -> Handle: ...
    def addRotateHandle(
        self, pos: _PointLike, center: _PointLike, item: Handle | None = None, name: str | None = None, index: int | None = None
    ) -> Handle: ...
    def addScaleRotateHandle(
        self, pos: _PointLike, center: _PointLike, item: Handle | None = None, name: str | None = None, index: int | None = None
    ) -> Handle: ...
    def addRotateFreeHandle(
        self,
        pos: _PointLike,
        center: _PointLike,
        axes=None,
        item: Handle | None = None,
        name: str | None = None,
        index: int | None = None,
    ) -> Handle: ...
    def addHandle(self, info: _HandleInfo, index: int | None = None) -> Handle: ...
    def indexOfHandle(self, handle: Handle | int) -> int: ...
    def removeHandle(self, handle: Handle | int) -> None: ...
    def replaceHandle(self, oldHandle: Handle | int, newHandle: Handle) -> None: ...
    def checkRemoveHandle(self, handle: Handle) -> bool: ...
    @overload
    def getLocalHandlePositions(self, index: None = None) -> list[tuple[str | None, Point | None]]: ...
    @overload
    def getLocalHandlePositions(self, index: int) -> tuple[str | None, Point | None]: ...
    @overload
    def getSceneHandlePositions(self, index: None = None) -> list[tuple[str | None, Incomplete]]: ...
    @overload
    def getSceneHandlePositions(self, index: int) -> tuple[str | None, Incomplete]: ...
    def getHandles(self) -> list[Handle]: ...
    def mapSceneToParent(self, pt): ...
    def setSelected(self, s: bool) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def setMouseHover(self, hover: bool) -> None: ...
    def contextMenuEnabled(self) -> bool: ...
    def raiseContextMenu(self, ev) -> None: ...
    def getMenu(self): ...
    def removeClicked(self) -> None: ...
    def mouseDragEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def cancelMove(self) -> None: ...
    def checkPointMove(self, handle: Handle, pos: _PointLike, modifiers) -> bool: ...
    def movePoint(
        self,
        handle: Handle | int,
        pos: _PointLike,
        modifiers=None,
        finish: bool = True,
        coords: Literal["parent", "scene"] = "parent",
    ) -> None: ...
    def stateChanged(self, finish: bool = True) -> None: ...
    def stateChangeFinished(self) -> None: ...
    def stateRect(self, state: _ROIState): ...
    def getSnapPosition(self, pos: _PointLike, snap: bool | Sequence[float] | None = None) -> Point: ...
    def boundingRect(self): ...
    def paint(self, p, opt, widget) -> None: ...
    # `(slices, transform)` when `returnSlice`, otherwise `(bounds, transform)`;
    # `None` if the transform between this ROI and *img* is not invertible.
    def getArraySlice(
        self, data: NDArray[Any], img, axes: tuple[int, int] = (0, 1), returnSlice: bool = True
    ) -> tuple[Incomplete, Incomplete] | None: ...
    # An ndarray, or `(ndarray, coords)` when `returnMappedCoords`.
    def getArrayRegion(
        self, data: NDArray[Any], img, axes: tuple[int, int] = (0, 1), returnMappedCoords: bool = False, **kwds
    ): ...
    # `(shape, vectors, origin)`, ready to pass on to `pyqtgraph.affineSlice`.
    def getAffineSliceParams(
        self, data: NDArray[Any], img, axes: tuple[int, int] = (0, 1), fromBoundingRect: bool = False
    ) -> tuple[list[float], tuple[tuple[float, float], tuple[float, float]], tuple[float, float]]: ...
    def renderShapeMask(self, width: int, height: int) -> NDArray[np.float64]: ...
    def getGlobalTransform(self, relativeTo: _ROIState | None = None) -> SRTTransform: ...
    def applyGlobalTransform(self, tr) -> None: ...

class Handle(UIGraphicsItem):
    # Number of sides and start angle (radians) of the polygon drawn for each handle type.
    types: ClassVar[dict[_HandleType, tuple[int, float]]]
    sigClicked: Incomplete
    sigRemoveRequested: Incomplete
    rois: list[ROI]
    radius: float
    typ: _HandleType | None
    pen: Incomplete
    hoverPen: Incomplete
    currentPen: Incomplete
    isMoving: bool
    menu: Incomplete
    sides: int
    startAng: float
    deletable: bool
    def __init__(
        self,
        radius: float,
        typ: _HandleType | None = None,
        pen: _PenArg = (200, 200, 220),
        hoverPen: _PenArg = (255, 255, 0),
        parent=None,
        deletable: bool = False,
        antialias: bool = True,
    ) -> None: ...
    def connectROI(self, roi: ROI) -> None: ...
    def disconnectROI(self, roi: ROI) -> None: ...
    def setDeletable(self, b: bool) -> None: ...
    def removeClicked(self) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    removeAction: Incomplete
    def buildMenu(self): ...
    def getMenu(self): ...
    def raiseContextMenu(self, ev) -> None: ...
    startPos: Incomplete
    cursorOffset: Incomplete
    def mouseDragEvent(self, ev) -> None: ...
    def movePoint(self, pos: _PointLike, modifiers=None, finish: bool = True) -> None: ...
    path: Incomplete
    def buildPath(self) -> None: ...
    def paint(self, p, opt, widget) -> None: ...
    def shape(self): ...
    def boundingRect(self): ...
    def generateShape(self): ...
    def viewTransformChanged(self) -> None: ...

class MouseDragHandler:
    roi: ROI
    dragMode: Literal["translate", "rotate", "scale"] | None
    startState: _ROISavedState | None
    snapModifier: Incomplete
    translateModifier: Incomplete
    rotateModifier: Incomplete
    scaleModifier: Incomplete
    rotateSpeed: float
    scaleSpeed: float
    def __init__(self, roi: ROI) -> None: ...
    startPos: Incomplete
    cursorOffset: Incomplete
    def mouseDragEvent(self, ev) -> None: ...

class TestROI(ROI):
    def __init__(self, pos: _PointLike, size: _PointLike, **args) -> None: ...

class RectROI(ROI):
    def __init__(self, pos: _PointLike, size: _PointLike, centered: bool = False, sideScalers: bool = False, **args) -> None: ...

class LineROI(ROI):
    def __init__(self, pos1: _PointLike, pos2: _PointLike, width: float, **args) -> None: ...

class MultiRectROI(QtWidgets.QGraphicsObject):
    sigRegionChangeFinished: Incomplete
    sigRegionChangeStarted: Incomplete
    sigRegionChanged: Incomplete
    pen: Incomplete
    roiArgs: dict[str, Incomplete]
    lines: list[ROI]
    # `width` is accepted for backwards compatibility and ignored; the segments are
    # created with a fixed size and then resized by their handles.
    def __init__(self, points: Sequence[_PointLike], width: float, pen: _PenArg = None, **args) -> None: ...
    def paint(self, *args) -> None: ...
    def boundingRect(self): ...
    def roiChangedEvent(self) -> None: ...
    def roiChangeStartedEvent(self) -> None: ...
    def roiChangeFinishedEvent(self) -> None: ...
    def getHandlePositions(self) -> list[Incomplete]: ...
    def getArrayRegion(self, arr: NDArray[Any], img=None, axes: tuple[int, int] = (0, 1), **kwds) -> NDArray[Any]: ...
    def addSegment(
        self, pos: _PointLike = (0, 0), scaleHandle: bool = False, connectTo: Handle | _PointLike | None = None
    ) -> None: ...
    def removeSegment(self, index: int = -1) -> None: ...

class MultiLineROI(MultiRectROI):
    def __init__(self, *args, **kwds) -> None: ...

class EllipseROI(ROI):
    path: Incomplete
    def __init__(self, pos: _PointLike, size: _PointLike, **args) -> None: ...
    def paint(self, p, opt, widget) -> None: ...
    def getArrayRegion(  # type: ignore[override]
        self, arr: NDArray[Any], img=None, axes: tuple[int, int] = (0, 1), returnMappedCoords: bool = False, **kwds
    ): ...
    def shape(self): ...

class CircleROI(EllipseROI):
    def __init__(self, pos: _PointLike, size: _PointLike | None = None, radius: float | None = None, **args) -> None: ...

class _PolyLineROIState(_ROIState):
    closed: bool
    points: list[Point]

class _PolyLineROISavedState(_ROISavedState):
    closed: bool
    points: list[tuple[float, float]]

class PolyLineROI(ROI):
    closed: bool
    segments: list[_PolyLineSegment]
    def __init__(self, positions: Sequence[_PointLike], closed: bool = False, pos: _PointLike | None = None, **args) -> None: ...
    def setPoints(self, points: Sequence[_PointLike], closed: bool | None = None) -> None: ...
    def clearPoints(self) -> None: ...
    def getState(self) -> _PolyLineROIState: ...
    def saveState(self) -> _PolyLineROISavedState: ...
    def setState(self, state: _PolyLineROIState | _PolyLineROISavedState) -> None: ...  # type: ignore[override]
    def addSegment(self, h1: Handle, h2: Handle, index: int | None = None) -> None: ...
    def setMouseHover(self, hover: bool) -> None: ...
    def addHandle(self, info: _HandleInfo, index: int | None = None) -> Handle: ...
    def segmentClicked(self, segment: _PolyLineSegment, ev=None, pos: _PointLike | None = None) -> None: ...
    # Only a `Handle` works here, even though the base class also accepts an index.
    def removeHandle(self, handle: Handle, updateSegments: bool = True) -> None: ...  # type: ignore[override]
    def removeSegment(self, seg: _PolyLineSegment) -> None: ...
    def checkRemoveHandle(self, h: Handle) -> bool: ...
    def paint(self, p, *args) -> None: ...
    def boundingRect(self): ...
    def shape(self): ...
    def getArrayRegion(self, *args, **kwds): ...
    def setPen(self, *args: _PenArg, **kwds) -> None: ...

class _LineSegmentROIState(_ROIState):
    points: list[Point]

class _LineSegmentROISavedState(_ROISavedState):
    points: list[tuple[float, float]]

class LineSegmentROI(ROI):
    def __init__(
        self,
        positions: Sequence[_PointLike | None] = (None, None),
        pos: _PointLike | None = None,
        handles: Sequence[Handle | None] = (None, None),
        **args,
    ) -> None: ...
    @property
    def endpoints(self) -> list[Handle]: ...
    def listPoints(self) -> list[Point]: ...
    def getState(self) -> _LineSegmentROIState: ...
    def saveState(self) -> _LineSegmentROISavedState: ...
    def setState(self, state: _LineSegmentROIState | _LineSegmentROISavedState) -> None: ...  # type: ignore[override]
    def paint(self, p, *args) -> None: ...
    def boundingRect(self): ...
    def shape(self): ...
    # An ndarray, or `(ndarray, coords)` when `returnMappedCoords`.
    def getArrayRegion(  # type: ignore[override]
        self, data: NDArray[Any], img, axes: tuple[int, int] = (0, 1), order: int = 1, returnMappedCoords: bool = False, **kwds
    ): ...

class _PolyLineSegment(LineSegmentROI):
    def __init__(self, *args, **kwds) -> None: ...
    def setParentHover(self, hover: bool) -> None: ...
    def hoverEvent(self, ev): ...

class CrosshairROI(ROI):
    def __init__(self, pos: _PointLike | None = None, size: _PointLike | None = None, **kargs) -> None: ...
    def invalidate(self) -> None: ...
    def boundingRect(self): ...
    def shape(self): ...
    def paint(self, p, *args) -> None: ...

class RulerROI(LineSegmentROI):
    def paint(self, p, *args) -> None: ...
    def boundingRect(self): ...

class TriangleROI(ROI):
    poly: Incomplete
    # `size` is the length of an edge of the triangle, not a length-2 sequence.
    def __init__(self, pos: _PointLike, size: float, **args) -> None: ...
    def paint(self, p, *args) -> None: ...
    path: Incomplete
    def shape(self): ...
    def getArrayRegion(self, *args, **kwds): ...
