from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, overload

import numpy as np
from numpy.typing import NDArray

from .. import debug
from ..functions import _BrushArg, _PenArg
from ..Point import Point
from .GraphicsObject import GraphicsObject

__all__ = ["ScatterPlotItem", "SpotItem"]

class SymbolAtlas:
    def __init__(self) -> None: ...
    def __getitem__(self, styles): ...
    def __len__(self) -> int: ...
    def devicePixelRatio(self) -> float: ...
    def setDevicePixelRatio(self, dpr: float) -> None: ...
    @property
    def pixmap(self): ...
    @property
    def maxWidth(self) -> float: ...
    def rebuild(self, styles=None) -> None: ...
    def clear(self) -> None: ...
    def diagnostics(self) -> dict[str, Incomplete]: ...

class ScatterPlotItem(GraphicsObject):
    sigClicked: Incomplete
    sigHovered: Incomplete
    sigPlotChanged: Incomplete
    picture: Incomplete
    fragmentAtlas: Incomplete
    data: NDArray[np.void]
    bounds: list[Sequence[float] | None]
    opts: dict[str, Incomplete]
    def __init__(self, *args, **kargs) -> None: ...
    def setData(self, *args, **kargs) -> None: ...
    def addPoints(self, *args, **kargs) -> None: ...
    def invalidate(self) -> None: ...
    def getData(self) -> tuple[NDArray[Any], NDArray[Any]]: ...
    @overload
    def implements(self, interface: str) -> bool: ...
    @overload
    def implements(self, interface: None = None) -> list[str]: ...
    def name(self) -> str | None: ...
    def setPen(self, *args: _PenArg, **kargs) -> None: ...
    def setBrush(self, *args: _BrushArg, **kargs) -> None: ...
    def setSymbol(self, symbol, update: bool = True, dataSet=None, mask=None) -> None: ...
    def setSize(self, size: float | Sequence[float], update: bool = True, dataSet=None, mask=None) -> None: ...
    def setPointsVisible(self, visible: bool | Sequence[bool], update: bool = True, dataSet=None, mask=None) -> None: ...
    def setPointData(self, data, dataSet=None, mask=None) -> None: ...
    def setPxMode(self, mode: bool) -> None: ...
    def updateSpots(self, dataSet=None) -> None: ...
    def clear(self) -> None: ...
    def dataBounds(self, ax: int, frac: float = 1.0, orthoRange: Sequence[float] | None = None) -> Sequence[float | None]: ...
    def pixelPadding(self) -> float: ...
    def boundingRect(self): ...
    def viewTransformChanged(self) -> None: ...
    def setExportMode(self, *args, **kwds) -> None: ...
    @debug.warnOnException
    def paint(self, p, option, widget) -> None: ...
    def points(self) -> NDArray[np.object_]: ...
    def pointsAt(self, pos) -> NDArray[np.object_]: ...
    ptsClicked: NDArray[np.object_]
    def mouseClickEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...

class SpotItem:
    def __init__(self, data, plot, index: int) -> None: ...
    def data(self): ...
    def index(self) -> int: ...
    def size(self) -> float: ...
    def pos(self) -> Point: ...
    def viewPos(self): ...
    def setSize(self, size: float) -> None: ...
    def symbol(self): ...
    def setSymbol(self, symbol) -> None: ...
    def pen(self): ...
    def setPen(self, *args: _PenArg, **kargs) -> None: ...
    def resetPen(self) -> None: ...
    def brush(self): ...
    def setBrush(self, *args: _BrushArg, **kargs) -> None: ...
    def resetBrush(self) -> None: ...
    def isVisible(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def setData(self, data) -> None: ...
    def updateItem(self) -> None: ...
