from _typeshed import Incomplete
from collections import OrderedDict
from collections.abc import Sequence
from typing import Any, overload
from typing_extensions import TypeAlias

import numpy as np
from numpy.typing import NDArray

from .. import debug
from ..functions import _BrushArg, _PenArg
from ..Point import Point
from .GraphicsObject import GraphicsObject

__all__ = ["ScatterPlotItem", "SpotItem"]

# A key of `Symbols`, an index into it, or a `QPainterPath` centred on (0, 0) with
# width and height 1.0.
_SymbolArg: TypeAlias = str | int | Incomplete

name_list: list[str]  # undocumented
Symbols: OrderedDict[str, Incomplete]  # undocumented

def makeCrosshair(r: float = 0.5, w: float = 1, h: float = 1): ...  # undocumented
def drawSymbol(painter, symbol: _SymbolArg | None, size: float, pen, brush) -> None: ...  # undocumented
def renderSymbol(symbol: _SymbolArg, size: float, pen, brush, device=None, dpr: float = 1.0): ...  # undocumented

class SymbolAtlas:
    def __init__(self) -> None: ...
    # `(y, x, height, width)` of each style within the atlas pixmap.
    def __getitem__(self, styles) -> list[tuple[int, int, int, int]]: ...
    def __len__(self) -> int: ...
    def devicePixelRatio(self) -> float: ...
    def setDevicePixelRatio(self, dpr: float) -> None: ...
    @property
    def pixmap(self): ...
    @property
    def maxWidth(self) -> float: ...
    def rebuild(self, styles=None) -> None: ...
    def clear(self) -> None: ...
    def diagnostics(self) -> dict[str, Incomplete]: ...

class ScatterPlotItem(GraphicsObject):
    sigClicked: Incomplete
    sigHovered: Incomplete
    sigPlotChanged: Incomplete
    picture: Incomplete
    fragmentAtlas: Incomplete
    data: NDArray[np.void]
    bounds: list[Sequence[float] | None]
    opts: dict[str, Incomplete]
    def __init__(self, *args, **kargs) -> None: ...
    def setData(self, *args, **kargs) -> None: ...
    def addPoints(self, *args, **kargs) -> None: ...
    def invalidate(self) -> None: ...
    def getData(self) -> tuple[NDArray[Any], NDArray[Any]]: ...
    @overload
    def implements(self, interface: str) -> bool: ...
    @overload
    def implements(self, interface: None = None) -> list[str]: ...
    def name(self) -> str | None: ...
    def setPen(self, *args: _PenArg, **kargs) -> None: ...
    def setBrush(self, *args: _BrushArg, **kargs) -> None: ...
    # `dataSet` defaults to this item's whole `data` array; `mask` selects the entries of a
    # per-point sequence that are actually applied to it.
    def setSymbol(
        self,
        symbol: _SymbolArg | Sequence[_SymbolArg] | NDArray[Any],
        update: bool = True,
        dataSet: NDArray[np.void] | None = None,
        mask: NDArray[np.bool_] | None = None,
    ) -> None: ...
    def setSize(
        self,
        size: float | Sequence[float] | NDArray[Any],
        update: bool = True,
        dataSet: NDArray[np.void] | None = None,
        mask: NDArray[np.bool_] | None = None,
    ) -> None: ...
    def setPointsVisible(
        self,
        visible: bool | Sequence[bool] | NDArray[Any],
        update: bool = True,
        dataSet: NDArray[np.void] | None = None,
        mask: NDArray[np.bool_] | None = None,
    ) -> None: ...
    def setPointData(self, data, dataSet: NDArray[np.void] | None = None, mask: NDArray[np.bool_] | None = None) -> None: ...
    def setPxMode(self, mode: bool) -> None: ...
    def updateSpots(self, dataSet: NDArray[np.void] | None = None) -> None: ...
    def clear(self) -> None: ...
    def dataBounds(self, ax: int, frac: float = 1.0, orthoRange: Sequence[float] | None = None) -> Sequence[float | None]: ...
    def pixelPadding(self) -> float: ...
    def boundingRect(self): ...
    def viewTransformChanged(self) -> None: ...
    def setExportMode(self, *args, **kwds) -> None: ...
    @debug.warnOnException
    def paint(self, p, option, widget) -> None: ...
    def points(self) -> NDArray[np.object_]: ...
    def pointsAt(self, pos) -> NDArray[np.object_]: ...
    ptsClicked: NDArray[np.object_]
    def mouseClickEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...

class SpotItem:
    # `data` is one record of the owning item's `data` array.
    def __init__(self, data: np.void, plot: ScatterPlotItem, index: int) -> None: ...
    # The user data associated with this spot.
    def data(self): ...
    def index(self) -> int: ...
    def size(self) -> float: ...
    def pos(self) -> Point: ...
    def viewPos(self): ...
    def setSize(self, size: float) -> None: ...
    # A key of `Symbols`, or the `QPainterPath` set on this spot.
    def symbol(self) -> str | Incomplete: ...
    def setSymbol(self, symbol: _SymbolArg) -> None: ...
    def pen(self): ...
    def setPen(self, *args: _PenArg, **kargs) -> None: ...
    def resetPen(self) -> None: ...
    def brush(self): ...
    def setBrush(self, *args: _BrushArg, **kargs) -> None: ...
    def resetBrush(self) -> None: ...
    def isVisible(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def setData(self, data) -> None: ...
    def updateItem(self) -> None: ...
