from _typeshed import Incomplete
from collections.abc import Callable, Mapping
from typing import Any
from typing_extensions import TypeAlias

from ..functions import _BrushArg, _PenArg
from ..Point import Point, _PointLike
from .TextItem import TextItem
from .UIGraphicsItem import UIGraphicsItem

__all__ = ["TargetItem", "TargetLabel"]

# Either a plain string, a `str.format` template fed `(x, y)`, or a callable of `(x, y)`.
_LabelText: TypeAlias = str | Callable[[float, float], str]

class TargetItem(UIGraphicsItem):
    sigPositionChanged: Incomplete
    sigPositionChangeFinished: Incomplete
    movable: bool
    moving: bool
    mouseHovering: bool
    currentPen: Incomplete
    currentBrush: Incomplete
    scale: Incomplete
    def __init__(
        self,
        pos: _PointLike | None = None,
        size: float = 10,
        # A name from `ScatterPlotItem.Symbols` or a `QPainterPath` centred on
        # (0, 0) with `max(width, height) == 1.0`.
        symbol: str | Incomplete = "crosshair",
        pen: _PenArg = None,
        hoverPen: _PenArg = None,
        brush: _BrushArg = None,
        hoverBrush: _BrushArg = None,
        movable: bool = True,
        label: _LabelText | bool | None = None,
        labelOpts: Mapping[str, Any] | None = None,
    ) -> None: ...
    def setPos(self, *args: _PointLike) -> None: ...
    brush: Incomplete
    def setBrush(self, *args: _BrushArg, **kwargs: _BrushArg) -> None: ...
    hoverBrush: Incomplete
    def setHoverBrush(self, *args: _BrushArg, **kwargs: _BrushArg) -> None: ...
    pen: Incomplete
    def setPen(self, *args: _PenArg, **kwargs) -> None: ...
    hoverPen: Incomplete
    def setHoverPen(self, *args: _PenArg, **kwargs) -> None: ...
    def boundingRect(self): ...
    def paint(self, p, *_) -> None: ...
    def setPath(self, path) -> None: ...
    def shape(self): ...
    # `None` when the item is not attached to a device, in which case the raw path is used.
    def generateShape(self): ...
    symbolOffset: Point
    def mouseDragEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def setMouseHover(self, hover: bool) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def viewTransformChanged(self) -> None: ...
    def pos(self) -> Point: ...
    def label(self) -> TargetLabel | None: ...
    def setLabel(self, text: _LabelText | bool | None = None, labelOpts: Mapping[str, Any] | None = None) -> None: ...

class TargetLabel(TextItem):
    offset: Point
    target: TargetItem
    # `kwargs` are passed on to `TextItem`, minus its `text` parameter.
    def __init__(
        self, target: TargetItem, text: _LabelText = "", offset: _PointLike = (20, 0), anchor: _PointLike = (0, 0.5), **kwargs
    ) -> None: ...
    def format(self) -> _LabelText: ...
    def setFormat(self, text: _LabelText) -> None: ...
    def valueChanged(self) -> None: ...
    def viewTransformChanged(self) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def mouseDragEvent(self, ev) -> None: ...
