from _typeshed import Incomplete
from collections.abc import Sequence
from typing_extensions import TypeAlias

from ..functions import _BrushArg, _ColorArg, _PenArg
from ..Point import Point
from .GraphicsObject import GraphicsObject

__all__ = ["TextItem"]

# A QPointF/QPoint or an (x, y) sequence.
_PointLike: TypeAlias = Sequence[float] | Incomplete

class TextItem(GraphicsObject):
    anchor: Point
    rotateAxis: Point | None
    textItem: Incomplete
    fill: Incomplete
    border: Incomplete
    def __init__(
        self,
        text: str = "",
        color: _ColorArg = (200, 200, 200),
        html: str | None = None,
        anchor: _PointLike = (0, 0),
        border: _PenArg = None,
        fill: _BrushArg = None,
        angle: float = 0,
        rotateAxis: _PointLike | None = None,
        ensureInBounds: bool = False,
    ) -> None: ...
    def setText(self, text: str, color: _ColorArg | None = None) -> None: ...
    def setPlainText(self, text: str) -> None: ...
    def toPlainText(self) -> str: ...
    def setHtml(self, html: str) -> None: ...
    def toHtml(self) -> str: ...
    def setTextWidth(self, *args) -> None: ...
    def setFont(self, *args) -> None: ...
    angle: float
    def setAngle(self, angle: float) -> None: ...
    def setAnchor(self, anchor: _PointLike) -> None: ...
    color: Incomplete
    def setColor(self, color: _ColorArg) -> None: ...
    def updateTextPos(self) -> None: ...
    def dataBounds(self, ax: int, frac: float = 1.0, orthoRange: Sequence[float] | None = None) -> list[float | None]: ...
    def boundingRect(self): ...
    def viewTransformChanged(self) -> None: ...
    def paint(self, p, *args) -> None: ...
    def setVisible(self, v: bool) -> None: ...
    def updateTransform(self, force: bool = False) -> None: ...
