from collections.abc import Sequence

from ..Point import _PointLike
from .GraphicsObject import GraphicsObject

__all__ = ["UIGraphicsItem"]

class UIGraphicsItem(GraphicsObject):
    def __init__(self, bounds=None, parent=None) -> None: ...
    def paint(self, *args) -> None: ...
    def itemChange(self, change, value): ...
    def boundingRect(self): ...
    # UIGraphicsItems are excluded from auto-range, so this is always None.
    def dataBounds(self, axis: int, frac: float = 1.0, orthoRange: Sequence[float] | None = None) -> None: ...
    def viewRangeChanged(self) -> None: ...
    def setNewBounds(self) -> None: ...
    def setPos(self, *args: _PointLike) -> None: ...
    def mouseShape(self): ...
