from _typeshed import Incomplete
from collections.abc import Sequence

from ..functions import _PenArg
from .UIGraphicsItem import UIGraphicsItem

__all__ = ["VTickGroup"]

class VTickGroup(UIGraphicsItem):
    path: Incomplete
    ticks: list[Incomplete]
    xvals: Sequence[float]
    # `[low, high]` as a fraction of the view height; 0 is the bottom, 1 the top.
    yrange: Sequence[float]
    def __init__(
        self, xvals: Sequence[float] | None = None, yrange: Sequence[float] | None = None, pen: _PenArg = None
    ) -> None: ...
    pen: Incomplete
    def setPen(self, *args: _PenArg, **kwargs) -> None: ...
    def setXVals(self, vals: Sequence[float]) -> None: ...
    def setYRange(self, vals: Sequence[float]) -> None: ...
    # VTickGroup never affects view autoscaling, so this is always None.
    def dataBounds(self, *args, **kargs) -> None: ...
    def yRange(self) -> Sequence[float]: ...
    def rebuildTicks(self) -> None: ...
    def paint(self, p, *args) -> None: ...
