# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Literal

from ..functions import _ColorArg
from ..Qt import QtWidgets

__all__ = ["ColorButton"]

class ColorButton(QtWidgets.QPushButton):
    sigColorChanging: Incomplete
    sigColorChanged: Incomplete
    padding: Sequence[float]
    colorDialog: Incomplete
    def __init__(self, parent=None, color: _ColorArg = (128, 128, 128), padding: float | Sequence[float] = 6) -> None: ...
    def paintEvent(self, ev) -> None: ...
    def setColor(self, color: _ColorArg, finished: bool = True) -> None: ...
    origColor: Incomplete
    def selectColor(self) -> None: ...
    def dialogColorChanged(self, color) -> None: ...
    def colorRejected(self) -> None: ...
    def colorSelected(self, color) -> None: ...
    def saveState(self) -> tuple[int, int, int, int]: ...
    def restoreState(self, state: _ColorArg) -> None: ...
    # returns a QColor for "qcolor", a 0-255 RGBA tuple for "byte" and a 0.0-1.0 RGBA tuple for "float"
    def color(self, mode: Literal["qcolor", "byte", "float"] = "qcolor"): ...
    def widgetGroupInterface(self): ...
