# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing import Literal

from ..colormap import ColorMap
from ..Qt import QtWidgets
from .ColorMapMenu import ColorMapMenu

__all__ = ["ColorMapButton"]

class ColorMapDisplayMixin:
    horizontal: bool
    def __init__(self, *, orientation: Literal["horizontal", "vertical"]) -> None: ...
    def setMaximumThickness(self, val: int) -> None: ...
    def setColorMap(self, cmap: ColorMap | str | None) -> None: ...
    def colorMap(self) -> ColorMap: ...
    # a QImage of the colormap's lookup table
    def getImage(self): ...
    def getMenu(self) -> ColorMapMenu: ...
    def paintColorMap(self, painter, rect) -> None: ...

class ColorMapButton(ColorMapDisplayMixin, QtWidgets.QWidget):
    sigColorMapChanged: Incomplete
    def __init__(self) -> None: ...
    def colorMapChanged(self) -> None: ...
    def paintEvent(self, evt) -> None: ...
    def mouseReleaseEvent(self, evt) -> None: ...
