# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from collections.abc import Callable, Mapping, Sequence
from typing import Any
from typing_extensions import Never

from ..Qt import QtWidgets

__all__ = ["ComboBox"]

class ComboBox(QtWidgets.QComboBox):
    def __init__(self, parent=None, items: Sequence[str] | Mapping[str, Any] | None = None, default=None) -> None: ...
    def setValue(self, value) -> None: ...
    def setText(self, text: str) -> None: ...
    def value(self): ...
    # private decorators, defined in the class body without `self`
    def ignoreIndexChange(func: Callable[..., Any]) -> Callable[..., Any]: ...
    def blockIfUnchanged(func: Callable[..., Any]) -> Callable[..., Any]: ...
    def setItems(self, items: Sequence[str] | Mapping[str, Any]) -> None: ...
    def items(self): ...
    def updateList(self, items: Sequence[str] | Mapping[str, Any]) -> None: ...
    def indexChanged(self, index: int) -> None: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def itemsChanged(self) -> None: ...
    def insertItem(self, *args) -> Never: ...
    def insertItems(self, *args) -> Never: ...
    def addItem(self, *args, **kwds) -> None: ...
    def setItemValue(self, name: str, value) -> None: ...
    def addItems(self, items: Sequence[str] | Mapping[str, Any]) -> None: ...
    def clear(self) -> None: ...
    def saveState(self): ...
    def restoreState(self, v) -> None: ...
    def widgetGroupInterface(self): ...
