# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from ..Qt import QtWidgets  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]

__all__ = ["ComboBox"]

class ComboBox(QtWidgets.QComboBox):
    def __init__(self, parent=None, items=None, default=None) -> None: ...
    def setValue(self, value) -> None: ...
    def setText(self, text) -> None: ...
    def value(self): ...
    def ignoreIndexChange(func): ...
    def blockIfUnchanged(func): ...
    def setItems(self, items) -> None: ...
    def items(self): ...
    def updateList(self, items): ...
    def indexChanged(self, index) -> None: ...
    def setCurrentIndex(self, index) -> None: ...
    def itemsChanged(self) -> None: ...
    def insertItem(self, *args) -> None: ...
    def insertItems(self, *args) -> None: ...
    def addItem(self, *args, **kwds) -> None: ...
    def setItemValue(self, name, value) -> None: ...
    def addItems(self, items) -> None: ...
    def clear(self) -> None: ...
    def saveState(self): ...
    def restoreState(self, v) -> None: ...
    def widgetGroupInterface(self): ...
