from _typeshed import Incomplete
from collections.abc import Callable, KeysView, Mapping
from typing import Any

import numpy as np
from numpy.typing import NDArray

from .. import parametertree as ptree
from .ColorMapWidget import _FieldSpecs

__all__ = ["DataFilterWidget"]

class DataFilterWidget(ptree.ParameterTree):
    sigFilterChanged: Incomplete
    params: DataFilterParameter
    # `DataFilterParameter.setFields`, `.generateMask`, `.filterData` and
    # `.describe`, bound in `__init__`
    setFields: Callable[[_FieldSpecs], None]
    generateMask: Callable[..., NDArray[np.bool_]]
    filterData: Callable[..., Any]
    describe: Callable[[], list[str]]
    def __init__(self) -> None: ...
    def parameters(self) -> DataFilterParameter: ...
    def addFilter(self, name: str) -> RangeFilterItem | EnumFilterItem: ...

class DataFilterParameter(ptree.types.GroupParameter):
    sigFilterChanged: Incomplete
    fields: dict[str, Mapping[str, Any]]
    def __init__(self) -> None: ...
    def filterChanged(self) -> None: ...
    def addNew(self, name: str) -> RangeFilterItem | EnumFilterItem: ...  # type: ignore[override]
    def fieldNames(self) -> KeysView[str]: ...
    def setFields(self, fields: _FieldSpecs) -> None: ...
    # `data` is a numpy record array; the rows that pass every filter are returned
    def filterData(self, data): ...
    def generateMask(self, data) -> NDArray[np.bool_]: ...
    def describe(self) -> list[str]: ...

class RangeFilterItem(ptree.types.SimpleParameter):
    fieldName: str
    units: str
    def __init__(self, name: str, opts: Mapping[str, Any]) -> None: ...
    def generateMask(self, data, mask: NDArray[np.bool_]) -> NDArray[np.bool_]: ...
    def describe(self) -> str: ...
    def updateFilter(self, opts: Mapping[str, Any]) -> None: ...

class EnumFilterItem(ptree.types.SimpleParameter):
    fieldName: str
    def __init__(self, name: str, opts: Mapping[str, Any]) -> None: ...
    def generateMask(self, data, startMask: NDArray[np.bool_]) -> NDArray[np.bool_]: ...
    def describe(self) -> str: ...
    def updateFilter(self, opts: Mapping[str, Any]) -> None: ...
    def setEnumVals(self, opts: Mapping[str, Any]) -> None: ...
