# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtWidgets

__all__ = ["FeedbackButton"]

class FeedbackButton(QtWidgets.QPushButton):
    sigCallSuccess: Incomplete
    sigCallFailure: Incomplete
    sigCallProcess: Incomplete
    sigReset: Incomplete
    origStyle: str
    origText: str
    origTip: str
    limitedTime: bool
    def __init__(self, *args) -> None: ...
    def feedback(self, success: bool, message: str | None = None, tip: str = "", limitedTime: bool = True) -> None: ...
    def success(self, message: str | None = None, tip: str = "", limitedTime: bool = True) -> None: ...
    def failure(self, message: str | None = None, tip: str = "", limitedTime: bool = True) -> None: ...
    def processing(self, message: str = "Processing..", tip: str = "", processEvents: bool = True) -> None: ...
    def reset(self) -> None: ...
    count: int
    indStyle: str
    # `color` is any CSS colour accepted by a Qt style sheet
    def startBlink(self, color: str, message: str | None = None, tip: str = "", limitedTime: bool = True) -> None: ...
    def borderOn(self) -> None: ...
    def borderOff(self) -> None: ...
    def setText(self, text: str | None = None, temporary: bool = False) -> None: ...
    def setToolTip(self, text: str | None = None, temporary: bool = False) -> None: ...
    def setStyleSheet(self, style: str | None = None, temporary: bool = False) -> None: ...
