from collections.abc import Sequence

from ..graphicsItems.GraphicsLayout import GraphicsLayout
from ..graphicsItems.LabelItem import LabelItem
from ..graphicsItems.PlotItem import PlotItem
from ..graphicsItems.ViewBox import ViewBox
from .GraphicsView import GraphicsView

__all__ = ["GraphicsLayoutWidget"]

class GraphicsLayoutWidget(GraphicsView):
    ci: GraphicsLayout
    def __init__(
        self, parent=None, show: bool = False, size: Sequence[float] | None = None, title: str | None = None, **kargs
    ) -> None: ...
    # Inherited from GraphicsLayout:
    def nextRow(self) -> None: ...
    def nextColumn(self) -> None: ...
    def nextCol(self, *args, **kargs) -> None: ...
    def addPlot(
        self, row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1, **kargs
    ) -> PlotItem: ...
    def addViewBox(
        self, row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1, **kargs
    ) -> ViewBox: ...
    def addLabel(
        self, text: str = " ", row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1, **kargs
    ) -> LabelItem: ...
    def addLayout(
        self, row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1, **kargs
    ) -> GraphicsLayout: ...
    def addItem(self, item, row: int | None = None, col: int | None = None, rowspan: int = 1, colspan: int = 1) -> None: ...
    def getItem(self, row: int, col: int): ...
    def itemIndex(self, item) -> int: ...
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
