# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..functions import _ColorArg
from ..graphicsItems.ImageItem import ImageItem
from ..GraphicsScene.GraphicsScene import GraphicsScene
from ..Point import Point, _PointLike
from ..Qt import QtWidgets

__all__ = ["GraphicsView"]

class GraphicsView(QtWidgets.QGraphicsView):
    sigDeviceRangeChanged: Incomplete
    sigDeviceTransformChanged: Incomplete
    sigMouseReleased: Incomplete
    sigSceneMouseMoved: Incomplete
    sigScaleChanged: Incomplete
    lastFileDir: str | None
    closed: bool
    lockedViewports: list[GraphicsView]
    lastMousePos: Point | None
    aspectLocked: bool
    range: Incomplete
    autoPixelRange: bool
    currentItem: Incomplete
    sceneObj: GraphicsScene | None
    centralWidget: Incomplete
    centralLayout: Incomplete
    mouseEnabled: bool
    scaleCenter: bool
    clickAccepted: bool
    def __init__(self, parent=None, useOpenGL: bool | None = None, background: _ColorArg = "default") -> None: ...
    def setAntialiasing(self, aa: bool) -> None: ...
    def setBackground(self, background: _ColorArg) -> None: ...
    def paintEvent(self, ev) -> None: ...
    def render(self, *args, **kwds): ...
    def close(self) -> None: ...
    def useOpenGL(self, b: bool = True) -> None: ...
    def keyPressEvent(self, ev) -> None: ...
    def setCentralItem(self, item) -> None: ...
    def setCentralWidget(self, item) -> None: ...
    def addItem(self, *args): ...
    def removeItem(self, *args): ...
    def enableMouse(self, b: bool = True) -> None: ...
    mouseTrail: list[Incomplete]
    lastButtonReleased: Incomplete
    def clearMouse(self) -> None: ...
    def resizeEvent(self, ev) -> None: ...
    def updateMatrix(self, propagate: bool = True) -> None: ...
    def viewRect(self): ...
    def visibleRange(self): ...
    def translate(self, dx: float, dy: float) -> None: ...
    # `center` is a QPointF in view coordinates, not a sequence.
    def scale(self, sx: float, sy: float, center=None) -> None: ...
    def setRange(
        self,
        newRect=None,
        padding: _PointLike = 0.05,
        lockAspect: bool | None = None,
        propagate: bool = True,
        disableAutoPixel: bool = True,
    ) -> None: ...
    def scaleToImage(self, image: ImageItem) -> None: ...
    def lockXRange(self, v1: GraphicsView) -> None: ...
    # `r` is a QRectF; only its left/right (resp. top/bottom) edges are used.
    def setXRange(self, r, padding: float = 0.05) -> None: ...
    def setYRange(self, r, padding: float = 0.05) -> None: ...
    def wheelEvent(self, ev) -> None: ...
    def setAspectLocked(self, s: bool) -> None: ...
    def leaveEvent(self, ev) -> None: ...
    mousePressPos: Incomplete
    def mousePressEvent(self, ev) -> None: ...
    def mouseReleaseEvent(self, ev) -> None: ...
    def mouseMoveEvent(self, ev) -> None: ...
    def pixelSize(self) -> Point: ...
    def dragEnterEvent(self, ev) -> None: ...
