# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtWidgets
from .PathButton import PathButton

__all__ = ["GroupBox"]

class GroupBox(QtWidgets.QGroupBox):
    sigCollapseChanged: Incomplete
    closePath: Incomplete  # QPainterPath
    openPath: Incomplete  # QPainterPath
    collapseBtn: PathButton
    def __init__(self, *args) -> None: ...
    def toggleCollapsed(self) -> None: ...
    def collapsed(self) -> bool: ...
    def setCollapsed(self, c: bool) -> None: ...
    # accepts the `closing` keyword on top of `QGroupBox.setSizePolicy`'s arguments
    def setSizePolicy(self, *args, **kwds) -> None: ...
    def setHorizontalPolicy(self, *args) -> None: ...
    def setVerticalPolicy(self, *args) -> None: ...
    def setTitle(self, title: str) -> None: ...
    def widgetGroupInterface(self): ...
