# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtWidgets  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]

__all__ = ["GroupBox"]

class GroupBox(QtWidgets.QGroupBox):
    sigCollapseChanged: Incomplete
    closePath: Incomplete
    openPath: Incomplete
    collapseBtn: Incomplete
    def __init__(self, *args) -> None: ...
    def toggleCollapsed(self) -> None: ...
    def collapsed(self): ...
    def setCollapsed(self, c) -> None: ...
    def setSizePolicy(self, *args, **kwds) -> None: ...
    def setHorizontalPolicy(self, *args) -> None: ...
    def setVerticalPolicy(self, *args) -> None: ...
    def setTitle(self, title) -> None: ...
    def widgetGroupInterface(self): ...
