# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtWidgets

__all__ = ["JoystickButton"]

class JoystickButton(QtWidgets.QPushButton):
    sigStateChanged: Incomplete
    radius: int
    state: list[float]
    def __init__(self, parent=None) -> None: ...
    pressPos: Incomplete
    def mousePressEvent(self, ev) -> None: ...
    def mouseMoveEvent(self, ev) -> None: ...
    def mouseReleaseEvent(self, ev) -> None: ...
    def wheelEvent(self, ev) -> None: ...
    def doubleClickEvent(self, ev) -> None: ...
    def getState(self) -> list[float]: ...
    spotPos: Incomplete
    def setState(self, *xy: float) -> None: ...
    def paintEvent(self, ev) -> None: ...
    def resizeEvent(self, ev) -> None: ...
