from _typeshed import Incomplete
from collections.abc import Mapping

from ..graphicsItems.MultiPlotItem import MultiPlotItem
from .GraphicsView import GraphicsView

__all__ = ["MultiPlotWidget"]

class MultiPlotWidget(GraphicsView):
    minPlotHeight: int
    mPlotItem: MultiPlotItem
    def __init__(self, parent=None) -> None: ...
    # Any other MultiPlotItem method, forwarded to `self.mPlotItem`.
    def __getattr__(self, attr: str): ...
    def setMinimumPlotHeight(self, min: float) -> None: ...
    def widgetGroupInterface(self): ...
    def saveState(self) -> dict[str, Incomplete]: ...
    def restoreState(self, state: Mapping[str, Incomplete]) -> None: ...
    def close(self) -> None: ...
    def setRange(self, *args, **kwds) -> None: ...
    range: Incomplete
    def resizeEvent(self, ev) -> None: ...
