from _typeshed import Incomplete
from collections.abc import Mapping, Sequence
from typing import Literal
from typing_extensions import TypeAlias

from ..functions import _ColorArg
from ..graphicsItems.AxisItem import AxisItem
from ..graphicsItems.PlotItem import PlotItem
from ..graphicsItems.ViewBox import ViewBox
from .GraphicsView import GraphicsView

__all__ = ["PlotWidget"]

# `ViewBox.XAxis`, `YAxis` or `XYAxes`.
_Axis: TypeAlias = Literal[0, 1, 2]
_Range: TypeAlias = Sequence[float]

class PlotWidget(GraphicsView):
    sigRangeChanged: Incomplete
    sigTransformChanged: Incomplete
    plotItem: PlotItem
    def __init__(self, parent=None, background: _ColorArg = "default", plotItem: PlotItem | None = None, **kargs) -> None: ...
    def close(self) -> None: ...
    # Any other PlotItem method, forwarded to `self.plotItem`.
    def __getattr__(self, attr: str): ...
    def viewRangeChanged(self, view, range) -> None: ...
    def widgetGroupInterface(self): ...
    def saveState(self) -> dict[str, Incomplete]: ...
    def restoreState(self, state: Mapping[str, Incomplete]) -> None: ...
    def getPlotItem(self) -> PlotItem: ...
    # Inherited from PlotItem:
    def setAxisItems(self, axisItems: Mapping[str, AxisItem] | None = None) -> None: ...
    def addItem(self, item, *args, **kargs) -> None: ...  # type: ignore[override]
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
    def register(self, name: str) -> None: ...
    def unregister(self) -> None: ...
    def setMouseEnabled(self, x: bool | None = None, y: bool | None = None) -> None: ...
    def viewRect(self): ...
    def setRange(  # type: ignore[override]
        self,
        rect=None,
        xRange: _Range | None = None,
        yRange: _Range | None = None,
        padding: float | None = None,
        update: bool = True,
        disableAutoRange: bool = True,
    ) -> None: ...
    def setYRange(  # type: ignore[override]
        self, min: float, max: float, padding: float | None = None, update: bool = True
    ) -> None: ...
    def setXRange(  # type: ignore[override]
        self, min: float, max: float, padding: float | None = None, update: bool = True
    ) -> None: ...
    def autoRange(self, padding: float | None = None, items: Sequence[Incomplete] | None = None, item=None) -> None: ...
    def setLimits(self, **kwds) -> None: ...
    def enableAutoRange(
        self,
        axis: _Axis | str | None = None,
        enable: bool | float = True,
        x: bool | float | None = None,
        y: bool | float | None = None,
    ) -> None: ...
    def disableAutoRange(self, axis: _Axis | str | None = None) -> None: ...
    def setXLink(self, view: ViewBox | str | None) -> None: ...
    def setYLink(self, view: ViewBox | str | None) -> None: ...
    def setAspectLocked(self, lock: bool = True, ratio: float | None = 1) -> None: ...
