# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

import mmap
from _typeshed import Incomplete
from typing import IO

from ..multiprocess.processes import QtProcess
from ..Qt import QtCore, QtGui, QtWidgets
from .GraphicsView import GraphicsView

__all__ = ["RemoteGraphicsView"]

class MouseEvent(QtGui.QMouseEvent):
    # (type, localPos, globalPos, button, buttons, modifiers)
    @staticmethod
    def get_state(obj, picklable: bool = False): ...
    def __init__(self, rhs) -> None: ...

class WheelEvent(QtGui.QWheelEvent):
    # (localPos, globalPos, pixelDelta, angleDelta, buttons, modifiers, phase, inverted)
    @staticmethod
    def get_state(obj, picklable: bool = False): ...
    def __init__(self, rhs) -> None: ...

class EnterEvent(QtGui.QEnterEvent):
    # (localPos, windowPos, globalPos)
    @staticmethod
    def get_state(obj): ...
    def __init__(self, rhs) -> None: ...

class LeaveEvent(QtCore.QEvent):
    # (type,)
    @staticmethod
    def get_state(obj, picklable: bool = False): ...
    def __init__(self, rhs) -> None: ...

class RemoteGraphicsView(QtWidgets.QWidget):
    # an `ObjectProxy` for the `pyqtgraph` module imported in the remote process
    pg: Incomplete
    shm: mmap.mmap | None
    shmFile: IO[bytes]
    # `useOpenGL` and `background` are passed to the remote `GraphicsView`, every
    # other keyword to `multiprocess.QtProcess`
    def __init__(self, parent=None, *args, **kwds) -> None: ...
    def resizeEvent(self, ev) -> None: ...
    def sizeHint(self): ...
    # `data` is the `(width, height, size)` tuple emitted by `Renderer.sceneRendered`
    def remoteSceneChanged(self, data: tuple[int, int, int]) -> None: ...
    def paintEvent(self, ev) -> None: ...
    def mousePressEvent(self, ev) -> None: ...
    def mouseReleaseEvent(self, ev) -> None: ...
    def mouseMoveEvent(self, ev) -> None: ...
    def wheelEvent(self, ev) -> None: ...
    def enterEvent(self, ev) -> None: ...
    def leaveEvent(self, ev) -> None: ...
    def remoteProcess(self) -> QtProcess: ...
    def close(self) -> None: ...

# Created by the remote process to handle render requests.
class Renderer(GraphicsView):
    sceneRendered: Incomplete
    shmFile: IO[bytes]
    shm: mmap.mmap
    img: Incomplete  # QImage
    renderTimer: Incomplete
    def __init__(self, *args, **kwds) -> None: ...
    def close(self) -> None: ...
    def shmFileName(self) -> str: ...
    def update(self) -> None: ...
    def resize(self, size) -> None: ...
    def renderView(self) -> None: ...
