# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from decimal import Decimal
from typing import Any

from ..Qt import QtWidgets
from ..SignalProxy import SignalProxy

__all__ = ["SpinBox"]

class SpinBox(QtWidgets.QAbstractSpinBox):
    valueChanged: Incomplete
    sigValueChanged: Incomplete
    sigValueChanging: Incomplete
    lastValEmitted: Decimal | None
    lastText: str
    textValid: bool
    errorBox: ErrorBox
    # keys of `opts`: bounds, wrapping, step, dec, int, finite, prefix, suffix, siPrefix,
    # scaleAtZero, delay, delayUntilEditFinished, decimals, format, regex, evalFunc,
    # compactHeight and (once set) minStep
    opts: dict[str, Any]
    decOpts: list[str]
    val: Decimal
    skipValidate: bool
    proxy: SignalProxy
    def __init__(self, parent=None, value: float = 0.0, **kwargs) -> None: ...
    def setOpts(self, **opts) -> None: ...
    def setMaximum(self, m: float | Decimal | None, update: bool = True) -> None: ...
    def setMinimum(self, m: float | Decimal | None, update: bool = True) -> None: ...
    def wrapping(self) -> bool: ...
    def setWrapping(self, s: bool) -> None: ...
    def setPrefix(self, p: str) -> None: ...
    def setRange(self, r0: float | Decimal | None, r1: float | Decimal | None) -> None: ...
    def setProperty(self, prop: str, val) -> None: ...
    def setSuffix(self, suf: str) -> None: ...
    def setSingleStep(self, step: float | Decimal) -> None: ...
    def setDecimals(self, decimals: int) -> None: ...
    def selectNumber(self) -> None: ...
    def focusInEvent(self, ev) -> None: ...
    def value(self) -> float: ...
    def setValue(self, value: float | Decimal | None = None, update: bool = True, delaySignal: bool = False) -> Decimal: ...
    def emitChanged(self) -> None: ...
    def delayedChange(self) -> None: ...
    def widgetGroupInterface(self): ...
    def sizeHint(self): ...
    def stepEnabled(self): ...
    def stepBy(self, n: int) -> None: ...
    def valueInRange(self, value: float | Decimal) -> bool: ...
    def updateText(self, **kwargs) -> None: ...
    def formatText(self, **kwargs) -> str: ...
    def validate(self, strn: str, pos: int): ...
    def fixup(self, strn: str) -> str: ...
    # returns the interpreted value, or False when the text cannot be parsed
    def interpret(self): ...
    def editingFinishedEvent(self) -> None: ...
    def paintEvent(self, ev) -> None: ...

class ErrorBox(QtWidgets.QWidget):  # undocumented
    def __init__(self, parent) -> None: ...
    def eventFilter(self, obj, ev) -> bool: ...
    def paintEvent(self, ev) -> None: ...
