# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Callable, Generator, Iterator, Sequence
from typing import Any, Literal
from typing_extensions import TypeAlias

from ..Qt import QtWidgets

__all__ = ["TableWidget"]

_SortMode: TypeAlias = Literal["value", "text", "index"] | None
_Format: TypeAlias = str | Callable[[TableWidgetItem], str] | None

class TableWidget(QtWidgets.QTableWidget):
    itemClass: type[TableWidgetItem]
    sortModes: dict[int, _SortMode]
    contextMenu: Incomplete
    # keyword arguments: editable (bool), sortable (bool)
    def __init__(self, *args, **kwds) -> None: ...
    verticalHeadersSet: bool
    horizontalHeadersSet: bool
    items: list[TableWidgetItem]
    def clear(self) -> None: ...
    def setData(self, data) -> None: ...
    def appendData(self, data) -> None: ...
    editable: bool
    def setEditable(self, editable: bool = True) -> None: ...
    def setFormat(self, format: _Format, column: int | None = None) -> None: ...
    def iteratorFn(self, data) -> tuple[Callable[[Any], Iterator[Any]] | None, list[str] | None]: ...
    def iterFirstAxis(self, data) -> Generator[Incomplete]: ...
    def iterate(self, data) -> Generator[Incomplete]: ...
    def iterateScalar(self, data) -> Generator[Incomplete]: ...
    def appendRow(self, data) -> None: ...
    def addRow(self, vals: Sequence[Any]) -> None: ...
    def setRow(self, row: int, vals: Sequence[Any]) -> None: ...
    def setSortMode(self, column: int, mode: _SortMode) -> None: ...
    def sizeHint(self): ...
    def serialize(self, useSelection: bool = False) -> str: ...
    def copySel(self) -> None: ...
    def copyAll(self) -> None: ...
    def saveSel(self) -> None: ...
    def saveAll(self) -> None: ...
    def save(self, data: str) -> None: ...
    def contextMenuEvent(self, ev) -> None: ...
    def keyPressEvent(self, ev) -> None: ...
    def handleItemChanged(self, item: TableWidgetItem) -> None: ...

class TableWidgetItem(QtWidgets.QTableWidgetItem):  # undocumented
    sortMode: _SortMode
    index: int
    def __init__(self, val, index: int, format: _Format = None) -> None: ...
    def setEditable(self, editable: bool) -> None: ...
    def setSortMode(self, mode: _SortMode) -> None: ...
    def setFormat(self, fmt: _Format) -> None: ...
    value: Incomplete
    def setValue(self, value) -> None: ...
    def itemChanged(self) -> None: ...
    def textChanged(self) -> None: ...
    def format(self) -> str: ...
    def __lt__(self, other) -> bool: ...
