# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Iterable

from ..Qt import QtWidgets

__all__ = ["TreeWidget", "TreeWidgetItem"]

class TreeWidget(QtWidgets.QTreeWidget):
    sigItemMoved: Incomplete
    sigItemCheckStateChanged: Incomplete
    sigItemTextChanged: Incomplete
    sigColumnCountChanged: Incomplete
    placeholders: list[Incomplete]
    childNestingLimit: int | None
    def __init__(self, parent=None) -> None: ...
    def setItemWidget(self, item, col: int, wid) -> None: ...
    def itemWidget(self, item, col: int): ...
    def dropMimeData(self, parent, index: int, data, action) -> bool: ...
    def itemMoving(self, item, parent, index: int) -> bool: ...
    def prepareMove(self, item) -> None: ...
    def recoverMove(self, item) -> None: ...
    def collapseTree(self, item) -> None: ...
    def removeTopLevelItem(self, item) -> None: ...
    def listAllItems(self, item=None) -> list[Incomplete]: ...
    def dropEvent(self, ev) -> None: ...
    def updateDropFlags(self) -> None: ...
    @staticmethod
    def informTreeWidgetChange(item) -> None: ...
    def addTopLevelItem(self, item) -> None: ...
    def addTopLevelItems(self, items: Iterable[Incomplete]) -> None: ...
    def insertTopLevelItem(self, index: int, item) -> None: ...
    def insertTopLevelItems(self, index: int, items: Iterable[Incomplete]) -> None: ...
    def takeTopLevelItem(self, index: int): ...
    def topLevelItems(self) -> list[Incomplete]: ...
    def clear(self) -> None: ...
    def invisibleRootItem(self) -> InvisibleRootItem: ...
    def itemFromIndex(self, index) -> tuple[Incomplete, int]: ...
    def setColumnCount(self, c: int) -> None: ...

class TreeWidgetItem(QtWidgets.QTreeWidgetItem):
    def __init__(self, *args) -> None: ...
    def setChecked(self, column: int, checked: bool) -> None: ...
    def isChecked(self, col: int) -> bool: ...
    def setExpanded(self, exp: bool) -> None: ...
    def isExpanded(self) -> bool: ...
    def setWidget(self, column: int, widget) -> None: ...
    def removeWidget(self, column: int) -> None: ...
    def treeWidgetChanged(self) -> None: ...
    def childItems(self) -> list[Incomplete]: ...
    def addChild(self, child) -> None: ...
    def addChildren(self, childs: Iterable[Incomplete]) -> None: ...
    def insertChild(self, index: int, child) -> None: ...
    def insertChildren(self, index: int, childs: Iterable[Incomplete]) -> None: ...
    def removeChild(self, child) -> None: ...
    def takeChild(self, index: int): ...
    def takeChildren(self) -> list[Incomplete]: ...
    def setData(self, column: int, role: int, value) -> None: ...
    def itemClicked(self, col: int) -> None: ...

class InvisibleRootItem:  # undocumented
    def __init__(self, item) -> None: ...
    def addChild(self, child) -> None: ...
    def addChildren(self, childs: Iterable[Incomplete]) -> None: ...
    def insertChild(self, index: int, child) -> None: ...
    def insertChildren(self, index: int, childs: Iterable[Incomplete]) -> None: ...
    def removeChild(self, child) -> None: ...
    def takeChild(self, index: int): ...
    def takeChildren(self) -> list[Incomplete]: ...
    def __getattr__(self, attr: str): ...
