# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from ..Qt import QtWidgets

__all__ = ["ValueLabel"]

class ValueLabel(QtWidgets.QLabel):
    values: list[tuple[float, float]]  # (timestamp, value)
    averageTime: float
    suffix: str
    siPrefix: bool
    formatStr: str
    def __init__(
        self, parent=None, suffix: str = "", siPrefix: bool = False, averageTime: float = 0, formatStr: str | None = None
    ) -> None: ...
    def setValue(self, value: float) -> None: ...
    def setFormatStr(self, text: str) -> None: ...
    def setAverageTime(self, t: float) -> None: ...
    def averageValue(self) -> float: ...
    def paintEvent(self, ev) -> None: ...
    def generateText(self) -> str: ...
