# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtWidgets  # type: ignore[import-not-found]  # pyright: ignore[reportMissingImports]

__all__ = ["ValueLabel"]

class ValueLabel(QtWidgets.QLabel):
    values: Incomplete
    averageTime: Incomplete
    suffix: Incomplete
    siPrefix: Incomplete
    formatStr: Incomplete
    def __init__(self, parent=None, suffix: str = "", siPrefix: bool = False, averageTime: int = 0, formatStr=None) -> None: ...
    def setValue(self, value) -> None: ...
    def setFormatStr(self, text) -> None: ...
    def setAverageTime(self, t) -> None: ...
    def averageValue(self): ...
    def paintEvent(self, ev): ...
    def generateText(self): ...
