# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Mapping
from typing import Literal
from typing_extensions import TypeAlias

from OpenGL.GL import *  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]

from ..Qt import QtCore
from ..Transform3D import Transform3D
from .GLViewWidget import GLViewWidget

# Keys are either an ``OpenGL.GL`` state constant (mapped to a bool, meaning
# glEnable/glDisable) or the name of a callable in ``OpenGL.GL`` (mapped to the
# tuple of arguments to call it with).
_GLOptions: TypeAlias = Mapping[Incomplete, Incomplete]
# Either the name of one of the predefined sets in `GLOptions`, or an explicit
# option mapping.
_GLOptionsArg: TypeAlias = Literal["opaque", "translucent", "additive"] | _GLOptions

GLOptions: dict[str, dict[Incomplete, Incomplete]]

class GLGraphicsItem(QtCore.QObject):
    def __init__(self, parentItem: GLGraphicsItem | None = None) -> None: ...
    def setParentItem(self, item: GLGraphicsItem | None) -> None: ...
    def setGLOptions(self, opts: _GLOptionsArg) -> None: ...
    def updateGLOptions(self, opts: _GLOptions) -> None: ...
    def parentItem(self) -> GLGraphicsItem | None: ...
    def childItems(self) -> list[GLGraphicsItem]: ...
    def view(self) -> GLViewWidget | None: ...
    def setDepthValue(self, value: float) -> None: ...
    def depthValue(self) -> float: ...
    def setTransform(self, tr) -> None: ...
    def resetTransform(self) -> None: ...
    def applyTransform(self, tr, local: bool) -> None: ...
    def transform(self) -> Transform3D: ...
    def viewTransform(self) -> Transform3D: ...
    def translate(self, dx: float, dy: float, dz: float, local: bool = False) -> None: ...
    def rotate(self, angle: float, x: float, y: float, z: float, local: bool = False) -> None: ...
    def scale(self, x: float, y: float, z: float, local: bool = True) -> None: ...
    def hide(self) -> None: ...
    def show(self) -> None: ...
    def setVisible(self, vis: bool) -> None: ...
    def visible(self) -> bool: ...
    def initialize(self) -> None: ...
    def isInitialized(self) -> bool: ...
    def initializeGL(self) -> None: ...
    def setupGLState(self) -> None: ...
    def paint(self) -> None: ...
    def update(self) -> None: ...
    def mapToParent(self, point): ...
    def mapFromParent(self, point): ...
    def mapToView(self, point): ...
    def mapFromView(self, point): ...
