# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing import Any, Literal
from typing_extensions import TypeAlias

import numpy as np
from numpy.typing import NDArray
from OpenGL.GL import *  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]

from ..Qt import QtWidgets
from ..Vector import Vector
from .GLGraphicsItem import GLGraphicsItem

# (x, y, width, height), in device pixels.
_Region: TypeAlias = tuple[float, float, float, float]

class GLViewMixin:
    # Keys: 'center' (Vector), 'rotation' (QQuaternion), 'distance', 'fov',
    # 'elevation', 'azimuth', 'viewport', 'rotationMethod', 'bgcolor'.
    opts: dict[str, Incomplete]
    items: list[GLGraphicsItem]
    noRepeatKeys: list[Incomplete]
    keysPressed: dict[Incomplete, int]
    keyTimer: Incomplete
    def __init__(self, *args, rotationMethod: Literal["euler", "quaternion"] = "euler", **kwargs) -> None: ...
    def deviceWidth(self) -> int: ...
    def deviceHeight(self) -> int: ...
    def reset(self) -> None: ...
    def addItem(self, item: GLGraphicsItem) -> None: ...
    def removeItem(self, item: GLGraphicsItem) -> None: ...
    def clear(self) -> None: ...
    def initializeGL(self) -> None: ...
    def setBackgroundColor(self, *args, **kwds) -> None: ...
    def getViewport(self) -> tuple[int, int, int, int]: ...
    def setProjection(self, region: _Region | None = None) -> None: ...
    def projectionMatrix(self, region: _Region | None = None): ...
    def setModelview(self) -> None: ...
    def viewMatrix(self): ...
    def itemsAt(self, region: _Region | None = None) -> list[GLGraphicsItem]: ...
    def paintGL(self, region: _Region | None = None, viewport: _Region | None = None, useItemNames: bool = False) -> None: ...
    def drawItemTree(self, item: GLGraphicsItem | None = None, useItemNames: bool = False) -> None: ...
    def setCameraPosition(
        self,
        pos: Vector | None = None,
        distance: float | None = None,
        elevation: float | None = None,
        azimuth: float | None = None,
        rotation=None,
    ) -> None: ...
    def cameraPosition(self) -> Vector: ...
    # Accepted keys: 'center', 'rotation', 'distance', 'fov', 'elevation', 'azimuth'.
    def setCameraParams(self, **kwds) -> None: ...
    def cameraParams(self) -> dict[str, Incomplete]: ...
    def orbit(self, azim: float, elev: float) -> None: ...
    def pan(self, dx: float, dy: float, dz: float, relative: Literal["global", "view", "view-upright"] = "global") -> None: ...
    def pixelSize(self, pos: Vector | NDArray[Any]) -> float | NDArray[Any]: ...
    mousePos: Incomplete
    def mousePressEvent(self, ev) -> None: ...
    def mouseMoveEvent(self, ev) -> None: ...
    def mouseReleaseEvent(self, ev) -> None: ...
    def wheelEvent(self, ev) -> None: ...
    def keyPressEvent(self, ev) -> None: ...
    def keyReleaseEvent(self, ev) -> None: ...
    def evalKeyState(self) -> None: ...
    def readQImage(self): ...
    def renderToArray(
        self, size: tuple[float, float], format=..., type=..., textureSize: int = 1024, padding: int = 256
    ) -> NDArray[np.ubyte]: ...

class GLViewWidget(GLViewMixin, QtWidgets.QOpenGLWidget):
    def __init__(self, *args, devicePixelRatio=None, **kwargs) -> None: ...
