from collections.abc import Sequence
from typing import Any, Literal
from typing_extensions import TypeAlias

from numpy.typing import ArrayLike, NDArray

# The only supported indexing modes: `None` for unindexed data, `'faces'` for
# data indexed by face.
_Indexed: TypeAlias = Literal["faces"] | None

class MeshData:
    def __init__(
        self,
        vertexes: ArrayLike | None = None,
        faces: ArrayLike | None = None,
        edges: ArrayLike | None = None,
        vertexColors: ArrayLike | None = None,
        faceColors: ArrayLike | None = None,
    ) -> None: ...
    def faces(self) -> NDArray[Any] | None: ...
    def edges(self) -> NDArray[Any] | None: ...
    def setFaces(self, faces: NDArray[Any]) -> None: ...
    def vertexes(self, indexed: _Indexed = None) -> NDArray[Any] | None: ...
    def setVertexes(self, verts: ArrayLike | None = None, indexed: _Indexed = None, resetNormals: bool = True) -> None: ...
    def resetNormals(self) -> None: ...
    def hasFaceIndexedData(self) -> bool: ...
    def hasEdgeIndexedData(self) -> bool: ...
    def hasVertexColor(self) -> bool: ...
    def hasFaceColor(self) -> bool: ...
    def faceNormals(self, indexed: _Indexed = None) -> NDArray[Any]: ...
    def vertexNormals(self, indexed: _Indexed = None) -> NDArray[Any]: ...
    def vertexColors(self, indexed: _Indexed = None) -> NDArray[Any] | None: ...
    def setVertexColors(self, colors: ArrayLike, indexed: _Indexed = None) -> None: ...
    def faceColors(self, indexed: _Indexed = None) -> NDArray[Any] | None: ...
    def setFaceColors(self, colors: ArrayLike, indexed: _Indexed = None) -> None: ...
    def faceCount(self) -> int | None: ...
    def edgeColors(self) -> NDArray[Any] | None: ...
    def vertexFaces(self) -> list[list[int]]: ...
    def save(self) -> bytes: ...
    def restore(self, state: bytes) -> None: ...
    @staticmethod
    def sphere(rows: int, cols: int, radius: float = 1.0, offset: bool = True) -> MeshData: ...
    @staticmethod
    def cylinder(
        rows: int, cols: int, radius: int | Sequence[float] = [1.0, 1.0], length: float = 1.0, offset: bool = False
    ) -> MeshData: ...
