from _typeshed import Incomplete
from collections.abc import Mapping, Sequence
from typing import ClassVar

from OpenGL.GL import *  # type: ignore[import-not-found, import-untyped]  # pyright: ignore[reportMissingImports]

def initShaders() -> None: ...

CompiledShaderPrograms: dict[Incomplete, Incomplete]

def getShaderProgram(name: str | None) -> ShaderProgram: ...

class Shader:
    shaderType: Incomplete
    code: str
    compiled: Incomplete
    def __init__(self, shaderType, code: str) -> None: ...
    def shader(self): ...

class VertexShader(Shader):
    def __init__(self, code: str) -> None: ...

class FragmentShader(Shader):
    def __init__(self, code: str) -> None: ...

class ShaderProgram:
    names: ClassVar[dict[str | None, ShaderProgram]]
    name: str | None
    shaders: Sequence[Shader]
    prog: Incomplete
    blockData: dict[str, Incomplete]
    uniformData: dict[str, Incomplete]
    def __init__(self, name: str | None, shaders: Sequence[Shader], uniforms: Mapping[str, Incomplete] | None = None) -> None: ...
    def setBlockData(self, blockName: str, data) -> None: ...
    def setUniformData(self, uniformName: str, data) -> None: ...
    def __setitem__(self, item: str, val) -> None: ...
    def __delitem__(self, item: str) -> None: ...
    def program(self): ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args) -> None: ...
    def uniform(self, name: str) -> int: ...

class HeightColorShader(ShaderProgram):
    def __enter__(self) -> None: ...
