from _typeshed import Incomplete

from ..Qt import QtCore
from ..widgets.TreeWidget import TreeWidget
from .Parameter import Parameter
from .ParameterItem import ParameterItem

class ParameterTree(TreeWidget):
    paramSet: Parameter | None
    lastSel: Incomplete
    def __init__(self, parent=None, showHeader: bool = True) -> None: ...
    def setParameters(self, param: Parameter, showTop: bool = True) -> None: ...
    def addParameters(self, param: Parameter, root=None, depth: int = 0, showTop: bool = True) -> None: ...
    def clear(self) -> None: ...
    def focusNext(self, item, forward: bool = True) -> None: ...
    def focusPrevious(self, item) -> None: ...
    def nextFocusableChild(self, root, startItem=None, forward: bool = True) -> ParameterItem | None: ...
    def contextMenuEvent(self, ev) -> None: ...
    def event(self, event: QtCore.QEvent) -> bool: ...
    def itemChangedEvent(self, item, col: int) -> None: ...
    def itemExpandedEvent(self, item) -> None: ...
    def itemCollapsedEvent(self, item) -> None: ...
    def selectionChanged(self, *args): ...
    def sizeHint(self): ...
