# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Callable, Mapping
from typing import Any

from ..Qt import QtWidgets
from .Parameter import Parameter

translate: Incomplete

class ParameterItem(QtWidgets.QTreeWidgetItem):
    param: Parameter
    depth: int
    ignoreNameColumnChange: bool
    def __init__(self, param: Parameter, depth: int = 0) -> None: ...
    def updateFlags(self) -> None: ...
    def valueChanged(self, param: Parameter, val) -> None: ...
    def isFocusable(self) -> bool: ...
    def setFocus(self) -> None: ...
    def focusNext(self, forward: bool = True) -> None: ...
    def treeWidgetChanged(self) -> None: ...
    def childAdded(self, param: Parameter, child: Parameter, pos: int) -> None: ...
    def childRemoved(self, param: Parameter, child: Parameter) -> None: ...
    def parentChanged(self, param: Parameter, parent: Parameter | None) -> None: ...
    contextMenu: Incomplete
    def contextMenuEvent(self, ev) -> None: ...
    def columnChangedEvent(self, col: int) -> None: ...
    def expandedChangedEvent(self, expanded: bool) -> None: ...
    def nameChanged(self, param: Parameter, name: str) -> None: ...
    def titleChanged(self) -> None: ...
    def limitsChanged(self, param: Parameter, limits) -> None: ...
    def defaultChanged(self, param: Parameter, default) -> None: ...
    def optsChanged(self, param: Parameter, opts: Mapping[str, Any]) -> None: ...
    def contextMenuTriggered(self, name: str) -> Callable[[], None]: ...
    def editName(self) -> None: ...
    def selected(self, sel: bool) -> None: ...
    def requestRemove(self) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, x: object) -> bool: ...
