# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

import types
import weakref
from _typeshed import Incomplete
from collections import OrderedDict
from collections.abc import Callable, Iterable, Iterator, Mapping
from typing import Any, Literal

from ..Qt import QtCore
from .ParameterItem import ParameterItem

PARAM_TYPES: dict[str, type[Parameter]]
PARAM_NAMES: dict[type[Parameter], str]

def registerParameterItemType(
    name: str, itemCls: type[ParameterItem], parameterCls: type[Parameter] | None = None, override: bool = False
) -> None: ...
def registerParameterType(name: str, cls: type[Parameter], override: bool = False) -> None: ...
def __reload__(old: Mapping[str, Any]) -> None: ...

class Parameter(QtCore.QObject):
    sigValueChanged: Incomplete
    sigValueChanging: Incomplete
    sigChildAdded: Incomplete
    sigChildRemoved: Incomplete
    sigRemoved: Incomplete
    sigParentChanged: Incomplete
    sigLimitsChanged: Incomplete
    sigDefaultChanged: Incomplete
    sigNameChanged: Incomplete
    sigOptionsChanged: Incomplete
    sigStateChanged: Incomplete
    sigTreeStateChanged: Incomplete
    sigContextMenu: Incomplete
    @staticmethod
    def create(**opts) -> Parameter: ...
    opts: dict[str, Any]
    childs: list[Parameter]
    names: dict[str, Parameter]
    items: weakref.WeakKeyDictionary[ParameterItem, None]
    treeStateChanges: list[tuple[Parameter, str, Any]]
    blockTreeChangeEmit: int
    # `**opts` accepts: name, type, value, default, children, readonly, enabled, visible, renamable,
    # removable, expanded, syncExpanded, strictNaming, title, limits, and any type-specific options
    # (step, siPrefix, suffix, tip, ...). Subclasses add more.
    def __init__(self, **opts) -> None: ...
    @property
    def itemClass(self) -> type[ParameterItem]: ...
    def name(self) -> str: ...
    def title(self) -> str: ...
    def contextMenu(self, name: str) -> None: ...
    def setName(self, name: str) -> str: ...
    def type(self) -> str | None: ...
    def isType(self, typ: str) -> bool: ...
    def childPath(self, child: Parameter) -> list[str] | None: ...
    def setValue(self, value, blockSignal: Callable[..., Any] | None = None): ...
    def hasValue(self) -> bool: ...
    def value(self): ...
    # A tree of {name: (value, children)} pairs, nested to the depth of the parameter tree.
    def getValues(self) -> OrderedDict[str, tuple[Any, Any]]: ...
    # The returned mapping is `self.opts` plus a "children" key; the exact set of keys depends on the
    # parameter type, so it is not a stable TypedDict.
    def saveState(self, filter: Literal["user"] | None = None) -> dict[str, Any]: ...
    def restoreState(
        self,
        state: Mapping[str, Any],
        recursive: bool = True,
        addChildren: bool = True,
        removeChildren: bool = True,
        blockSignals: bool = True,
    ) -> None: ...
    def valueModifiedSinceResetToDefault(self) -> bool: ...
    def defaultValue(self): ...
    def setDefault(self, val, updatePristineValues: bool = False) -> None: ...
    def setToDefault(self) -> None: ...
    def hasDefault(self) -> bool: ...
    def valueIsDefault(self) -> bool: ...
    def setLimits(self, limits): ...
    def writable(self) -> bool: ...
    def setWritable(self, writable: bool = True) -> None: ...
    def readonly(self) -> bool: ...
    def setReadonly(self, readonly: bool = True) -> None: ...
    def setOpts(self, **opts) -> None: ...
    def emitStateChanged(self, changeDesc: str, data) -> None: ...
    def makeTreeItem(self, depth: int) -> ParameterItem: ...
    def addChild(
        self, child: Parameter | Mapping[str, Any], autoIncrementName: bool | None = None, existOk: bool = False
    ) -> Parameter: ...
    def addChildren(self, children: Mapping[str, Any] | Iterable[Parameter | Mapping[str, Any]]) -> None: ...
    def insertChild(
        self,
        pos: int | Parameter,
        child: Parameter | Mapping[str, Any],
        autoIncrementName: bool | None = None,
        existOk: bool = False,
    ) -> Parameter: ...
    def removeChild(self, child: Parameter) -> None: ...
    def clearChildren(self) -> None: ...
    def children(self) -> list[Parameter]: ...
    def hasChildren(self) -> bool: ...
    def parentChanged(self, parent: Parameter | None) -> None: ...
    def parent(self) -> Parameter | None: ...
    def remove(self) -> None: ...
    def incrementName(self, name: str) -> str: ...
    def __iter__(self) -> Iterator[Parameter]: ...
    def __getitem__(self, names: str | tuple[str, ...]): ...
    def __setitem__(self, names: str | tuple[str, ...], value) -> None: ...
    def keys(self) -> dict[str, Parameter]: ...
    def child(self, *names: str) -> Parameter: ...
    def param(self, *names: str) -> Parameter: ...
    def registerItem(self, item: ParameterItem) -> None: ...
    def hide(self) -> None: ...
    def show(self, s: bool = True) -> None: ...
    def treeChangeBlocker(self) -> SignalBlocker: ...
    def blockTreeChangeSignal(self) -> None: ...
    def unblockTreeChangeSignal(self) -> None: ...
    def treeStateChanged(self, param: Parameter, changes: Iterable[tuple[Parameter, str, Any]]) -> None: ...
    def emitTreeChanges(self) -> None: ...

class SignalBlocker:
    enterFn: Callable[[], Any]
    exitFn: Callable[[], Any]
    def __init__(self, enterFn: Callable[[], Any], exitFn: Callable[[], Any]) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_value: BaseException | None, tb: types.TracebackType | None
    ) -> None: ...
