from collections.abc import Iterable
from typing import Any, Literal

from .Parameter import Parameter
from .parameterTypes import GroupParameter
from .SystemSolver import SystemSolver as SystemSolver

__all__ = ["ParameterSystem", "SystemSolver"]

class ParameterSystem(GroupParameter):
    def __init__(self, *args, **kwds) -> None: ...
    def setSystem(self, sys: SystemSolver) -> None: ...
    def updateSystem(self, param: Parameter, changes: Iterable[tuple[Parameter, str, Any]]) -> None: ...
    def updateAllParams(self) -> None: ...
    def updateParamState(self, param: Parameter, state: Literal["autoSet", "autoUnset", "fixed"]) -> None: ...
