from collections import OrderedDict
from collections.abc import Mapping
from typing import Any, ClassVar, Literal
from typing_extensions import Self

class SystemSolver:
    # Maps variable name -> [value, type, constraint, allowed_constraints]; subclasses override it.
    defaultState: ClassVar[OrderedDict[str, list[Any]]]
    def __init__(self) -> None: ...
    def copy(self) -> Self: ...
    def reset(self) -> None: ...
    def __getattr__(self, name: str): ...
    def __setattr__(self, name: str, value) -> None: ...
    def get(self, name: str): ...
    def set(
        self, name: str, value=None, constraint: bool | Literal["fixed"] | tuple[float | None, float | None] | None = True
    ): ...
    def check_constraint(self, name: str, value) -> bool: ...
    def saveState(self) -> OrderedDict[str, tuple[Any, Any]]: ...
    def restoreState(self, state: Mapping[str, tuple[Any, Any]]) -> None: ...
    def resetUnfixed(self) -> None: ...
    def solve(self) -> None: ...
    def checkOverconstraint(self) -> str | Literal[False]: ...
