# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Callable, Mapping, Sequence
from typing import Any

from ...Qt import QtCore
from ..Parameter import Parameter
from ..ParameterItem import ParameterItem

class WidgetParameterItem(ParameterItem):
    asSubItem: bool
    hideWidget: bool
    widget: Incomplete
    eventProxy: EventProxy
    subItem: Incomplete
    defaultBtn: Incomplete
    displayLabel: Incomplete
    layoutWidget: Incomplete
    def __init__(self, param: Parameter, depth: int) -> None: ...
    # Returns a Qt editor widget carrying `sigChanged`, `value()` and `setValue()`; subclasses override it.
    def makeWidget(self): ...
    def widgetEventFilter(self, obj, ev) -> bool: ...
    def makeDefaultButton(self): ...
    def setFocus(self) -> None: ...
    def isFocusable(self) -> bool: ...
    def valueChanged(self, param: Parameter, val, force: bool = False) -> None: ...
    def updateDefaultBtn(self) -> None: ...
    def updateDisplayLabel(self, value=None) -> None: ...
    def widgetValueChanged(self) -> None: ...
    def widgetValueChanging(self, *args) -> None: ...
    def selected(self, sel: bool) -> None: ...
    def showEditor(self) -> None: ...
    def hideEditor(self) -> None: ...
    def limitsChanged(self, param: Parameter, limits) -> None: ...
    def defaultChanged(self, param: Parameter, value) -> None: ...
    def treeWidgetChanged(self) -> None: ...
    def defaultClicked(self) -> None: ...
    def optsChanged(self, param: Parameter, opts: Mapping[str, Any]) -> None: ...

class EventProxy(QtCore.QObject):
    callback: Callable[..., bool]
    def __init__(self, qobj, callback: Callable[..., bool]) -> None: ...
    def eventFilter(self, obj, ev) -> bool: ...

class SimpleParameter(Parameter):
    # `type` is one of "int", "float", "bool", "str", "color", "colormap".
    @property
    def itemClass(self) -> type[ParameterItem]: ...

class GroupParameterItem(ParameterItem):
    addItem: Incomplete
    addWidget: Incomplete
    addWidgetBox: Incomplete
    def __init__(self, param: Parameter, depth: int) -> None: ...
    def pointSize(self) -> int: ...
    def updateDepth(self, depth: int) -> None: ...
    def addClicked(self) -> None: ...
    def addChanged(self) -> None: ...
    def treeWidgetChanged(self) -> None: ...
    def addChild(self, child) -> None: ...
    def optsChanged(self, param: Parameter, opts: Mapping[str, Any]) -> None: ...
    def updateAddList(self) -> None: ...

class GroupParameter(Parameter):
    itemClass: type[GroupParameterItem]
    sigAddNew: Incomplete
    def addNew(self, typ: str | None = None) -> None: ...
    def setAddList(self, vals: Sequence[str]) -> None: ...

class Emitter(QtCore.QObject):
    sigChanging: Incomplete
    sigChanged: Incomplete
