from _typeshed import Incomplete
from collections import OrderedDict
from collections.abc import Callable, Mapping, Sequence
from typing import Any, Literal

from ...SignalProxy import SignalProxy
from ..Parameter import Parameter
from ..ParameterItem import ParameterItem
from . import BoolParameterItem, SimpleParameter
from .basetypes import Emitter, GroupParameter, GroupParameterItem

class ChecklistParameterItem(GroupParameterItem):
    btnGrp: Incomplete
    metaBtnWidget: Incomplete
    metaBtnLayout: Incomplete
    metaBtns: dict[str, Incomplete]
    def __init__(self, param: Parameter, depth: int) -> None: ...
    def treeWidgetChanged(self) -> None: ...
    def selectAllClicked(self) -> None: ...
    def clearAllClicked(self) -> None: ...
    def insertChild(self, pos, item): ...
    def addChild(self, item): ...
    def takeChild(self, i: int) -> None: ...
    def optsChanged(self, param: Parameter, opts: Mapping[str, Any]) -> None: ...
    def expandedChangedEvent(self, expanded: bool) -> None: ...
    def valueChanged(self, param: Parameter, val) -> None: ...
    def updateDefaultBtn(self) -> None: ...
    makeDefaultButton: Incomplete
    defaultClicked: Incomplete

class RadioParameterItem(BoolParameterItem):
    emitter: Emitter
    def __init__(self, param: Parameter, depth: int) -> None: ...
    hideWidget: bool
    # Returns a QRadioButton.
    def makeWidget(self): ...
    def maybeSigChanged(self, val: bool) -> None: ...

class BoolOrRadioParameter(SimpleParameter):
    @property
    def itemClass(self) -> type[ParameterItem]: ...

class ChecklistParameter(GroupParameter):
    itemClass: type[ChecklistParameterItem]
    targetValue: Any
    valChangingProxy: SignalProxy
    forward: OrderedDict[str, Any]
    reverse: tuple[list[Any], list[str]]
    # `**opts` adds "limits", "exclusive" (default False) and "delay" (default 1.0) to the standard
    # Parameter options. Passing "children" raises ValueError.
    def __init__(self, **opts) -> None: ...
    # A list of the checked values, or -- when "exclusive" is set -- a single value or None.
    def childrenValue(self): ...
    def updateLimits(self, _param: Parameter | None, limits: Sequence[Any] | Mapping[str, Any]) -> None: ...
    def optsChanged(self, param: Parameter, opts: Mapping[str, Any]) -> None: ...
    def setValue(self, value, blockSignal: Callable[..., Any] | None = None) -> None: ...
    def setToDefault(self) -> None: ...
    def saveState(self, filter: Literal["user"] | None = None) -> dict[str, Any]: ...
    def restoreState(
        self,
        state: Mapping[str, Any],
        recursive: bool = True,
        addChildren: bool = True,
        removeChildren: bool = True,
        blockSignals: bool = True,
    ) -> None: ...
