from collections.abc import Mapping, Sequence
from typing import Any

from ..Parameter import Parameter
from .basetypes import WidgetParameterItem

class NumericParameterItem(WidgetParameterItem):
    # Returns a `pyqtgraph.SpinBox`; the "int" and "float" parameter types both use it.
    def makeWidget(self): ...
    def updateDisplayLabel(self, value=None) -> None: ...
    def showEditor(self) -> None: ...
    def limitsChanged(self, param: Parameter, limits: Sequence[float | None] | None) -> None: ...
    def optsChanged(self, param: Parameter, opts: Mapping[str, Any]) -> None: ...
