from _typeshed import Incomplete, StrPath
from collections.abc import Mapping, Sequence
from typing import Any, ClassVar

from ..parametertree import Parameter

LastExportDirectory: str | None

class Exporter:
    allowCopy: bool
    Exporters: ClassVar[list[type[Exporter]]]
    @classmethod
    def register(cls) -> None: ...
    item: Incomplete
    def __init__(self, item) -> None: ...
    def parameters(self) -> Parameter | None: ...
    def export(self, fileName: StrPath | None = None, toBytes: bool = False, copy: bool = False) -> None: ...
    fileDialog: Incomplete
    def fileSaveDialog(self, filter: str | Sequence[str] | None = None, opts: Mapping[str, Any] | None = None) -> None: ...
    def fileSaveFinished(self, fileName: str) -> None: ...
    def getScene(self): ...
    def getSourceRect(self): ...
    def getTargetRect(self): ...
    def setExportMode(self, export: bool, opts: Mapping[str, Any] | None = None) -> None: ...
    def getPaintItems(self, root=None) -> list[Incomplete]: ...
    def render(self, painter, targetRect, sourceRect, item=None) -> None: ...
