# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing_extensions import Self

from ..Qt import QtCore

class Mutex(QtCore.QMutex):
    l: Incomplete
    tb: list[str]
    debug: bool
    def __init__(self, *args, **kargs) -> None: ...
    def tryLock(self, timeout: float | None = None, id: object = None) -> bool: ...
    def lock(self, id: object = None) -> None: ...
    def unlock(self) -> None: ...
    def acquire(self, blocking: bool = True) -> bool: ...
    def release(self) -> None: ...
    def depth(self) -> int: ...
    def traceback(self) -> list[str]: ...
    def __exit__(self, *args: object) -> None: ...
    def __enter__(self) -> Self: ...

class RecursiveMutex(Mutex):
    def __init__(self, **kwds) -> None: ...
