# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..exporters.Exporter import Exporter
from ..Qt import QtWidgets
from .GraphicsScene import GraphicsScene

class FormatExportListWidgetItem(QtWidgets.QListWidgetItem):
    expClass: type[Exporter]
    def __init__(self, expClass: type[Exporter], *args, **kwargs) -> None: ...

class ExportDialog(QtWidgets.QWidget):
    shown: bool
    currentExporter: Exporter | None
    scene: GraphicsScene
    selectBox: Incomplete  # QtWidgets.QGraphicsRectItem
    ui: Incomplete  # exportDialogTemplate_generic.Ui_Form
    def __init__(self, scene: GraphicsScene) -> None: ...
    def show(self, item=None) -> None: ...
    def updateItemList(self, select=None) -> None: ...
    def updateItemTree(self, item, treeItem, select=None) -> None: ...
    def exportItemChanged(self, item, prev) -> None: ...
    def updateFormatList(self) -> None: ...
    def exportFormatChanged(self, item, prev) -> None: ...
    def exportClicked(self) -> None: ...
    def copyClicked(self) -> None: ...
    def close(self) -> None: ...
    def closeEvent(self, event) -> None: ...
