# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from typing import ClassVar
from weakref import WeakKeyDictionary

from ..Qt import QtWidgets
from .exportDialog import ExportDialog
from .mouseEvents import HoverEvent, MouseClickEvent, MouseDragEvent

__all__ = ["GraphicsScene"]

class GraphicsScene(QtWidgets.QGraphicsScene):
    sigMouseHover: Incomplete
    sigMouseMoved: Incomplete
    sigMouseClicked: Incomplete
    sigPrepareForPaint: Incomplete
    sigItemAdded: Incomplete
    sigItemRemoved: Incomplete
    ExportDirectory: ClassVar[str | None]
    exportDirectory: str | None
    clickEvents: list[MouseClickEvent]
    dragButtons: list[Incomplete]  # list[QtCore.Qt.MouseButton]
    mouseGrabber: Incomplete
    dragItem: Incomplete  # QGraphicsItem | None
    lastDrag: MouseDragEvent | None
    hoverItems: WeakKeyDictionary[Incomplete, None]  # keys are QGraphicsItem
    lastHoverEvent: HoverEvent | None
    minDragTime: float
    contextMenu: list[Incomplete]  # list[QtGui.QAction]
    exportDialog: ExportDialog | None
    def __init__(self, clickRadius: int = 2, moveDistance: float = 5, parent=None) -> None: ...
    def render(self, *args) -> None: ...
    def prepareForPaint(self) -> None: ...
    def setClickRadius(self, r: int) -> None: ...
    def setMoveDistance(self, d: float) -> None: ...
    def mousePressEvent(self, ev) -> None: ...
    def mouseMoveEvent(self, ev) -> None: ...
    def leaveEvent(self, ev) -> None: ...
    def mouseReleaseEvent(self, ev) -> None: ...
    def mouseDoubleClickEvent(self, ev) -> None: ...
    def sendHoverEvents(self, ev, exitOnly: bool = False) -> None: ...
    def sendDragEvent(self, ev, init: bool = False, final: bool = False) -> bool: ...
    def sendClickEvent(self, ev: MouseClickEvent) -> bool: ...
    def addItem(self, item) -> None: ...
    def removeItem(self, item) -> None: ...
    def itemsNearEvent(self, event, selMode=..., sortOrder=..., hoverable: bool = False) -> list[Incomplete]: ...
    def getViewWidget(self): ...
    def addParentContextMenus(self, item, menu, event): ...
    contextMenuItem: Incomplete
    def getContextMenus(self, event) -> list[Incomplete]: ...
    def showExportDialog(self) -> None: ...
