from _typeshed import Incomplete

from ..Point import Point

__all__ = ["MouseDragEvent", "MouseClickEvent", "HoverEvent"]

class MouseDragEvent:
    start: bool
    finish: bool
    accepted: bool
    currentItem: Incomplete
    acceptedItem: Incomplete
    def __init__(self, moveEvent, pressEvent, lastEvent, start: bool = False, finish: bool = False) -> None: ...
    def accept(self) -> None: ...
    def ignore(self) -> None: ...
    def isAccepted(self) -> bool: ...
    def scenePos(self) -> Point: ...
    def screenPos(self) -> Point: ...
    def buttonDownScenePos(self, btn=None) -> Point: ...
    def buttonDownScreenPos(self, btn=None) -> Point: ...
    def lastScenePos(self) -> Point: ...
    def lastScreenPos(self) -> Point: ...
    def buttons(self): ...
    def button(self): ...
    def pos(self) -> Point: ...
    def lastPos(self) -> Point: ...
    def buttonDownPos(self, btn=None) -> Point: ...
    def isStart(self) -> bool: ...
    def isFinish(self) -> bool: ...
    def modifiers(self): ...

class MouseClickEvent:
    accepted: bool
    currentItem: Incomplete
    acceptedItem: Incomplete
    def __init__(self, pressEvent, double: bool = False) -> None: ...
    def accept(self) -> None: ...
    def ignore(self) -> None: ...
    def isAccepted(self) -> bool: ...
    def scenePos(self) -> Point: ...
    def screenPos(self) -> Point: ...
    def buttons(self): ...
    def button(self): ...
    def double(self) -> bool: ...
    def pos(self) -> Point: ...
    def lastPos(self) -> Point: ...
    def modifiers(self): ...
    def time(self) -> float: ...

class HoverEvent:
    enter: bool
    acceptable: bool
    exit: bool
    currentItem: Incomplete
    def __init__(self, moveEvent, acceptable) -> None: ...
    def isEnter(self) -> bool: ...
    def isExit(self) -> bool: ...
    def acceptClicks(self, button) -> bool: ...
    def acceptDrags(self, button) -> bool: ...
    def scenePos(self) -> Point: ...
    def screenPos(self) -> Point: ...
    def lastScenePos(self) -> Point: ...
    def lastScreenPos(self) -> Point: ...
    def buttons(self): ...
    def pos(self) -> Point: ...
    def lastPos(self) -> Point: ...
    def modifiers(self): ...
    def clickItems(self) -> dict[Incomplete, Incomplete]: ...
    def dragItems(self) -> dict[Incomplete, Incomplete]: ...
