# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete, StrPath
from collections.abc import Mapping
from typing import Any, Literal

from .. import dockarea as dockarea
from ..graphicsItems.GraphicsObject import GraphicsObject
from ..Point import _PointLike
from ..Qt import QtWidgets
from .Node import Node
from .NodeLibrary import NodeLibrary
from .Terminal import Terminal, TerminalGraphicsItem

# Upstream typo: this is spelled `__init__` rather than `__all__`, so it has no
# effect on `from ... import *`.
__init__: list[str]

def strDict(d: Mapping[Any, Any]) -> dict[str, Any]: ...

class Flowchart(Node):
    sigFileLoaded: Incomplete
    sigFileSaved: Incomplete
    sigChartLoaded: Incomplete
    sigStateChanged: Incomplete
    sigChartChanged: Incomplete
    library: NodeLibrary
    filePath: str | None
    inputWasSet: bool
    nextZVal: int
    processing: bool
    inputNode: Node
    outputNode: Node
    def __init__(
        self,
        # {terminal name: options passed on to `Terminal.__init__`}
        terminals: Mapping[str, Mapping[str, Any]] | None = None,
        name: str | None = None,
        filePath: str | None = None,
        library: NodeLibrary | None = None,
    ) -> None: ...
    def setLibrary(self, lib: NodeLibrary) -> None: ...
    def setInput(self, **args) -> None: ...
    def outputChanged(self) -> None: ...
    def output(self) -> dict[str, Any]: ...
    def nodes(self) -> dict[str, Node]: ...
    def addTerminal(self, name: str, **opts) -> Terminal: ...
    # Unlike `Node.removeTerminal`, this accepts only a terminal name.
    def removeTerminal(self, name: str) -> None: ...  # type: ignore[override]
    def internalTerminalRenamed(self, term: Terminal, oldName: str) -> None: ...
    def internalTerminalAdded(self, node: Node, term: Terminal) -> None: ...
    def internalTerminalRemoved(self, node: Node, term: Terminal) -> None: ...
    def terminalRenamed(self, term: Terminal, oldName: str) -> None: ...
    def createNode(self, nodeType: str, name: str | None = None, pos: _PointLike | None = None) -> Node: ...
    def addNode(self, node: Node, name: str, pos: _PointLike | None = None) -> None: ...
    def removeNode(self, node: Node) -> None: ...
    def nodeClosed(self, node: Node) -> None: ...
    def nodeRenamed(self, node: Node, oldName: str) -> None: ...
    def arrangeNodes(self) -> None: ...
    def internalTerminal(self, term: Terminal) -> Terminal: ...
    def connectTerminals(self, term1: Terminal, term2: Terminal) -> None: ...
    # Keyword arguments are input terminal names; returns {output terminal name: value}.
    def process(self, **args) -> dict[str, Any]: ...
    # ("p", node) means process that node, ("d", terminal) means its value may be dropped.
    def processOrder(self) -> list[tuple[Literal["p"], Node] | tuple[Literal["d"], Terminal]]: ...
    def nodeOutputChanged(self, startNode: Node) -> None: ...
    def chartGraphicsItem(self): ...
    scene: Incomplete  # GraphicsScene
    viewBox: Incomplete  # FlowchartViewBox
    def widget(self) -> FlowchartCtrlWidget: ...
    def listConnections(self) -> set[tuple[Terminal, Terminal]]: ...
    # Extends `Node.saveState` with the "nodes", "connects", "inputNode" and "outputNode" keys.
    def saveState(self) -> dict[str, Any]: ...
    def restoreState(self, state: Mapping[str, Any], clear: bool = False) -> None: ...
    fileDialog: Incomplete  # FileDialog
    def loadFile(self, fileName: StrPath | None = None, startDir: str | None = None) -> None: ...
    def saveFile(
        self, fileName: StrPath | None = None, startDir: str | None = None, suggestedFileName: str = "flowchart.fc"
    ) -> None: ...
    def clear(self) -> None: ...
    def clearTerminals(self) -> None: ...

class FlowchartGraphicsItem(GraphicsObject):
    chart: Flowchart
    def __init__(self, chart: Flowchart) -> None: ...
    terminals: dict[str, TerminalGraphicsItem]
    def updateTerminals(self) -> None: ...
    def boundingRect(self): ...
    def paint(self, p, *args) -> None: ...

class FlowchartCtrlWidget(QtWidgets.QWidget):
    items: dict[Node, Incomplete]  # {node: QTreeWidgetItem}
    currentFileName: StrPath | None
    chart: Flowchart
    ui: Incomplete
    cwWin: Incomplete
    def __init__(self, chart: Flowchart) -> None: ...
    def chartToggled(self, b: bool) -> None: ...
    def reloadClicked(self) -> None: ...
    def loadClicked(self) -> None: ...
    def fileSaved(self, fileName: StrPath) -> None: ...
    def saveClicked(self) -> None: ...
    def saveAsClicked(self) -> None: ...
    def setCurrentFile(self, fileName: StrPath | None) -> None: ...
    def itemChanged(self, *args) -> None: ...
    def scene(self): ...
    def viewBox(self): ...
    def nodeRenamed(self, node: Node, oldName: str) -> None: ...
    def addNode(self, node: Node) -> None: ...
    def removeNode(self, node: Node) -> None: ...
    def bypassClicked(self) -> None: ...
    # Upstream bug: `__init__` assigns a `FlowchartWidget` to `self.chartWidget`,
    # so this method is unreachable on an instance.
    def chartWidget(self): ...
    def outputChanged(self, data: Mapping[str, Any]) -> None: ...
    def clear(self) -> None: ...
    def select(self, node: Node) -> None: ...
    def clearSelection(self) -> None: ...

class FlowchartWidget(dockarea.DockArea):
    chart: Flowchart
    ctrl: FlowchartCtrlWidget
    hoverItem: Incomplete
    view: Incomplete
    viewDock: Incomplete
    hoverText: Incomplete
    hoverDock: Incomplete
    selInfo: Incomplete
    selInfoLayout: Incomplete
    selDescLabel: Incomplete
    selNameLabel: Incomplete
    selectedTree: Incomplete
    selDock: Incomplete
    def __init__(self, chart: Flowchart, ctrl: FlowchartCtrlWidget) -> None: ...
    nodeMenu: Incomplete
    subMenus: list[Incomplete]
    def reloadLibrary(self) -> None: ...
    def buildMenu(self, pos=None): ...
    menuPos: Incomplete
    def menuPosChanged(self, pos) -> None: ...
    def showViewMenu(self, ev) -> None: ...
    def scene(self): ...
    def viewBox(self): ...
    def nodeMenuTriggered(self, action) -> None: ...
    def selectionChanged(self) -> None: ...
    def hoverOver(self, items) -> None: ...
    def clear(self) -> None: ...

class FlowchartNode(Node): ...
