from _typeshed import Incomplete
from collections import OrderedDict
from collections.abc import Sequence
from typing_extensions import TypeGuard

from .Node import Node

# `nodeTree` nests one level per path component, with node classes as leaves.
def isNodeClass(cls: type) -> TypeGuard[type[Node]]: ...

class NodeLibrary:
    nodeList: OrderedDict[str, type[Node]]
    nodeTree: OrderedDict[str, Incomplete]
    def __init__(self) -> None: ...
    def addNodeType(self, nodeClass: type[Node], paths: Sequence[Sequence[str]], override: bool = False) -> None: ...
    def getNodeType(self, name: str) -> type[Node]: ...
    def getNodeTree(self) -> OrderedDict[str, Incomplete]: ...
    def copy(self) -> NodeLibrary: ...
    @staticmethod
    def treeCopy(tree: OrderedDict[str, Incomplete]) -> OrderedDict[str, Incomplete]: ...
    def reload(self) -> None: ...
