# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete, OptExcInfo
from collections import OrderedDict
from collections.abc import Callable, Mapping
from typing import Any

from ..graphicsItems.GraphicsObject import GraphicsObject
from ..Qt import QtCore, QtWidgets
from .Terminal import Terminal, TerminalGraphicsItem

__all__ = ["Node", "NodeGraphicsItem"]

class Node(QtCore.QObject):
    sigOutputChanged: Incomplete
    sigClosed: Incomplete
    sigRenamed: Incomplete
    sigTerminalRenamed: Incomplete
    sigTerminalAdded: Incomplete
    sigTerminalRemoved: Incomplete
    bypassButton: Incomplete  # QPushButton | None, assigned by the flowchart control widget
    terminals: OrderedDict[str, Terminal]
    # `sys.exc_info()` captured the last time `update()` raised, or None.
    exception: OptExcInfo | None
    def __init__(
        self,
        name: str,
        # {terminal name: options passed on to `Terminal.__init__`}
        terminals: Mapping[str, Mapping[str, Any]] | None = None,
        allowAddInput: bool = False,
        allowAddOutput: bool = False,
        allowRemove: bool = True,
    ) -> None: ...
    def nextTerminalName(self, name: str) -> str: ...
    def addInput(self, name: str = "Input", **args) -> Terminal: ...
    def addOutput(self, name: str = "Output", **args) -> Terminal: ...
    def removeTerminal(self, term: Terminal | str) -> None: ...
    def terminalRenamed(self, term: Terminal, oldName: str) -> None: ...
    def addTerminal(self, name: str, **opts) -> Terminal: ...
    def inputs(self) -> OrderedDict[str, Terminal]: ...
    def outputs(self) -> OrderedDict[str, Terminal]: ...
    # Called with one keyword argument per input terminal plus `display`; returns
    # {output terminal name: value}. Subclasses override this with named parameters.
    def process(self, **kargs): ...
    def graphicsItem(self) -> NodeGraphicsItem: ...
    def __getitem__(self, item: str) -> Terminal: ...
    def name(self) -> str: ...
    def rename(self, name: str) -> None: ...
    def dependentNodes(self) -> set[Node]: ...
    # Subclasses return the QWidget shown in the flowchart control panel.
    def ctrlWidget(self) -> None: ...
    def bypass(self, byp: bool) -> None: ...
    def isBypassed(self) -> bool: ...
    def setInput(self, **args) -> None: ...
    def inputValues(self) -> dict[str, Any]: ...
    def outputValues(self) -> dict[str, Any]: ...
    def connected(self, localTerm: Terminal, remoteTerm: Terminal) -> None: ...
    def disconnected(self, localTerm: Terminal, remoteTerm: Terminal) -> None: ...
    def update(self, signal: bool = True) -> None: ...
    # Returns {output terminal name: value}; `library.Display.PlotWidgetNode` overrides it
    # to return None, so the return type is left open here.
    def processBypassed(self, args: Mapping[str, Any]): ...
    def setOutput(self, **vals) -> None: ...
    def setOutputNoSignal(self, **vals) -> None: ...
    def setException(self, exc: OptExcInfo | None) -> None: ...
    def clearException(self) -> None: ...
    def recolor(self) -> None: ...
    # Keys: "pos", "bypass" and, when any terminal is editable, "terminals".
    # Subclasses may add their own keys.
    def saveState(self) -> dict[str, Any]: ...
    def restoreState(self, state: Mapping[str, Any]) -> None: ...
    def saveTerminals(self) -> OrderedDict[str, dict[str, Any]]: ...
    def restoreTerminals(self, state: Mapping[str, Mapping[str, Any]]) -> None: ...
    def clearTerminals(self) -> None: ...
    def close(self) -> None: ...
    def disconnectAll(self) -> None: ...

class TextItem(QtWidgets.QGraphicsTextItem):
    on_update: Callable[[], object] | None
    def __init__(self, text: str, parent, on_update: Callable[[], object] | None) -> None: ...
    def focusOutEvent(self, ev) -> None: ...
    def keyPressEvent(self, ev) -> None: ...
    def mousePressEvent(self, ev) -> None: ...

class NodeGraphicsItem(GraphicsObject):
    pen: Incomplete
    selectPen: Incomplete
    brush: Incomplete
    hoverBrush: Incomplete
    selectBrush: Incomplete
    hovered: bool
    node: Node
    bounds: Incomplete  # QRectF
    nameItem: TextItem
    menu: Incomplete  # QMenu | None
    def __init__(self, node: Node) -> None: ...
    def setTitleOffset(self, new_offset: float) -> None: ...
    def titleOffset(self) -> float: ...
    def setTerminalOffset(self, new_offset: float) -> None: ...
    def terminalOffset(self) -> float: ...
    def labelChanged(self) -> None: ...
    def setPen(self, *args, **kwargs) -> None: ...
    def setBrush(self, brush) -> None: ...
    terminals: dict[str, tuple[Terminal, TerminalGraphicsItem]]
    def updateTerminals(self) -> None: ...
    def boundingRect(self): ...
    def paint(self, p, *args) -> None: ...
    def mousePressEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def mouseDragEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def keyPressEvent(self, ev) -> None: ...
    def itemChange(self, change, val): ...
    def getMenu(self): ...
    def raiseContextMenu(self, ev) -> None: ...
    def buildMenu(self) -> None: ...
    def addInputFromMenu(self) -> None: ...
    def addOutputFromMenu(self) -> None: ...
