# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Literal
from typing_extensions import TypeAlias

from ..functions import _ColorArg
from ..graphicsItems.GraphicsObject import GraphicsObject
from ..Qt import QtWidgets

# A terminal is either an input or an output of its Node.
_TerminalIO: TypeAlias = Literal["in", "out"]

__all__ = ["Terminal", "TerminalGraphicsItem"]

class Terminal:
    valueOk: bool | None
    def __init__(
        self,
        node,  # the owning `Node`
        name: str,
        io: _TerminalIO,
        optional: bool = False,
        multi: bool = False,
        pos: Sequence[float] | None = None,
        renamable: bool = False,
        removable: bool = False,
        multiable: bool = False,
        bypass=None,
    ) -> None: ...
    # With no `term`, the value itself; for a multi-value input, the value
    # contributed by that one connected terminal.
    def value(self, term: Terminal | None = None): ...
    def bypassValue(self): ...
    def setValue(self, val, process: bool = True) -> None: ...
    def setOpts(self, **opts) -> None: ...
    def connected(self, term: Terminal) -> None: ...
    def disconnected(self, term: Terminal) -> None: ...
    def inputChanged(self, term: Terminal, process: bool = True) -> None: ...
    def valueIsAcceptable(self) -> bool | None: ...
    def setValueAcceptable(self, v: bool | None = True) -> None: ...
    def connections(self) -> dict[Terminal, Incomplete]: ...
    def node(self): ...
    def isInput(self) -> bool: ...
    def isMultiValue(self) -> bool: ...
    def setMultiValue(self, multi: bool) -> None: ...
    def isOutput(self) -> bool: ...
    def isRenamable(self) -> bool: ...
    def isRemovable(self) -> bool: ...
    def isMultiable(self) -> bool: ...
    def name(self) -> str: ...
    def graphicsItem(self): ...
    def isConnected(self) -> bool: ...
    def connectedTo(self, term: Terminal) -> bool: ...
    def hasInput(self) -> bool: ...
    def inputTerminals(self) -> list[Terminal]: ...
    def dependentNodes(self) -> set[Incomplete]: ...
    def connectTo(self, term: Terminal, connectionItem=None): ...
    def disconnectFrom(self, term: Terminal) -> None: ...
    def disconnectAll(self) -> None: ...
    def recolor(self, color: _ColorArg | None = None, recurse: bool = True) -> None: ...
    def rename(self, name: str) -> None: ...
    def __hash__(self) -> int: ...
    def close(self) -> None: ...
    def saveState(self) -> dict[str, Any]: ...
    def __lt__(self, other: Terminal) -> bool: ...

class TextItem(QtWidgets.QGraphicsTextItem):
    on_update: Incomplete
    def __init__(self, text, parent, on_update) -> None: ...
    def focusOutEvent(self, ev) -> None: ...
    def keyPressEvent(self, ev) -> None: ...

class TerminalGraphicsItem(GraphicsObject):
    term: Incomplete
    brush: Incomplete
    box: Incomplete
    label: Incomplete
    newConnection: Incomplete
    menu: Incomplete
    def __init__(self, term, parent=None) -> None: ...
    def labelChanged(self) -> None: ...
    def termRenamed(self, name) -> None: ...
    def setBrush(self, brush) -> None: ...
    def disconnect(self, target) -> None: ...
    def boundingRect(self): ...
    def paint(self, p, *args) -> None: ...
    anchorPos: Incomplete
    def setAnchor(self, x, y) -> None: ...
    def updateConnections(self) -> None: ...
    def mousePressEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def raiseContextMenu(self, ev) -> None: ...
    def getMenu(self): ...
    def toggleMulti(self) -> None: ...
    def removeSelf(self) -> None: ...
    def mouseDragEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def connectPoint(self): ...
    def nodeMoved(self) -> None: ...

class ConnectionItem(GraphicsObject):
    source: Incomplete
    target: Incomplete
    length: int
    hovered: bool
    path: Incomplete
    shapePath: Incomplete
    style: Incomplete
    def __init__(self, source, target=None) -> None: ...
    def close(self) -> None: ...
    def setTarget(self, target) -> None: ...
    def setStyle(self, **kwds) -> None: ...
    def updateLine(self) -> None: ...
    def generatePath(self, start, stop): ...
    def keyPressEvent(self, ev) -> None: ...
    def mousePressEvent(self, ev) -> None: ...
    def mouseClickEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...
    def boundingRect(self): ...
    def viewRangeChanged(self) -> None: ...
    def shape(self): ...
    def paint(self, p, *args) -> None: ...
