from _typeshed import StrPath
from collections.abc import Sequence

__all__ = ["getGraphIcon", "getGraphPixmap"]

class GraphIcon:
    def __init__(self, path: StrPath) -> None: ...
    @property
    def qicon(self): ...

def getGraphIcon(name: str): ...
def getGraphPixmap(name: str, size: Sequence[int] = (20, 20)): ...
