# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtWidgets  # type: ignore[import-not-found]  # pyright: ignore[reportMissingImports]

class ConsoleWidget(QtWidgets.QWidget):
    localNamespace: Incomplete
    editor: Incomplete
    output: Incomplete
    input: Incomplete
    historyFile: Incomplete
    currentTraceback: Incomplete
    def __init__(self, parent=None, namespace=None, historyFile=None, text=None, editor=None) -> None: ...
    def catchAllExceptions(self, catch: bool = True) -> None: ...
    def catchNextException(self, catch: bool = True) -> None: ...
    def setStack(self, frame=None) -> None: ...
    def loadHistory(self): ...
    def saveHistory(self, history) -> None: ...
    def globals(self): ...
    def locals(self): ...
    def cmdSelected(self, item) -> None: ...
    def cmdDblClicked(self, item) -> None: ...
