# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete, StrPath
from types import FrameType
from typing import Any

from ..Qt import QtWidgets

class ConsoleWidget(QtWidgets.QWidget):
    localNamespace: dict[str, Any]
    editor: str | None
    output: Incomplete
    input: Incomplete
    historyFile: StrPath | None
    currentTraceback: Incomplete
    def __init__(
        self,
        parent=None,
        namespace: dict[str, Any] | None = None,
        historyFile: StrPath | None = None,
        text: str | None = None,
        editor: str | None = None,
    ) -> None: ...
    def catchAllExceptions(self, catch: bool = True) -> None: ...
    def catchNextException(self, catch: bool = True) -> None: ...
    def setStack(self, frame: FrameType | None = None) -> None: ...
    def loadHistory(self) -> list[str] | None: ...
    def saveHistory(self, history: list[str]) -> None: ...
    def globals(self) -> dict[str, Any]: ...
    def locals(self) -> dict[str, Any]: ...
    def cmdSelected(self, item) -> None: ...
    def cmdDblClicked(self, item) -> None: ...
