# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

import types
from _typeshed import Incomplete
from typing import Any, Literal
from typing_extensions import TypeAlias

from ..Qt import QtWidgets

_TextStyle: TypeAlias = Literal["command", "output", "error"]

class ReplWidget(QtWidgets.QWidget):
    sigCommandEntered: Incomplete
    sigCommandRaisedException: Incomplete
    globals: dict[str, Any]
    locals: dict[str, Any]
    stdoutInterceptor: StdoutInterceptor
    ps1: str
    ps2: str
    textStyles: dict[str, Incomplete]
    def __init__(self, globals: dict[str, Any], locals: dict[str, Any], parent=None) -> None: ...
    def runCmd(self, cmd: str) -> None: ...
    def write(self, strn: str, style: _TextStyle = "output", scrollToBottom: bool | Literal["auto"] = "auto") -> None: ...
    def displayException(self) -> None: ...

class StdoutInterceptor:
    writeFn: Incomplete
    def __init__(self, writeFn) -> None: ...
    def realOutputFiles(self) -> tuple[Incomplete, Incomplete]: ...
    def print(self, *args: object) -> None: ...
    def flush(self) -> None: ...
    def fileno(self) -> Literal[1]: ...
    def write(self, strn: str) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None
    ) -> None: ...
