# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from types import FrameType, TracebackType

from ..Qt import QtWidgets

class StackWidget(QtWidgets.QTreeWidget):
    def __init__(self, parent=None) -> None: ...
    def selectedFrame(self) -> FrameType | None: ...
    frames: list[FrameType]
    def clear(self) -> None: ...
    def setException(self, exc: BaseException | None = None, lastFrame: FrameType | None = None) -> None: ...
    def setStack(self, frame: FrameType | None = None, expand: bool = True, lastFrame: FrameType | None = None) -> None: ...

def stackFromFrame(frame: FrameType, lastFrame: FrameType | None = None) -> list[FrameType]: ...
def stacksFromTraceback(tb: TracebackType, lastFrame: FrameType | None = None) -> list[Incomplete]: ...
def makeItemTree(stack, title): ...
def exceptionChain(exc: BaseException) -> list[Incomplete]: ...
def textItem(text: str): ...
