# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete

from ..Qt import QtWidgets

class StackWidget(QtWidgets.QTreeWidget):
    def __init__(self, parent=None) -> None: ...
    def selectedFrame(self): ...
    frames: Incomplete
    def clear(self) -> None: ...
    def setException(self, exc=None, lastFrame=None) -> None: ...
    def setStack(self, frame=None, expand: bool = True, lastFrame=None) -> None: ...

def stackFromFrame(frame, lastFrame=None): ...
def stacksFromTraceback(tb, lastFrame=None): ...
def makeItemTree(stack, title): ...
def exceptionChain(exc): ...
def textItem(text): ...
