# Qt base classes come from `pyqtgraph.Qt`, which typeshed cannot resolve; see README.md.
# pyright: reportUntypedBaseClass=false

from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Literal

from numpy.typing import NDArray

from ..colormap import ColorMap
from ..graphicsItems.ImageItem import ImageItem
from ..graphicsItems.PlotItem import PlotItem
from ..graphicsItems.ROI import ROI
from ..graphicsItems.ViewBox import ViewBox
from ..Qt import QtWidgets

translate: Incomplete

class PlotROI(ROI):
    def __init__(self, size: float) -> None: ...

class ImageView(QtWidgets.QWidget):
    sigTimeChanged: Incomplete
    sigProcessingChanged: Incomplete
    levelMin: float | None
    levelMax: float | None
    name: str
    image: NDArray[Any] | None
    axes: dict[str, int | None]
    imageDisp: NDArray[Any] | None
    ui: Incomplete
    scene: Incomplete
    discreteTimeLine: Incomplete
    ignoreTimeLine: bool
    view: Incomplete
    menu: Incomplete
    roi: Incomplete
    normRoi: Incomplete
    roiCurves: list[Incomplete]
    timeLine: Incomplete
    imageItem: ImageItem
    currentIndex: int
    frameTicks: Incomplete
    keysPressed: Incomplete
    playTimer: Incomplete
    playRate: int
    fps: int
    lastPlayTime: int
    normRgn: Incomplete
    normProxy: Incomplete
    noRepeatKeys: Incomplete
    def __init__(
        self,
        parent=None,
        name: str = "ImageView",
        view: ViewBox | PlotItem | None = None,
        imageItem: ImageItem | None = None,
        levelMode: Literal["mono", "rgba"] = "mono",
        discreteTimeLine: bool = False,
        roi: ROI | None = None,
        normRoi: ROI | None = None,
        *args,
    ) -> None: ...
    tVals: Incomplete
    def setImage(
        self,
        img: NDArray[Any],
        autoRange: bool = True,
        autoLevels: bool = True,
        levels: Sequence[float] | None = None,
        axes: dict[str, int] | None = None,
        xvals: NDArray[Any] | None = None,
        pos: Sequence[float] | None = None,
        scale: Sequence[float] | None = None,
        transform=None,
        autoHistogramRange: bool = True,
        levelMode: Literal["mono", "rgba"] | None = None,
    ) -> None: ...
    def clear(self) -> None: ...
    def play(self, rate: float | None = None) -> None: ...
    def togglePause(self) -> None: ...
    def setHistogramLabel(self, text: str | None = None, **kwargs) -> None: ...
    def nframes(self) -> int: ...
    def autoLevels(self) -> None: ...
    def setLevels(self, *args, **kwds) -> None: ...
    def autoRange(self) -> None: ...
    def getProcessedImage(self) -> NDArray[Any]: ...
    def close(self) -> None: ...
    def keyPressEvent(self, ev) -> None: ...
    def keyReleaseEvent(self, ev) -> None: ...
    def evalKeyState(self) -> None: ...
    def timeout(self) -> None: ...
    def setCurrentIndex(self, ind: int) -> None: ...
    def jumpFrames(self, n: int) -> None: ...
    def normRadioChanged(self) -> None: ...
    def updateNorm(self) -> None: ...
    def normToggled(self, b: bool) -> None: ...
    def hasTimeAxis(self) -> bool: ...
    def roiClicked(self) -> None: ...
    def roiChanged(self) -> None: ...
    def quickMinMax(self, data: NDArray[Any]) -> list[tuple[float, float]]: ...
    def normalize(self, image: NDArray[Any]) -> NDArray[Any]: ...
    def timeLineChanged(self) -> None: ...
    def updateImage(self, autoHistogramRange: bool = True) -> None: ...
    def timeIndex(self, slider) -> tuple[int, float]: ...
    def getView(self) -> ViewBox | PlotItem: ...
    def getImageItem(self) -> ImageItem: ...
    def getRoiPlot(self) -> PlotItem: ...
    def getHistogramWidget(self): ...
    def export(self, fileName: str) -> None: ...
    def exportClicked(self) -> None: ...
    normAction: Incomplete
    exportAction: Incomplete
    def buildMenu(self) -> None: ...
    def menuClicked(self) -> None: ...
    def setColorMap(self, colormap: ColorMap) -> None: ...
    def setPredefinedGradient(self, name: str) -> None: ...
    # Inherited from ViewBox:
    def addItem(self, item, ignoreBounds: bool = False) -> None: ...
    def removeItem(self, item) -> None: ...
