import threading
import weakref
from _typeshed import ReadableBuffer
from collections.abc import Callable, Iterable, Mapping, Sequence
from multiprocessing.connection import Connection
from typing import Any, ClassVar, Literal
from typing_extensions import TypeAlias

_CallSync: TypeAlias = Literal["off", "sync", "async"]
_ReturnType: TypeAlias = Literal["proxy", "value", "auto"]
_RequestType: TypeAlias = Literal[
    "result", "error", "getObjAttr", "callObj", "getObjValue", "transfer", "transferArray", "import", "del", "close"
]

class ClosedError(Exception): ...
class NoResultError(Exception): ...
class RemoteExceptionWarning(UserWarning): ...

class RemoteEventHandler:
    handlers: ClassVar[dict[int, RemoteEventHandler]]  # maps {process ID: handler}
    debug: bool
    conn: Connection
    name: str
    # maps {reqId: (status, result)}; when status is "error" the result is (exception, formatted exception)
    results: dict[int, tuple[Literal["result", "error"], Any]]
    resultLock: threading.RLock
    proxies: dict[weakref.ref[ObjectProxy], int]  # maps {weakref(proxy): proxyId}
    proxyLock: threading.RLock
    # keys: "callSync", "timeout", "returnType", "autoProxy", "deferGetattr", "noProxyTypes"
    proxyOptions: dict[str, Any]
    optsLock: threading.RLock
    nextRequestId: int
    exited: bool
    processLock: threading.RLock
    sendLock: threading.RLock
    def __init__(self, connection: Connection, name: str, pid: int | None, debug: bool = False) -> None: ...
    @classmethod
    def getHandler(cls, pid: int) -> RemoteEventHandler: ...
    def debugMsg(self, msg: str, *args: object) -> None: ...
    def getProxyOption(self, opt: str): ...  # the value type depends on the option
    # accepts the keys listed on proxyOptions
    def setProxyOptions(self, **kwds) -> None: ...
    def processRequests(self): ...  # -> int, the number of events processed (subclasses return None)
    def handleRequest(self) -> None: ...
    def replyResult(self, reqId: int, result: object) -> None: ...
    def replyError(self, reqId: int, *exc) -> None: ...  # *exc is a sys.exc_info() triple
    def send(
        self,
        request: _RequestType,
        opts: dict[str, Any] | None = None,
        reqId: int | None = None,
        callSync: _CallSync = "sync",
        timeout: float = 10,
        returnType: _ReturnType | None = None,
        byteData: Sequence[ReadableBuffer] | None = None,
        **kwds,
    ): ...  # None if callSync == "off", a Request if "async", otherwise the remote result
    def close(self, callSync: _CallSync = "off", noCleanup: bool = False, **kwds) -> None: ...
    def getResult(self, reqId: int): ...  # the remote result
    def _import(self, mod: str, **kwds): ...  # proxy to the imported module (or to the symbols in fromlist)
    def getObjAttr(self, obj: ObjectProxy, attr: str, **kwds): ...  # the attribute, by value or by proxy
    def getObjValue(self, obj: ObjectProxy, **kwds): ...  # the value of the proxied object
    def callObj(self, obj: ObjectProxy, args: Sequence[Any], kwds: dict[str, Any], **opts): ...  # the call's return value
    def registerProxy(self, proxy: ObjectProxy) -> None: ...
    def deleteProxy(self, ref: weakref.ref[ObjectProxy]) -> None: ...
    def transfer(self, obj: object, **kwds): ...  # a proxy for the transferred object
    def autoProxy(self, obj: object, noProxyTypes: Iterable[type]): ...  # obj itself, or a LocalObjectProxy wrapping it

class Request:
    proc: RemoteEventHandler
    description: str | None
    reqId: int | None
    gotResult: bool
    timeout: float
    def __init__(
        self, process: RemoteEventHandler, reqId: int | None, description: str | None = None, timeout: float = 10
    ) -> None: ...
    def result(self, block: bool = True, timeout: float | None = None): ...  # the remote result
    def hasResult(self) -> bool: ...

class LocalObjectProxy:
    nextProxyId: ClassVar[int]
    proxiedObjects: ClassVar[dict[int, Any]]  # maps {proxyId: object}
    @classmethod
    def registerObject(cls, obj: object) -> int: ...
    @classmethod
    def lookupProxyId(cls, pid: int): ...  # the object registered under this proxy id
    @classmethod
    def releaseProxyId(cls, pid: int) -> None: ...
    processId: int
    typeStr: str
    obj: Any  # the wrapped object
    opts: dict[str, Any]
    def __init__(self, obj: object, **opts) -> None: ...
    def __reduce__(self) -> tuple[Callable[..., Any], tuple[int, int, str, None, dict[str, Any]]]: ...

proxy = LocalObjectProxy

def unpickleObjectProxy(
    processId: int, proxyId: int, typeStr: str, attributes: Iterable[str] | None = None, opts: Mapping[str, Any] | None = None
): ...  # the local object when unpickled in its own process, otherwise an ObjectProxy

class ObjectProxy:
    def __init__(self, processId: int, proxyId: int, typeStr: str = "", parent: ObjectProxy | None = None) -> None: ...
    # accepts the keys "callSync", "returnType", "autoProxy", "timeout", "deferGetattr" and "noProxyTypes"
    def _setProxyOptions(self, **kwds) -> None: ...
    def _getValue(self): ...  # the value of the proxied object
    def _getProxyOption(self, opt: str): ...  # the value type depends on the option
    def _getProxyOptions(self) -> dict[str, Any]: ...
    def __reduce__(self) -> tuple[Callable[..., Any], tuple[int, int, str, tuple[str, ...]]]: ...
    def __getattr__(self, attr: str, **kwds): ...  # the remote attribute, by value or by proxy
    def _deferredAttr(self, attr: str) -> DeferredObjectProxy: ...
    def __call__(self, *args, **kwds): ...  # the remote return value, or a Request when called asynchronously
    def _getSpecialAttr(self, attr: str) -> DeferredObjectProxy: ...
    # Every dunder below is forwarded to the remote object through a generated `(*args)` wrapper,
    # so the argument list cannot be made more specific and the result is whatever the remote object returns.
    def __getitem__(self, *args): ...
    def __setitem__(self, *args) -> None: ...
    def __setattr__(self, *args) -> None: ...
    def __len__(self, *args) -> int: ...
    def __add__(self, *args): ...
    def __sub__(self, *args): ...
    def __div__(self, *args): ...
    def __truediv__(self, *args): ...
    def __floordiv__(self, *args): ...
    def __mul__(self, *args): ...
    def __pow__(self, *args): ...
    def __iadd__(self, *args): ...
    def __isub__(self, *args): ...
    def __idiv__(self, *args): ...
    def __itruediv__(self, *args): ...
    def __ifloordiv__(self, *args): ...
    def __imul__(self, *args): ...
    def __ipow__(self, *args): ...
    def __rshift__(self, *args): ...
    def __lshift__(self, *args): ...
    def __irshift__(self, *args): ...
    def __ilshift__(self, *args): ...
    def __eq__(self, *args): ...
    def __ne__(self, *args): ...
    def __lt__(self, *args): ...
    def __gt__(self, *args): ...
    def __le__(self, *args): ...
    def __ge__(self, *args): ...
    def __and__(self, *args): ...
    def __or__(self, *args): ...
    def __xor__(self, *args): ...
    def __iand__(self, *args): ...
    def __ior__(self, *args): ...
    def __ixor__(self, *args): ...
    def __mod__(self, *args): ...
    def __radd__(self, *args): ...
    def __rsub__(self, *args): ...
    def __rdiv__(self, *args): ...
    def __rfloordiv__(self, *args): ...
    def __rtruediv__(self, *args): ...
    def __rmul__(self, *args): ...
    def __rpow__(self, *args): ...
    def __rrshift__(self, *args): ...
    def __rlshift__(self, *args): ...
    def __rand__(self, *args): ...
    def __ror__(self, *args): ...
    def __rxor__(self, *args): ...
    def __rmod__(self, *args): ...
    def __hash__(self) -> int: ...

class DeferredObjectProxy(ObjectProxy):
    def __init__(self, parentProxy: ObjectProxy, attribute: str) -> None: ...
    def _undefer(self): ...  # a non-deferred ObjectProxy referencing the same object
